### ISSUE TITLE
Analyzer and FixAllOccurences integration and performance tests against RWC with large set of analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#10251]
Currently we have unit tests + integration tests for analyzers and FixAll, but they are executed on small code snippets with very small set of analyzers. We also have RPS tests running on RWC, but they run only with built in IDE analyzers and more focused on testing the typing performance.

We have had a bunch of performance and functional regressions reported by customers in analyzer intellisense diagnostics + FixAll experience in the VS2015 update releases - this just re-affirms our need for some real world code performance and functional tests against a larger set of analyzers.

Additionally, given that @heejaechang is planning to move the IDE diagnostic service out of proc with https://github.com/dotnet/roslyn/issues/6846 in the next update, I would say this test story is a **Primary Signoff Criteria** for that work.

We need to at least do the following items:

- [x] Identify test set (@mavasani): Identify representative set of analyzers and RWC against which we want to write tests. Ideally:
  1. Selected analyzers would be from roslyn-analyzers repo (though we can use some built-in IDE analyzers for FixAll testing).
  2. The set of analyzers + test code should generate diagnostics in at least thousands or ten thousands in number.
  3. We should probably select analyzers built against 1.0 so we can run them against VS2015 RTM, Update1 and Update2 bits for generating a baseline.

- [x] Functional test for Analyzer execution (@mavasani): Tracked by https://github.com/dotnet/roslyn/issues/10248.

- [x] Performance test for Analyzer execution (@basoundr): Tracked by https://github.com/dotnet/roslyn/issues/621.  

- [ ] Stress test for analyzer execution (@basoundr and @mavasani): Tracked by https://github.com/dotnet/roslyn/issues/10464.

- [x] Functional test for FixAll batch fixer (@mavasani): Tracked by https://github.com/dotnet/roslyn/issues/10250.

- [ ] Performance test for FixAll (@rchande): Tracked by https://github.com/dotnet/roslyn/issues/7636. 

- [x] Generate baseline for performance tests: We should generate a baseline for the above tests by running them against VS2015 RTM, Update1 and Update2. If the current performance is not reasonable compared to the baseline, we should file product bugs to improve performance.

- [x] Dogfooding/Manual testing of the new IDE engine

- [x] RPS scenario for Full solution diagnostics (@basoundr): Tracked by https://github.com/dotnet/roslyn/issues/11029

**Comment by mavasani** [comment]
Functional tests implemented with https://github.com/dotnet/roslyn-internal/pull/805

**Comment by mavasani** [comment]
The 2 pending items here are now tracked by separate perf work items and are independent of v2 engine replacement. I have manually verified FixAll performance is acceptable with v2 engine.

I am marking this story as complete and closing this issue.
