### ISSUE TITLE
Improve productivity with more refactorings

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10289]
- [x] Move Class To File (#8932)
- [ ] Allow Rename of namespaces to introduce (& maybe remove) namespace parts (#3583)
- [ ] Disable a Refactoring (#4032)
- [ ] Allow CodeRefactorings to be distributed via NuGets (#4083)
- [ ] [Feature Request] Auto Implemented Interface (#4407)
- [ ] Suggested Improvements for Change Signature (#4510)
- [ ] Proposal: Tuple and Change Signature refactoring (#11021)
- [ ] Suggestion: Allow renaming classes/methods from the Solution Explorer (#5084)
- [ ] Refactoring: Implement constructor body (#6787)
- [ ] Replace string literal with `nameof` (#7043)
- [x] Convert string.Format call to String interpolation (#7044)
- [x] QuickAction for making a class Public or adding Static (#7567)
- [ ] Support "Make Async" on methods (#7769)
- [ ] Include comments when implementing an interface with Shift+Alt+F10 (#7862)
- [ ] Refactoring: private field from constructor and vice versa (#8925)
- [ ] Refactoring: Generate boilerplate for immutable and readonly classes (#8930)
- [ ] Refactoring: Suggest converting a for-loop to LINQ (#8953)
- [ ] Split passed params into primitive types after ExtractMethod refactorings (#7389)
- [ ] Consider pattern matching for extract method scenarios (#9244)
- [x] Refactoring: Sync file name with class name (#10290)
- [ ] Refactoring: Support easily ordering/rearranging methods or arguments (#10281)
- [ ] Refactoring: Support "Ignore/Ignore All" for a code fix (#10283)
- [ ] The outline box of the inline rename is misleading (#6121)
- [ ] Renaming the default namespace should update the RootNamespace property of the project (#2062)
- [ ] Refactoring suggestion: Change generic type (#12945)
- [ ] Suggest to convert if to switch (#13438)
- [ ] Improve Preview Changes experience (#5222)
- [ ] Rename parameters should rename overrides/implementations (#5245)
- [ ] Consider addressing possible conflicts introduced by 'replace method with property'. (#5620)
- [ ] Suggestion: Select the span automatically based on cursor position for introduce local / constant (#752)
- [ ] Type generalization refactorings (#15796)
- [ ] Introduce local quick fix by declaring the local first (#15879)
- [ ] Move region/selection to file (#15979)
- [ ] Extract out local function (#16288)

**Comment by DustinCampbell** [comment]
Most of these items need descriptions. Some of them don't actually feel like they fit into this category (e.g. #7862)

Question: Do we feel like implementing all of the items in this Story produce a cohesive experience that we could call "done"? It feels a bit of a grab bag right now. It'd be great if these items were stack ranked, so we an easily prioritize. cc @kuhlenh, @Pilchie

**Comment by Pilchie** [comment]
Should be migrated to https://github.com/dotnet/roslyn/projects/5.

**Comment by jmarolf** [comment]
moved to project
