### ISSUE TITLE
Improve productivity in navigation/search

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/roslyn#10300]
- [ ] Navigation: Support forward and backward slashes in Navigate To (#10275)
- [ ] NavigateTo: Qualify nested class names with outer class (#7432)
- [x] In "Navigate To" sort results by type first (#8924)
- [ ] Go to Definition: Support Namespaces (#1014)
- [x] Find Refs needs better output formatting or grouping for partial classes (#1634)
- [ ] Bring back Go to Definition Navigation Stack (#14496)
- [ ] In "Navigate To" have smarter support for camelcase searching (#9346)
- [ ] Find All References shows error dialog on alias symbols defined via project property pages (#2079
- [ ] Find All in Visual studio based on Syntax tree (#6618)
- [x] Move 'Navigate To' search bar to center of the screen (#8929)
- [ ] Find All Refs: Re-add cascading from constructors to types (#3225)
- [x] ~~Navigation: I can't remember the shortcut key for Navigate To (#10286)~~
- [ ] ~~Navigation: Have a way to do "reverse navigation" (#10288)~~

**Comment by alrz** [comment]
Does "go to implementation" and "go to declaration" at method level (e.g. overrides) belong to this category?

**Comment by Pilchie** [comment]
The already added Go To Implementation supports this.

**Comment by alrz** [comment]
What about the other way around, e.g. from override to abstract/virtual?

**Comment by Pilchie** [comment]
That we're still sadly lacking.

**Comment by Pilchie** [comment]
Should be migrated to https://github.com/dotnet/roslyn/projects/8

**Comment by jmarolf** [comment]
Migrated issues to project
