### ISSUE TITLE
Tuples Work Items

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#10945]
This is the TODO list for the development of the tuples language feature for C# 7.
# Known issues and scenarios
- [x] VB tuples (LDM #11370)
  - [x] Conversions (needs more testing)
  - [x] Case sensitivity
  - [x] Metadata import/export
  - [x] Simple scenarios (parsing and binding for short tuples)
  - [x] Type unification
  - [x] Add support for long tuples
- [ ] Warning on tuple element name re-arrangement (https://github.com/dotnet/roslyn/issues/14217)
- [x] Metadata roundtripping (#12347)
- [x] -(RC) Review proposed changes to public API
- [ ] -(RC) Review error messages
- [x] Deconstruction (#11299)
- [x] Debugging (large)
- [ ] Making tuples available to early adopters (Roslyn Insider blockers)
  - [ ] Update issue
  - [ ] Gallery issue
  - [x] Un-install issue
  - [x] Telemetry
- [ ] IDE should help complete this code `(int word, int) t = ($$word:$$`
- [ ] Interop with KVP and other simple types (?)
- [ ] Validate proper interfaces (IEquatable, ...) (small)
- [x] Validate extension methods (small)
- [ ] Perf validation
- [x] Write spec
- [ ] Validate control/data flow 
- [ ] Validate using tuple syntax in XML doc
- [x] XML docs for public APIs
- [x] Align terminology: "elements" (not "members" or "items" or "parts"), "cardinality" or "size" (but not "arity"), "tuple literal" (rather than "tuple expression" which could be ambiguous in speech).
- [ ] Resolve [filed issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A"New+Language+Feature+-+Tuples")
- [ ] IOperations?
- [ ] Test ideas:
  - [x] Verify that the Dynamic attribute is emitted on fields and signatures.
  - [x] Compile the checked code from the ValueTuple library.
- [x] [Do we still need `TupleElementNames` property](https://github.com/dotnet/roslyn/pull/11457#discussion_r64268033)?
- [x] Betterness with names/dynamic (we drop the names when conflicting) #12585
- [x] Report diagnostic for re-using member names out of position (LDM 5/20) (small) #12585
- [x] NoPia and tuples: If Pia tries to embed a TupleTypeSymbol, it should fail because the symbol says the type is not generic, but the underlying type is generic.
- [x] Verify if various classes that deal with types need to handle TupleTypeSymbol. For example: TypeUnification, MemberRefMetadataDecoder, MemberSignatureComparer, SymbolMatcher (part of EnC).
- [x] Support tuples with only some names (LDM 5/20)
- [x] Add tuples to v7 flag (small)
- [x] Tuple conversions (medium)
- [x] Target typing
  - [x] `(byte, float) x = (1, 2)` should work
  - [x] `return (null, null)` should work in `(object, object) M()`
- [x] Publish short-term nuget package for tuples library
- [x] Get tuples library into corefx
- [x] Test with patterns (shouldn't interfere)
- [x] Update feature flag to new behavior (add diagnostics in syntax tree)
- [x] Merge with underlying type
  - [x] Retarget all members
  - [x] VT same as (tuple)
  - [x] Verify behavior for reserved member names
- [x] Update well-known tuple types to TN naming convention
- [x] Support tuples 8+
- [x] Operators (unification surfaces operators from underlying type)
- [x] Semantic info (members, declared symbols)
- [x] Interop with System.Tuple
## LDM
- [ ] Warning for name rearrangement? https://github.com/dotnet/roslyn/issues/14217 
- [x] Maybe no tuple name mismatch error when explicitly implementing interface? #12828
- [ ] Dynamic support: `dynamic x = (a: 1, b: 2); Write(x.a);`
- [x] No var support in tuple types? (answer: no. LDM 7/13)

``` C#
(byte y, var z) temp = (1, 2); // no var allowed in tuple type
(byte y, var z) = (1, 2); // but d-declaration with var is allowed
```
- [x] Should the tuple library ship with `ITuple` interface? (answer: yes, let's work out the details with corefx team)
- [x] Which reserved names to block.
- [x] Explicit conversion issues (see LDM notes 6/17 for resolution)
- [x] Names betterness (see LDM notes 6/17 for resolution)
- [x] Better betterness for tuples (see LDM notes 6/17 for resolution)
- [x] The distinction between tuple type and underlying type (if any, see proposal in #11382). (answer: the plan of record is to keep the distinction)
- [x] Kevin Halverson's scenario (answer: yes, name rules were clarified in 5/20 meeting, including partially named tuple literals)
## Corefx threads
- [ ] Copy implementation to mscorlib (https://github.com/dotnet/roslyn/issues/13177)
- [ ] Create type forwarding assemblies pointing to mscorlib (this is not needed until some post-2.0 version of netstandard)
- [ ] Add reference from NetStandard2.0 meta-package (https://github.com/dotnet/standard/issues/22)
- [ ] Adding tuple-friendly LINQ APIS
- [ ] Conversion operators and deconstruct method for simple types (KVP)
  - [ ] Identify tuple-like types
- [ ] ITuple implementation (https://github.com/dotnet/corefx/pull/10068)
  - [ ] ITuple should be in CompilerServices namespace. 
  - [ ] Possibly with a different name.
  - [ ] Only in NetStandard 2.0 (so that Tuple and ValueTuple get them at the same time)
- [ ] Add some attributes to `ValueTuple` for debug info and intellisense completion
- [x] Review `TupleExtensions`
- [x] Rename attribute to naming convention: "Item" instead of "Element"
- [x] Justify VT'0
- [x] Add Deconstruct on `ValueTuple` (no, no need)
- [x] Remove internal constraint from `ValueTuple` (no, we can leave)
- [x] New attribute for names
- [x] Publish library for `ValueTuple` 
- [x] Conversion methods and Deconstruct method for `System.Tuple` smaller than 21
# Interaction with other language features:
- [ ] Test parsing backtracking/perf
- [ ] Test incremental parsing (probably un-affected)
- [ ] Test cannot assign from dynamic

General concerns:
- [ ] Error handling/recovery
  - [ ] Errors in parsing
  - [ ] Error handling for semantic errors (e.g. ambiguous lookup, inaccessible lookup, wrong kind of thing found, instance vs static thing found, wrong type for the context, value vs variable)
  - [ ] Missing types (mscorlib or others)
- [ ] Public interface of compiler APIs, backcompat scenarios
- [ ] backward and forward compatibility (i.e. interoperation with previous and future compilers, each in both directions)
- [ ] VB/F# interop, Mono issues
- [ ] BCL and other customer impact
- [ ] Determinism
- [ ] Loading from metadata (source vs. loaded from metadata)
- [ ] Atomicity
- [ ] Edit-and-continue
- [ ] Completeness of the specification as a guide for testing (e.g. is the spec complete enough to suggest what the compiler should do in each scenario?)
- [ ] Other external documentation
- [ ] Performance
- [ ] Reflection

Types and members:
- [ ] Access modifiers (public, protected, internal, protected internal, private), static modifier
- [ ] Parameter modifiers (ref, out, params)
- [ ] Attributes (including security attribute)
- [ ] Generics (type arguments, constraints, variance)
- [ ] default value
- [ ] partial classes
- [ ] literals
- [ ] enum (implicit vs. explicit underlying type)
- [ ] expression trees
- [ ] Iterators
- [ ] Initializers (object, collection, dictionary)
- [ ] array (single- or multi-dimensional, jagged, initilalizer)
- [ ] Expression-bodied methods/properties/...
- [ ] Extension methods
- [ ] Partial method
- [ ] Named and optional parameters
- [ ] String interpolation
- [ ] Properties (read-write, read-only, write-only, auto-property, expression-bodied)
- [ ] Interfaces (implicit vs. explicit interface member implementation)
- [ ] delegates
- [ ] Multi-declaration

Code:
- [ ] Operators (see Eric's list)
  - [ ] Operator overloading
- [ ] Lvalues: the synthesized fields are mutable
  - [ ] Ref / out parameters
  - [ ] Compound operators (+=, /=, etc ..)
  - [ ] Assignment exprs
- [ ] lambdas (capture of parameters or locals, target typing)
- [ ] execution order
- [ ] Target typing (var, lambdas, integrals)
- [ ] Type inference
- [ ] Conversions
  - [ ] Implicit (identity, implicit numeric, implicit enumeration, implicit nullable, null litaral, implicit reference, boxing, implicit dynamic, implicit constant, user-defined implicit conversion, anonymous function, method group)
  - [ ] Explicit (numeric, enumeration, nullable, reference, unboxing, dynamic, user-defined)
  - [ ] Anonymous functions
- [ ] nullable (wrapping, unwrapping)
- [ ] OHI
  - [ ] inheritance (virtual, override, abstract, new)
  - [ ] overload resolution
- [ ] Anonymous types
- [ ] Unsafe code
- [ ] LINQ
- [ ] constructors, properties, indexers, events, operators, and destructors.
- [ ] Async

Misc:
- [ ] reserved keywords (sometimes contextual)
- [ ] pre-processing directives
- [ ] COM interop
  # Interaction with Debugger:
- [ ] typing in immediate/watch window (that also covers hovering over a variable)
- [ ] displaying locals (that also covers autos)
# Interaction with IDE:
- [ ] Colorization
- [ ] Type ahead
- [ ] Intellisense (squiggles, dot completion)
- [ ] Renaming
- [ ] Interaction with incomplete code scenarios (e.g. while typing)
- [ ] More complete list: https://github.com/dotnet/roslyn/issues/8389
