### ISSUE TITLE
Deconstruction work items

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#11299]
This list is no longer maintained. Remaining work items and issues are tracked as [issues with label "Tuples"](https://github.com/dotnet/roslyn/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Language+Feature+-+Tuples%22).

This is the TODO list for the development of the deconstruction language feature for C# 7.

# Known issues and scenarios
- [ ] Wildcard support #12619
- [x] Update spec (here's the [branch to work on](https://github.com/jcouv/roslyn/blob/deconstruction-design/docs/features/deconstruction.md))

- [ ] Deconstruction-assignment
    - [ ] -(2.1) Support Edit-and-Continue #12436
    - [ ] Refine data flow analysis to simulate final evaluation and order
        - [ ] [Properties on the left](https://github.com/dotnet/roslyn/pull/11384#discussion_r63827875)
   - [ ] Don't [prematurely resolve lazy diagnostics](https://github.com/dotnet/roslyn/pull/11983/files/7e79c2602331b9f673e25d1b179e85be556979f0#r67014572)
   - [ ] Optimize common cases
        - [ ] Verify whether [this IL](https://github.com/dotnet/roslyn/pull/11457/files/7170bd2011e6811720493aee7452f9dfc487dd1d#r64249212) is correct
   - [ ] Test ideas:
       - [x] ref returning methods on the left. Check sideeffects.
       - [x] Foo()[Bar()] on the left, where all Foo, Bar and the indexer have sideeffects - print something
       - [x] check IL in simple/common cases
       - [ ] `(.... ) = async Expr();`
       - [ ] [define Deconstruct in VB](https://github.com/dotnet/roslyn/pull/11873#issuecomment-225062291)
    - [ ] Consider making AssignmentInfo a struct
    - [x] Verify [correct handling of dynamic](https://github.com/dotnet/roslyn/pull/11715#discussion_r65787272)
   - [ ] [Optimize case were RHS is a local](https://github.com/dotnet/roslyn/pull/11457#discussion_r64171416)
    - [x] Have a field with the common references used in tests (SystemCoreRef, ValueTupleRef, ...)
    - [x] Warnings on out-of-position names
    - [x] Update evaluation order to reflect LDM decision #12400
    - [x] Update return type to be a tuple, instead of void. #12635
    - [x] Including tuple literal (there should be no conversions before the tuple elements are evaluated)
   - [x] Improve error message in [NullRight test](https://github.com/dotnet/roslyn/pull/11457/files/7170bd2011e6811720493aee7452f9dfc487dd1d#r64293508)
    - [x] Refer to more specific location in error messages
    - [x] Factor code that is common to out vars after merging together.
    - [x] Return type (void)
    - [x] Optimize the case where LHS variable is simple ref value
    - [x] tuple/ValueTuple deconstruction
        - [x] Does `(previous, current, next) = (current, next, null)` fail due to no type on right-hand-side in which to look up `Deconstruct`? (no, tuples don't need Deconstruct)
    - [x] Nesting case
    - [x] Finding `Deconstruct` from base or from extension method.
        - [x] Re-visit the resolution for Deconstruct, using the resolution logic from "out vars".
        - [x] Verify Deconstruct is an instance method.
        - [x] System.Tuple deconstruction
    - [x] Move binding code to separate file.
    - [x] Should deconstruction-assignment the same syntax model as deconstruction-declaration? (currently is uses a VariableDeclaration with a tuple type as the type). (answer: I don't think so)
    - [x] [Consider ](https://github.com/dotnet/roslyn/pull/11384#discussion_r63825210) using a BadExpression in binding (answer: I don't think so as it makes the diagnostics worse)

- [ ] Deconstruction-declaration
    - [x] -(RC) Put OmittedType instead of null in `VariableDeclaration.Type` (make it non-optional again). #12588  
    - [ ] -(2.1) Support other contexts: From, Let
    - [ ] Improve parsing fault tolerance and diagnostics as Cyrus suggested. For example, if you type `var (int x, string y = null) = M();`
    - [ ] Reporting error if you try to use deconstruct syntax in unsupported contexts (like `using`).
    - [x] Review #12534 with Aleksey
    - [ ] Test ideas:
        - [ ] Implicit anonymous function parameter list, e.g. `(x, (y, z)) => ...` 
        - [ ] out var, e.g. `M(out var (x, y))` 
        - [ ] Test region analysis API. (Neal)
        - [ ] Test with dynamic and verify attribute is properly emitted. (Chuck, #12398)
        - [ ] Test symbols in `(Type1 x, Type2 x) = foo;`
        - [ ] Add test for sequence points
        - [x] `(int x, int y) = x;` // flow analysis
        - [x] Declaring a ref-returning method called `var` should give an error.
    - [x] Support typeless tuple literals in deconstruction declarations #12410
    - [x] -(RC) Add validation to factory methods (only allow creating valid combinations with reasonable-looking children)
    - [x] -(RC) Add validation logic or erasure to WithXYZ methods
    - [x] Consider [simplifying tree walking ](https://github.com/dotnet/roslyn/pull/12224#discussion_r68774996) in new local symbol. (answer: N/A)
    - [x] Support local declaration, for, foreach
    - [x] Circularity problem (including nested case)
    - [x] Formatting issue and coloring in IDE with `var (x, y) = ...` syntax.

- [x] Write spec

- [ ] Resolve [filed issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A"New+Language+Feature+-+Tuples")

## LDM
- [x] D-assignment return type: could we make use of the return-type of Deconstruct method?
- [x] D-declaration with typeless tuple literals. (answer: let's make it work. LDM 7/13)
  
 ```C#
(string x, byte y, var z) = (null, 1, 2); // what is the type on the RHS?
(string x, byte y) temp = (null, 1); // the type on the right is (string, byte)
    ```
- [x] What is the return type of a deconstruction-assignment expression? Void or some tuple? (answer: currently void, but if we have time let's do smart tuple return. LDM 7/13)
    - [x] Treat Deconstruct as a kind of conversion in more scenarios?
    ```C#
(object z5, long z6) = KVP.Create("hello", 42); // You can do this (deconstruction)
(object z8, long z9) z7 = KVP.Create("hello", 42); // You cannot do this...
    ```
- [x] I assume no compound assignment `(x, y) += M();` (answer: not at this point. LDM 7/13)
- [x] Wildcard? (answer: yes, should probably be star. LDM 7/13)
- [x] Should anonymous types have a Deconstruct? (answer: no, low value. LDM 7/13)
- [x] Should names matter in deconstruction? (answer: yes, let's warn tuple literal `var (x, y) = (a: 1, x: 2);`)
- [x] Confirm that `var (x, y) = ...` should be an error if `var` type exists. (answer: correct)
- [x] Confirm that `var (x, y) = ...` is a deconstruction even when a ref-returning "var" method exists. (answer: correct)
- [x] FYI the Deconstruct method is now resolved like an invocation with out vars. (confirmed, yes)
    - [x] This has implications on bad Deconstruct shadowing another good one (see `BadDeconstructShadowsBaseDeconstruct`). (confirmed, that's ok)
    - [x] Can dynamic be desconstructed? (answer: no)
- [x] What contexts are deconstruction-declarations allowed in?  (answer: LDM confirmed the prioritization above)
    - P0: local declaration, for statement, foreach, 
    - P1: let clause, from clause, 
    - later: lambda, method declaration, using, outvar, join clause, query continuation clause, join into clause, catch.
- [x] Is `(int x, var (y, z)) = M();` allowed? (answer: yes)
- [x] I assume no mix of assignment and declaration `int x; (x, int y) = M();` (answer: confirmed in 5/25 LDM)
- [x] I assume deconstruction-assignment should work even if System.ValueTuple is not present. (answer: correct)
- [x] Switching to tuple-returning-Deconstruct? (answer: no)
- [x] What is the evaluation order for nested deconstruction-assignment? (answer: all LHS side-effects, all RHS, all conversions, all assignments)
- [x] Finalize syntax for deconstruction-declaration. (answer: `var (x, y) = M();` and `(int x, int y) = M();`)
    - [x] Reserving ‘var’, or maybe give up on ‘var (x, y) = M();’ syntax that is ambiguous with method invocation. (answer: no need)
    - [x] Considering ‘@’ to simplify parsing of deconstructions. (answer: no need)
- [x] Do the names matter? `int x, y; (a: x, b: y) = M();` (answer: for now this should be error)

# Interaction with other language features:

General concerns:
- [ ] Error handling/recovery
    - [ ] Errors in parsing
    - [ ] Error handling for semantic errors (e.g. ambiguous lookup, inaccessible lookup, wrong kind of thing found, instance vs static thing found, wrong type for the context, value vs variable)
    - [ ] Missing types (mscorlib or others)
- [ ] Public interface of compiler APIs, backcompat scenarios
- [ ] backward and forward compatibility (i.e. interoperation with previous and future compilers, each in both directions)
- [ ] VB/F# interop, Mono issues
- [ ] BCL and other customer impact
- [ ] Determinism
- [ ] Loading from metadata (source vs. loaded from metadata)
- [ ] Atomicity
- [ ] Edit-and-continue
- [ ] Completeness of the specification as a guide for testing (e.g. is the spec complete enough to suggest what the compiler should do in each scenario?)
- [ ] XML docs and other external documentation
- [ ] Performance
- [ ] Reflection
- [ ] Review proposed changes to public API
- [ ] Debugging
- [ ] Leverage feature in Roslyn codebase (dogfood)

Types and members:
- [ ] Access modifiers (public, protected, internal, protected internal, private), static modifier
- [ ] Parameter modifiers (ref, out, params)
- [ ] Attributes (including security attribute)
- [ ] Generics (type arguments, constraints, variance)
- [ ] default value
- [ ] partial classes
- [ ] literals
- [ ] enum (implicit vs. explicit underlying type)
- [ ] expression trees
- [ ] Iterators
- [ ] Initializers (object, collection, dictionary)
- [ ] array (single- or multi-dimensional, jagged, initilalizer)
- [ ] Expression-bodied methods/properties/...
- [ ] Extension methods
- [ ] Partial method
- [ ] Named and optional parameters
- [ ] String interpolation
- [ ] Properties (read-write, read-only, write-only, auto-property, expression-bodied)
- [ ] Interfaces (implicit vs. explicit interface member implementation)
- [ ] delegates
- [ ] Multi-declaration

Code:
- [ ] Operators (see Eric's list)
    - [ ] Operator overloading
- [ ] Lvalues: the synthesized fields are mutable
    - [ ] Ref / out parameters
    - [ ] Compound operators (+=, /=, etc ..)
    - [ ] Assignment exprs
- [ ] lambdas (capture of parameters or locals, target typing)
- [ ] execution order
- [ ] Target typing (var, lambdas, integrals)
- [ ] Type inference
- [ ] Conversions
    - [ ] Implicit (identity, implicit numeric, implicit enumeration, implicit nullable, null litaral, implicit reference, boxing, implicit dynamic, implicit constant, user-defined implicit conversion, anonymous function, method group)
    - [ ] Explicit (numeric, enumeration, nullable, reference, unboxing, dynamic, user-defined)
    - [ ] Anonymous functions
- [ ] nullable (wrapping, unwrapping)
- [ ] OHI
    - [ ] inheritance (virtual, override, abstract, new)
    - [ ] overload resolution
- [ ] Anonymous types
- [ ] Unsafe code
- [ ] LINQ
- [ ] constructors, properties, indexers, events, operators, and destructors.
- [ ] Async

Misc:
- [ ] reserved keywords (sometimes contextual)
- [ ] pre-processing directives
- [ ] COM interop

 # Interaction with Debugger:
- [ ] typing in immediate/watch window (that also covers hovering over a variable)
- [ ] displaying locals (that also covers autos)

# Interaction with IDE:
- [ ] Colorization
- [ ] Type ahead
- [ ] Intellisense (squiggles, dot completion)
- [ ] Renaming
- [ ] Interaction with incomplete code scenarios (e.g. while typing)
- [ ] More complete list: https://github.com/dotnet/roslyn/issues/8389

# References

#10642
