### ISSUE TITLE
"Out Variable Declaration" work items and open design issues

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#11566]
The purpose of this issue is to track the TODO list and the list of open design issues for the development of the Out Variable Declaration feature for C# 7. There is also a discussion thread for this feature at #6183.

**Open issues:**
- [X] ~~The specification for overload resolution needs to be modified to account for the inference of the type of an _out variable_s declared with `var`.~~
- [X] ~~There is a proposal pending LDM decision: An _out variable_ is read-only. 
  If that proposal is approved, we should see if ILocalSymbol should be extended to make the read-only status discoverable.~~ LDM has made a decision to keep the variables writable.
- [X] ~~There is a proposal pending LDM decision:
  An _out variable_ may not be referenced before the close parenthesis of the invocation in which it is defined:~~ LDM has made a decision to not apply this restriction to explicitly typed variables. 

``` cs
    M(out int x, x = 3); // allowed
    M(out var x, x = 3); // error
```
- [X] ~~LDM should take another look at the restriction that disallows Out Variable Declarations within constructor initializers. We might want to remove it after all.~~ LDM has made a decision to remove this restriction.  

**TODO:**
- [X] ~~Add tests for scope rules. Given that currently scoping rules match the rules for pattern variables, and implementation takes advantage of existing infrastructure added for pattern variables, the priority of adding these tests is low. We have pretty good suite of tests for pattern variables.~~ 
- [ ] Add tests for lambdas and await capturing out variables. 
- [X] ~~Need to get an approval for the new SemanticModel.GetDeclaredSymbol API.~~ The API has been removed because, given the new Syntax Model, we can rely on the existing API.
- [X] ~~Work with IDE team on feature specific refactorings.~~ 

**Related:**
- LDM notes on [expression variables in queries](https://github.com/dotnet/csharplang/blob/master/meetings/2016/LDM-2016-12-07-14.md#expression-variables-in-query-expressions)

**Comment by AdamSpeight2008** [comment]
Can you clarify this?
> - There is a proposal pending LDM decision: An out variable may not be referenced before the close parenthesis of the invocation in which it is defined:

The **out variable** can not be referred to, within the other parameters of the method.

```
    M(out x, x = 3, 0); // error
```
--------
Is the proposal the equivalent to the following?
```
M( out x, x = 3)
// Equivalent to 
int x; 
M( out x , x = 3 )
```
If so, then to referred to restriction, isn't a restriction.

-----

Is the **our variable` accessible with then other branches of the `if`?

```vb.net
If M(out x, "FOO" ) Then
' ...
Else If m = 0 Then
 ' ...
Else
  Console.Write(x)
End If
```

**Comment by AlekseyTs** [comment]
@AdamSpeight2008 As clearly stated at the top of this issue, this **is not** an issue for discussions. There is a discussion thread for this feature at https://github.com/dotnet/roslyn/issues/6183. I'll give you  a couple of hours to move your comments and then I am going to delete them from here.
