### ISSUE TITLE
[Umbrella] ValueTuple library work

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#13177]
Documentation of the various slices in the ValueTuple package:

Targeting pack | Contents
-----------------|-----------
netcoreapp1.1 | Ref and lib assemblies type-forwards to System.Runtime ref assembly, which type-forwards to System.Private.Corelib (from CoreCLR or CoreRT).
netstandard1.0 and up | Assembly implements ValueTuple and depends on System.Runtime
netstandard2.0 and up | Relies on netstandard package
PCL | Assembly implements ValueTuple, but depends on mscorlib. Note that the precedence rules on targets means that PCL is picked when targeting desktop 4.5.
desktop 4.7 | type-forwards ValueTuple to mscorlib

-----------------------------
## Known issues
Most prominent issue is when targeting desktop 4.6 (or lower) and referencing the ValueTuple package, then running on machine with desktop 4.7 installed.
The symptom are that tuples don't work in EE, interactive and possibly ASP.NET.
Workaround options: (1) target 4.7, or (2) remove ValueTuple dependency, or (3) run without 4.7 installed.
See https://github.com/dotnet/corefx/issues/16195 for more details.

-----------------------------

## Work items

Adding `System.ValueTuple` to various corlib implementations:
- [x] corefx (to first ship as [nuget package version 4.3.0](http://www.nuget.org/packages/System.ValueTuple/)) ([PR](https://github.com/dotnet/corefx/pull/7803))
- [x] mscorlib/desktop (to first ship with upcoming desktop framework) ([changeset](http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/1627677), [bug](https://devdiv.visualstudio.com/DevDiv/_workitems?id=257122&_a=edit))
- [x] corlib/coreCLR (https://github.com/dotnet/coreclr/pull/8695)
- [x] corlib/coreRT (https://github.com/dotnet/corert/pull/2399)
- [x] mscorlib/xamarin (to first ship with Xamarin Cycle10)

Add `ITuple` to `System.Tuple` and `System.ValueTuple` to those corlibs:
- [x] mscorlib/desktop (to first ship in the first version after 4.7)
- [x] corlib/coreCLR (to first ship in [version 1.2 of the package](https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR))
- [x] corlib/coreRT
- [x] mscorlib/xamarin (done in https://github.com/mono/mono/commit/ddb72c43c8d092c651cb8abfc0d4dd7feee4aa5e)

After that:
- [x] Update coreFX with type forwarders to coreCLR (done in https://github.com/dotnet/corefx/pull/14786)
- [x] add tests in coreFX for the ITuple implementation in coreCLR (done in https://github.com/dotnet/corefx/pull/14786)
- [x] Fix coreFX lib assembly typeforewarders in target group = "netcoreapp1.1" to point to `System.Runtime` instead of `System.Private.CoreLib` (https://github.com/dotnet/corefx/issues/15475, done with https://github.com/dotnet/corefx/commit/17fdb439c50f4aa66a99f9b5549e9db923331e40)
- [x] Update coreFX with type forwarders to coreRT (https://github.com/dotnet/corefx/issues/15176) (this was done implicitly as the result of the type-forward for netcoreapp1.1 and a subsequent cleanup by Eric)
- [x] Update coreFX with type forwarders to desktop 4.7 (issue https://github.com/dotnet/corefx/issues/15175, PR https://github.com/dotnet/corefx/pull/18519)
- [x] Add ValueTuple in .Net Standard
- [x] Add ValueTuple to .Net Standard meta-package in the meanwhile (https://github.com/dotnet/standard/issues/22, PR: https://github.com/dotnet/standard/pull/279)
- [x] Add support for Xamarin in ValueTuple package (https://github.com/dotnet/corefx/issues/14235, https://github.com/dotnet/corefx/pull/16447) (should ship as patch right after 1.1.0)
- [x] Add ValueTuple to .Net Core 2.0 shared framework (issue https://github.com/dotnet/corefx/issues/17797)

Make `System.ValueTuple` binary serializable (https://github.com/dotnet/corefx/issues/15229) (which will ship together with `ITuple` above):
- [x] mscorlib/desktop with tests ([work item](https://devdiv.visualstudio.com/DevDiv/_workitems?id=378419), [changeset](http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/1646459))
- [x] corlib/coreCLR (https://github.com/dotnet/coreclr/pull/9271)
- [x] in coreFX, ~~update ref assembly (add serializable attribute) and~~ add tests to cover coreCLR implementation
- [x] corlib/coreRT (https://github.com/dotnet/corert/pull/2644)
- [x] mscorlib/xamarin (I think nothing to be done)
- [x] Add compiler end-to-end tests (with tuple syntax)

Hash seed randomization: 
- [ ] desktop (could be considered)
- [x] coreFX (done with Guid)
- [x] coreCLR (done with Random)
- [x] coreRT (done with Random)

EqualityComparer optimization: 
- [x] desktop (N/A, the underlying runtime does not have the optimization)
- [x] coreFX (N/A, cannot be done because that ValueTuple code can run on existing runtimes that don't have the underlying optimization)
- [x] coreCLR (done)
- [x] coreRT (https://github.com/dotnet/corert/pull/3021)

Various BCL improvements:
- [ ] Zip and Unzip LINQ APIs (https://github.com/dotnet/corefx/issues/16011)
- [ ] GetAwaiter for tuples of Tasks (https://github.com/dotnet/roslyn/issues/16159#issuecomment-278521187, https://github.com/dotnet/corefx/issues/16010)
- [ ] Deconstruct on KeyValuePair and DictionaryEntry (https://github.com/dotnet/coreclr/issues/8560, [VSO](https://devdiv.visualstudio.com/DevDiv/_workitems?id=299547))

Downgrade warnings issue:
~~- [ ] Change dependencies of ValueTuple package to reference 1.0.0 baseline ([issue](https://github.com/dotnet/corefx/issues/15826), [fix](https://github.com/dotnet/corefx/pull/16119))~~ (closed "by design", customer should upgrade their 1.0 projects to 1.1 to use `ValueTuple`).

EE bug with not loading mscorlib
- [x] Fix in 15.3 and ported to 15.2 (https://github.com/dotnet/roslyn/pull/18552)

Clash between ValueTuple.dll and mscorlib.dll from new desktop framework (in short, a workaround was added to EE and a facade assembly was added to mscorlib in desktop 4.7.1 that type unifies with ValueTuple assembly version 4.1.*):
- [x] EE issue (https://github.com/dotnet/corefx/issues/16195, [VSO](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=385832))
- [x] Scripting issue (https://github.com/dotnet/roslyn/issues/17157)
- [x] Compiler workaround (https://github.com/dotnet/roslyn/pull/17192)
- [x] Desktop 4.7.1 fix (GAC and type unification) (Sep ETA)
- [ ] Consider removing the EE workaround

Various bugs/proposals:

- [x] Issue with partial trust (https://github.com/dotnet/coreclr/issues/10123)
- [x] Verify package still works after netstandard change (https://github.com/dotnet/corefx/issues/17960)
- [x] Proposal to optimize comparison logic (https://github.com/dotnet/corefx/issues/18666)

Change behavior when comparing with `null` (https://github.com/dotnet/corefx/issues/18528) (we ended up cancelling to keep Tuple and ValueTuple APIs more stable)
- In Core 2.0 (PR https://github.com/dotnet/coreclr/pull/11345)
- In desktop (version after 4.7.1, to give more bake time and not require quirking)
- ValueTuple package (it will be left as-is)
- Mono?

**Comment by jcouv** [comment]
Added code and test code for mscorlib/desktop ([changeset](http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/1627677), [bug](https://devdiv.visualstudio.com/DevDiv/_workitems?id=257122&_a=edit))

**Comment by jcouv** [comment]
Marek added code and test for mscorlib/xamarin (https://github.com/mono/mono/commit/0a515cf13be8b87993c60494d2be80df17031bfe)

It will be part of Xamarin Cycle10 release which is expected to be in line with VS Jan/Feb release.

**Comment by jcouv** [comment]
Added ITuple to mscorlib/desktop ([changeset](http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/1639983))

**Comment by jamesqo** [comment]
When porting the change to coreclr/corert, consider cherry-picking the changes from https://github.com/dotnet/corefx/pull/14187 which should substantially speed up `GetHashCode`.

**Comment by jcouv** [comment]
@jamesqo Makes sense. When I port ValueTuple to coreclr/corert, I will use the latest code from corefx at that time (so it will include the hashcode changes).

**Comment by jcouv** [comment]
Working on changes to corlib in CoreCLR (https://github.com/dotnet/coreclr/pull/8695) and CoreRT (https://github.com/dotnet/corert/pull/2399).

**Comment by jcouv** [comment]
Working to remove ITuple constraint from TRest ([workitem](https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=363866))

**Comment by jcouv** [comment]
Added type forwards from CoreFx (`System.ValueTuple` and `System.Runtime`) to CoreCLR's implmentation in `System.Private.CoreLib` (https://github.com/dotnet/corefx/pull/14786)

**Comment by jcouv** [comment]
Mono now re-uses the code from CoreRT, which means it has ITuple too (https://github.com/mono/mono/commit/ddb72c43c8d092c651cb8abfc0d4dd7feee4aa5e)

**Comment by jcouv** [comment]
The remaining bullets from the list above will now be tracked by individual issues. None of them is essential at this point. I'll close this umbrella.

**Comment by jcouv** [comment]
[An issue was reported](https://developercommunity.visualstudio.com/content/problem/130199/155-preview-cannot-build-c-projects-using-systemva.html) with 15.5, possibly related to ASP.Net, but not yet diagnosed.

**Comment by Tornhoof** [comment]
Same issue happens on 15.4 after installing .NET 4.7.1 DevPack and changing the framework version to .NET 4.7.1.
I had to  add the ValueTuple Nuget package (4.4) to the projects otherwise it wouldn't compile.
Error is: ``Error	CS8137	Cannot define a class or member that utilizes tuples because the compiler required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found. Are you missing a reference?``

**Comment by jcouv** [comment]
@Tornhoof I think you're describing a problem that has been identified and acknowledged with 4.7.1.. Can you try and see if the mitigation described in [this thread](https://github.com/Microsoft/dotnet-framework-early-access/issues/9) (manually editing auto-generated binding redirects) works for the issue you're describing?

**Comment by Tornhoof** [comment]
Yes, manually removing the value tuple redirect fixes it. Unfortunately manually removing something from the auto-generated redirects in the new SDK Project system is a bit of work, for now I prefer my NuGet workaround as it fixes the bindings automatically.
