### ISSUE TITLE
[Umbrella] Places where runtime bugs interfere with compiler or language evolution

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#13295]
This is a collection of issues where limitations or bugs in the current runtime have been significant impediments to compiler or language evolution. This list will evolve over time as new cases are identified or fixed.
- [ ] #10126 Loader bug incorrectly reports struct cycle for static field (https://github.com/dotnet/coreclr/issues/4049)
- [ ] Loader bug incorrectly reports struct cycle for unused type parameter (https://github.com/dotnet/coreclr/issues/7957)
- [ ] #3711 Delegate combine fails at runtime (https://github.com/dotnet/coreclr/issues/1712)
- [ ] #1029 Bug in Activator.CreateInstance prevents default struct ctors (https://github.com/dotnet/coreclr/issues/6843)
- [ ] https://github.com/dotnet/corefx/issues/4112   No API to pass Type.Missing argument through reflection calls. Completely blocks some "dynamic" scenarios involving optional parameters when platform requires interpreting. (C# binder uses Type.Missing to designate omitted arguments and it is a problem that they do not survive calls via reflection)
- [ ] https://github.com/dotnet/csharplang/issues/124 Support generic attributes (https://github.com/dotnet/coreclr/pull/9189 runtime throws an exception when reflecting on an attribute type that is generic)

**Comment by gafter** [comment]
This issue is moved to https://github.com/dotnet/csharplang/issues/251
