### ISSUE TITLE
GetService Calls in constructors

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#15148]
There are quite a few calls to GetService in the constructors of MEF-created objects. This can potentially cause deadlocks in VS, there have a few other deadlock issues because GetService ends up needing to make COM calls. We should fix these to import the needed types in the constructor instead of using GetService calls before we run into issues. These are the remaining instances I've found after #15145. Related to #15143.

* [x] [DefinitionsAndReferencesPresenter](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/Def/Implementation/FindReferences/DefinitionsAndReferencesPresenter.cs#L26) (removed in https://github.com/dotnet/roslyn/pull/20905)
* [x] [NavigableItemsPresenter](https://github.com/dotnet/roslyn/blob/2d339b4b10bb9a7bdb0b4c643aeebed928b5e485/src/VisualStudio/Core/Def/Implementation/GoToDefinition/NavigableItemsPresenter.cs#L24) (removed in #20905)
* [x] [VisualStudioWaitIndicator](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/Def/Implementation/Utilities/VisualStudioWaitIndicator.cs#L29) (fixed in #34218)
* [x] #55277
* [x] [DeferredProjectWorkspaceService](https://github.com/dotnet/roslyn/blob/5b71ff5f14a541570ca3f109674c80ed83c6639a/src/VisualStudio/Core/Next/ProjectSystem/DeferredProjectWorkspaceService.cs#L27) - This one is a lazy use where the lazy initialization possibly isn't on the UI thread. (removed in #23317)
* [x] #55278
* [x] [LanguageSettingsPersister](https://github.com/dotnet/roslyn/blob/8ea6a8f5b3cc3d30324e6f0b8608f9fc79cd4846/src/VisualStudio/Core/Def/Implementation/Options/LanguageSettingsPersister.cs#L54) - This one needs to be converted to a proper initializer, it's doing a lot of work in the constructor. (#37377)
* [x] #55280
* [x] #55281
* [x] [VisualStudioDiagnosticListTable](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/Def/Implementation/TableDataSource/VisualStudioDiagnosticListTable.cs#L43) - Optional import (fixed in #36098)
* [x] #55282
* [x] [AnalyzersFolderItemProvider](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/SolutionExplorerShim/AnalyzersFolderItem/AnalyzersFolderItemProvider.cs#L32) (fixed in #48831)
* [x] [StreamingFindReferencesPresenter](https://github.com/dotnet/roslyn/blob/65cc61578e9646cf76a297d8a9e0005afa57378a/src/VisualStudio/Core/Next/FindReferences/StreamingFindReferencesPresenter.cs#L63) (fixed in #41191)
* [x] #55283
* [ ] #55284
* [x] #55285
* [x] [VirtualMemoryNotificationListener](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/Def/Implementation/VirtualMemoryNotificationListener.cs#L49) (fixed in #54378)
* [x] [XamlTextViewCreationListener](https://github.com/dotnet/roslyn/blob/fb95b42c5c1a5ed832f3ab999be4de0f4526e2d5/src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs#L59) (fixed in #48459)
* [x] [VisualStudioSymbolNavigationService](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs#L47) (fixed in #50889)
* [x] [VisualStudioWorkspaceImpl](https://github.com/dotnet/roslyn/blob/6181abfdf59da26da27f0dbedae2978df2f83768/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs#L66) (fixed in #14354)
* [ ] #55286
* [x] #55287
* [x] #55288
* [x] [SaveEventsService](https://github.com/dotnet/roslyn/blob/84bc7eea2e05e9d9d7e1b53c2a107c0ac9857a72/src/VisualStudio/Core/Def/Implementation/SaveEventsService.cs#L37-L38) (removed in #32623)

**Comment by 333fred** [comment]
Note that some of these might be fine, if we're guaranteed to be on the correct thread when called. But we should verify and comment where appropriate in that case.

**Comment by BillHiebert** [comment]
Note that I just reproduced this failure with build d15rel.26118.00 but opening an asp.net core web project.

**Comment by Pilchie** [comment]
@BillHiebert we're still tracking [VSO bug 268787](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/268787) to fix the specific cases that we know are bad, and https://github.com/dotnet/roslyn/pull/14354 is our current attempt to fix it.  As soon as we understand why that introduces other deadlocks in our tests, we'll be bringing a fix.

**Comment by davkean** [comment]
@Pilchie That PR hasn't be touched for two months. Here's an issue that was been hit multiple times: https://github.com/dotnet/roslyn/issues/16642. I'd like to not dup these as it likes like that PR isn't going to be merged anytime soon.

**Comment by Pilchie** [comment]
AFAIK, that PR is our only chance of getting this fixed, and it is *definitely* on @jasonmalinowski's radar for VS2017.

**Comment by CyrusNajmabadi** [comment]
@sharwell is there anything left to do here.  If not, please close out.

**Comment by CyrusNajmabadi** [comment]
Closing out.  If there are items remaining we can find and fix individually.
