### ISSUE TITLE
Work items for LanguageVersion 7.1 and point releases

### ISSUE THREAD

**Issue by VSadov** [dotnet/roslyn#17173]
Update (jcouv): Updated the issue to capture proposal and open issues.

Here's the current proposal:

In the IDE, the dropdown will just have new entries, “C# 7.1”, …, “C# 8.0”, in addition to current options.
It will also have a new entry “latest”, which means ‘latest latest’ version. The existing “default” option means ‘latest major’ version. 
We will likely re-label “latest” and “default” to friendlier names in the UI, but we will keep the default as ‘latest major’.

No change in msbuild (just passing langver through, as today).

In the compiler:
Langver command-line parameter is a string and currently accepts “7”, “default”, and some more. It will support new options: “7.1” and “latest”.
The public API enum, `LanguageVersion`, will have a new entry with label “CSharp7_1” and enum value `71` (integer). C# 8 will be represented with label “CSharp8” and value `80`. The enum already supports “Latest”.

## General tracking of compiler adoption with new releases

| Host | Users can upgrade? | Upgraded by default? | Allows dogfooding | Plan |
| ------|-----------------------|-------------------------|-----------------------|------|
| VS | Yes, install VSIX. But un-install problem | Yes. Default is “default” (not “latest”). Lighbulb helps upgrade existing projects | Somewhat (but no channel for Roslyn/master yet). Roslyn insider extension currently broken. |  Fix SDK un-install issue. Could we get a channel with Roslyn/master? |
| asp.net | Manually (update compiler nuget and fix web.config). | Yes (new projects in VS2017 use C# 7.0). No for existing projects.  | |  Maybe we could offer lightbulb too? |
| CLI | Practically, no (very difficult). | Not sure. | No. | Use package integration. .Net Core 2.0 should offer C# 7.0. Not sure about 7.1. |
| corext | | |  | Move to package dependency. |
| Mono | No. Mono still using own compiler | | | Mono planning to adopt Roslyn compiler for Mono 5.0. I don’t know how easy to upgrade from there. |
| Unity | They depend on mono using Roslyn first | | |
| Azure functions |  | Consumes nuget package. Likely uses "default" language version. | | Fabio will update to C# 7.0 package. After that we should discuss using "latest". |
| Powershell | I don't think so | | |
| Linqpad | Not sure | Yes (Linqpad seems to pick up new compiler quickly) | No |

## Work items for adding 7.1

- [x] We need to confirm whether the enum value stays `71` (adequate for less than 9 minor versions) or become `701` or whatever. Once the value is settled, the output needs to be fixed and tests will have to be adjusted. (fixed in https://github.com/dotnet/roslyn/pull/17894)
- [x] The parsing of command-line parameter should not accept "71", but rather "7.1" (fixed in https://github.com/dotnet/roslyn/pull/17894)
- [x] Fix the error message (it should print "7.1", instead of the "71" currently) (fixed in https://github.com/dotnet/roslyn/pull/17894)
- [x] Add entries to UI ("7.1" and "latest") and re-label as discussed
    - "C# latest major version (default)”
    - "C# latest minor version (latest)” 
- [x] Add code fixer so that `ERR_FeatureNotAvailableInVersion7` offer "upgrade this project to use 'latest'" and "upgrade all projects to use 'latest'". (PR https://github.com/dotnet/roslyn/pull/17435)
- [x] Use a single diagnostic for `LanguageVersionExtensionsInternal.GetErrorCode()` (no, better telemetry to keep different error codes)
- [x] Print version diagnostic with `#VERSION` (https://github.com/dotnet/roslyn/issues/17859, PR https://github.com/dotnet/roslyn/pull/17957)
- [x] After any of the 7.1 features are merged to master, the UpgradeProject code fixer should be modified to handle it and tested accordingly.
- [x] VB project settings UI and DTE. (closing for now, as point release for VB will come later)

Relates to https://github.com/dotnet/roslyn/issues/7141

**Comment by VSadov** [comment]
CC: @jcouv

**Comment by AdamSpeight2008** [comment]
Why was using the type `Version` ruled out ?

**Comment by jcouv** [comment]
@AdamSpeight2008 [Which type `Version`](http://source.roslyn.io/#q=version) do you mean?

**Comment by AdamSpeight2008** [comment]
@jcouv [System.Version](https://msdn.microsoft.com/en-us/library/system.version(v=vs.110).aspx)

**Comment by jcouv** [comment]
@AdamSpeight2008 The compiler already uses `LanguageVersion`. It is part of the public API and we cannot change to a different type without breaking backwards compatibility of multiple APIs (regardless of merits of another type, which I did not investigate).

**Comment by OmarTawfik** [comment]
@jcouv does this cover the Project Properties > Advanced tab in VS?

**Comment by jcouv** [comment]
@OmarTawfik Yes, that's covered by the 4th bullet ("Add entries to UI ("7.1" and "latest") and re-label as discussed). I'll talk to you tomorrow about the labels we discussed with Kasey.

**Comment by jcouv** [comment]
All the work items to add support for C# 7.1 have been completed. I'll close the issue.
