### ISSUE TITLE
Umbrella issue to track all known VS SDK issues

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#17456]
- [ ] "ExternalSettingsManager::GetScopePaths failed to initialize PkgDefManager "
https://ci.dot.net/job/dotnet_roslyn/job/dev16/job/windows_release_vs-integration/2

- [ ] System.IO.IOException: The process cannot access the file 'C:\USERS\DOTNET-BOT\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_DD22E32EROSLYNDEV\EXTENSIONS\Microsoft\Roslyn Language Services for Visual Studio 15\42.42.42.42424\extension.vsixmanifest' because it is being used by another process.
https://ci.dot.net/job/dotnet_roslyn/job/dev15.0.x/job/windows_debug_vs-integration_prtest/3/console

- [ ] The "FindInstalledExtension" task failed unexpectedly: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration/373/

- [ ] DeployExtension=true is not forcing MEF composition in all cases: https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=385351&triage=true
Workaround is to run ‘devenv /clearcache’ and ‘devenv /updateconfiguration’ before launching VS

- [ ] Allow uninstall experimental VSIXes through Extensions and Updates dialog: https://devdiv.visualstudio.com/DevDiv/_workitems?id=367158&_a=edit

- [ ] There was a problem checking to see if the profile was setup: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/344/

- [ ] Issue where installing an Experimental extension globally causes problems
  This is partially covered by VSO 36715
@brettfo wrote a tool that LUT is using and Roslyn has a PR to consume: https://github.com/dotnet/roslyn/pull/13690

- [ ] Prevent users from installing Experimental extensions globally
- [ ] Prevent users from specifying both AllUsers and Experimental simultaneously
- [ ] Roslyn no longer doing this bad behavior in the first place

**Comment by tmat** [comment]
@jasonmalinowski @Pilchie @tannergooding @jaredpar @Michael-Eng @AlexEyler @tinaschrepfer

If you are aware of an existing VSO bug tracking an issue listed above that doesn't have a link to VSO, please add the link.
