### ISSUE TITLE
[IOperation] Top TODO List

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#17724]
- [x] https://github.com/dotnet/roslyn/issues/18066 API Review
- [x]  https://github.com/dotnet/roslyn/issues/17889 C# and VB Implementation parity
- [x] https://github.com/dotnet/roslyn/issues/6894 Complete Unit Tests
- [ ] https://github.com/dotnet/roslyn/issues/17913 Syntax and IOperation correspondance

**Comment by CyrusNajmabadi** [comment]
Open questions:

[ ] What 'level' does IOperation operate at?  i.e. an entirely unlowered tree?  An entirely lowered tree?  Something in between?  Right now i think it's the "in between", but i think we need to pick one end or the other.
[ ] Should every statement/expression node have an IOperation equivalent? Some nodes have no corresponding IOperation.  For example, if i have "N1.N2.C1.C2.StaticMethod()" i can't get IOperations on any of "N1.N2.C1.C2".  I can only get an invocation operation, and a method-access operation.  The lack of IOperations for intermediary nodes means IDE can't use this for stuff like simplification.  However, adding these nodes could be costly.
[ ] Can we move to a non-allocation model for IOperation?  In an ideal world we would have an accurate IOperation API and then we'd just literally return the compiler BoundNode.  Allocations in bound-nodes are concerning as walking the bound nodes may end up being prohibitively expensive.
[ ] Today, IOperations are very hit or miss for errors.  The compilers often punt and just generate BadExpression and whatnot.  This leads to very poor experiences as IDE layers need to operate well in broken code scenarios.
[ ] IOperation doesn't have parent pointers.  This is pretty unpleasant as you can't jump into an operation and then look up to see how it is being used.

**Comment by mavasani** [comment]
Regarding this:

> Today, IOperations are very hit or miss for errors. The compilers often punt and just generate BadExpression and whatnot. This leads to very poor experiences as IDE layers need to operate well in broken code scenarios.

I think implementing https://github.com/dotnet/roslyn/issues/17802 might solve this issue as compiler does store the bound expressions within a BoundBadExpression, we just don't seem to expose them from IInvalidExpression/IInvalidStatement

**Comment by CyrusNajmabadi** [comment]
Added a new one: No generalized walk to walk down IOperations (like we can with Syntax).

This is annoying when you want to do something like say "i want to see if there's a coalesce expression somewhere below this IOperation"

**Comment by genlu** [comment]
@CyrusNajmabadi Is this what you wanted?
http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/OperationWalker.cs,101426d3d21b2151,references

**Comment by CyrusNajmabadi** [comment]
@genlu yes. though i don't really want to have to define and instantiate a class just to simply enumerate the children of a type.  I think we should likely put some helper extensions that delegate to this though.

**Comment by CyrusNajmabadi** [comment]
New issue: Why is there no IStatement?  It seems odd that all hte statement operation just derive from IOperation directly.

**Comment by mavasani** [comment]
@CyrusNajmabadi - there is no IExpression either...

**Comment by CyrusNajmabadi** [comment]
That's unfortunate :)

**Comment by CyrusNajmabadi** [comment]
@genlu Do you know why that would be?  It seems generally valuable to have such a split (like we do at the syntax level).

**Comment by mavasani** [comment]
+1, especially given we also have BoundExpression and BoundStatement in compiler layers, which will probably make the implementation of the interfaces clearer in the compiler code as well.

**Comment by genlu** [comment]
Those (`IStatement` and `IExpression`) were removed by John, IIRC one of the reasons was users might not care (or not understand) the (in some cases subtle) difference between a statement and an expression.

**Comment by CyrusNajmabadi** [comment]
Hrmm... i'm not sure i buy that... :)   I mean, we expose both those concepts in the VB and C# syntax models.  And it's actually super helpful for knowing the set of things i might get at any level.  For example, if an 'IIfStatement' just has an 'IOperation' for the condition, that means i could get *anything*.  If that can be filtered down to just the set of IExpressions, that vastly decreases the mental model for what i might get.

**Comment by mavasani** [comment]
Seems like this PR has context: https://github.com/dotnet/roslyn/pull/8624

**Comment by mavasani** [comment]
Specifically https://github.com/dotnet/roslyn/pull/8624#issuecomment-183502247

**Comment by CyrusNajmabadi** [comment]
I'm not certain how i feel about "Concretely, if we preserve an expression/statement distinction, we can't represent F#".  Representing F# is currently a non-goal.  And if it becomes a goal that likely means a ton mroe work.  At that point pretty much any construct might not fit properly for that language (let alone others)...

Let me talk to Matt about if this is part of the scope for this work.

**Comment by genlu** [comment]
It was not about representing F#, it was about raising IL to IOperation. Not sure if that is still a goal though. @nguerrera

**Comment by CyrusNajmabadi** [comment]
Interesting.  That will definitely have to be something we discuss with Matt.  Raising IL would be very nifty.  But if that's the case, we need the right set of people involved from the start to ensure we make the right decisions here.

**Comment by CyrusNajmabadi** [comment]
Need to think about upcoming language features and the expression/statement dichotomy.  For example, we have IThrowStatemnet.  But C#7.0 added throw-expressions.  So perhaps we just want to have IThrowExpression and if it's used in a statement we would have an IExpressionStatement htat points at it.

**Comment by CyrusNajmabadi** [comment]
Another unexpected result/VB-C#-inconsistency.  If you get the IBlockStatement for a VB "sub new" (i.e. constructor).  It will have a "return statement" as the last statement of the IBlockStatement.  This is both weird (since there's no actual return-statement, or anything like it, in a constructor), and it is inconsistent with C# which does not have such a statement in the statement list.

**Comment by bkoelman** [comment]
Is its WasCompilerGenerated property set to True? I have seen similar cases
in C# where a synthesized return statement is returned from operations,
while the source code does not actually contain them. I was told this has
to do with lowering.

Op 19 mrt. 2017 00:41 schreef "CyrusNajmabadi" <notifications@github.com>:

Another unexpected result/VB-C#-inconsistency. If you get the
IBlockStatement for a VB "sub new" (i.e. constructor). It will have a
"return statement" as the last statement of the IBlockStatement. This is
both weird (since there's no actual return-statement, or anything like it,
in a constructor), and it is inconsistent with C# which does not have such
a statement in the statement list.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/roslyn/issues/17724#issuecomment-287583138>, or mute
the thread

**Comment by CyrusNajmabadi** [comment]
@bkoelman Possibly.  Though even if htat were the case, the inconsistency with C# is enough to raise this as an issue.

On monday we're going to be talking with the compiler team about hte future of IOperation.  One thing we'd like is that *by default* (i.e. without any configuration options provided), there should be minimal (or no) lowering going on.  With lowering it becomes very hard to map between the operations and the actual tree you're starting with.

We do think the lowered trees are of great value though.  And we think they should be exposed in teh future, just in a way that puts the client in control.  i.e. we could define actual lowering passes and allow the client to say which lowered pass of the tree they want to get the IOperations for.  That way you could say "i want the tree after the async rewrites" or "i want the tree as pristine as possible".  Of course, hte more lowered you get, the more it would be expected that the bound trees would diverge from the original syntax tree.

**Comment by CyrusNajmabadi** [comment]
Another issue:

IOperations do not expose if they were generated by the compiler or not.  i.e. WasCompilerGenerated is at the BoundNode level but not the source level.  We likely would want to expose this information, esp. if we expose the concept of lowering passes.

**Comment by mavasani** [comment]
Re: WasCompilerGenerated

I think there is an existing issue tracking this work.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn/issues/10214

**Comment by jcouv** [comment]
@jinujoseph Is this issue up-to-date? Seems like some of the linked issues have been closed already.
I was looking for the issue tracking the generation of `Operations.xml.Generated.cs`. Is that still going to happen?

**Comment by mavasani** [comment]
> I was looking for the issue tracking the generation of Operations.xml.Generated.cs. Is that still going to happen?

@333fred is working on it currently.

**Comment by jinujoseph** [comment]
@jcouv  tracking bug for Generator work is tracked [here ](https://github.com/dotnet/roslyn/issues/20204)

**Comment by jinujoseph** [comment]
closing this issue out as pending works are tracked separately.
