### ISSUE TITLE
[IOperation] VB & C# Implementation differences 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#17889]
- [ ] [17861](https://github.com/dotnet/roslyn/issues/17861) SemanticModel.GetOperation uses different GetOperationOptions
- [ ] #17998 Differing variable declaration in For loops between C# and VB
- [ ] #8919 No top-level block access in VB
- [x] #18000 Multiple Variable declaration inconsistency

**Comment by 333fred** [comment]
* [ ] https://github.com/dotnet/roslyn/issues/17998 Differing variable declaration in For loops between C# and VB

**Comment by jinujoseph** [comment]
handled seperately
