### ISSUE TITLE
Enable EnC support for C#7 features

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#17891]
- [x] https://github.com/dotnet/roslyn/issues/17896 ENC support for out Var
- [x] https://github.com/dotnet/roslyn/issues/12435 ENC support for pattern matching
- [x] https://github.com/dotnet/roslyn/issues/17991 ENC support for switch
- [ ] https://github.com/dotnet/roslyn/issues/5156   ENC support for local functions
- [x] https://github.com/dotnet/roslyn/issues/17681 ENC for expression-bodied methods
- [x] https://github.com/dotnet/roslyn/issues/16960 ENC for out variable declarations
- [x] https://github.com/dotnet/roslyn/issues/12438 ENC improvements for C# 7
- [x] https://github.com/dotnet/roslyn/issues/12436 ENC for Tuples

See also https://github.com/dotnet/roslyn/issues/12438 https://github.com/dotnet/roslyn/issues/12379

**Comment by jinujoseph** [comment]
refer #12379 
@tmat @ivanbasov

**Comment by jcouv** [comment]
You may want to update the documentation at https://github.com/dotnet/roslyn/wiki/EnC-Supported-Edits

**Comment by jcouv** [comment]
Nice. Thanks! 🎉
