### ISSUE TITLE
[IOperation] API/Design Review

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#18066]
# V1 

Checked: Review Complete
**Bold** : Active Work
`Grey` : Task Completed 

- [x] https://github.com/dotnet/roslyn/issues/18246: `Refactor & Decide on interface versus abstract type` (Decision on interface/class pending)

- [x] https://github.com/dotnet/roslyn/issues/8813 `IHasArgumentsExpression, IInvocationExpression and IArgument interfaces` , implementation pending https://github.com/dotnet/roslyn/issues/18549

- [x] https://github.com/dotnet/roslyn/issues/18115: `IObjectCreationExpression API shape`

- [x] https://github.com/dotnet/roslyn/issues/17802: `IInvalidExpression and IInvalidStatement should expose child operations`

- [x] https://github.com/dotnet/roslyn/issues/18335 `Should the initializers of an `As New` multiple declaration be the same object`

- [x] https://github.com/dotnet/roslyn/issues/8851 `BoundLambda - value returned by IOperation.Type`
- [x] https://github.com/dotnet/roslyn/issues/18300 `IOperation API for string interpolation`

- [x] https://github.com/dotnet/roslyn/issues/17838: Discuss IOperation API for queries
- [x] https://github.com/dotnet/roslyn/issues/18155: IArrayCreationExpression.Dimensions for explicit versus implicit case
- [x] https://github.com/dotnet/roslyn/issues/18057 IUnboundLambdaExpression should not be part of APIs
- [x] https://github.com/dotnet/roslyn/issues/18056 IIncrementExpression
- [x] https://github.com/dotnet/roslyn/issues/18055 IConversionExpression must expose IsChecked boolean
- [x] https://github.com/dotnet/roslyn/issues/18135 true/false unary operation
- [x] https://github.com/dotnet/roslyn/issues/18089, https://github.com/dotnet/roslyn/issues/8885 Semantics of IOperation.IsInvalid
- [x] https://github.com/dotnet/roslyn/issues/18064 GetOperation returns a superset of IOperations
- [x] https://github.com/dotnet/roslyn/issues/18601 Parent Pointer
- [x] https://github.com/dotnet/roslyn/issues/9331 **Remove ConditionalWeakTable from the compilers**

- [x] https://github.com/dotnet/roslyn/issues/18781 https://github.com/dotnet/roslyn/issues/8883  IOperation API shape for collection initializer expressions

- [x] https://github.com/dotnet/roslyn/issues/10856: IOperation support for tuple literals

- [x] https://github.com/dotnet/roslyn/issues/19925: IOperation API for BoundUserDefinedConditionalLogicalOperator
- [x] https://github.com/dotnet/roslyn/issues/19926: IOperation API for anonymous object creation expressions
- [x] https://github.com/dotnet/roslyn/issues/19954: IOperation API for nameof expression

- [x] https://github.com/dotnet/roslyn/issues/19300: OperationKind.FieldInitializerInCreation and OperationKind.PropertyInitializerInCreation are redundant 

- [x] https://github.com/dotnet/roslyn/issues/18839 https://github.com/dotnet/roslyn/issues/8897: _IOperation API shape for DelegateCreationExpression_ 

- [x] https://github.com/dotnet/roslyn/issues/8905, https://github.com/dotnet/roslyn/issues/18548  _Bound...Placeholder nodes_

- [ ] IExpression and IStatement (and IExpressionStatement and IStatementExpression).
 
- [ ] https://github.com/dotnet/roslyn/issues/18289 https://github.com/dotnet/roslyn/issues/8825 https://github.com/dotnet/roslyn/issues/8825 Operand of the IUnaryOperatorExpression

- [ ] https://github.com/dotnet/roslyn/issues/8917 https://github.com/dotnet/roslyn/issues/8916 https://github.com/dotnet/roslyn/issues/8915 https://github.com/dotnet/roslyn/issues/8914 https://github.com/dotnet/roslyn/issues/8913 _VB missing interface_

- [ ] https://github.com/dotnet/roslyn/issues/8861 _receiver for IConditionalAccessExpression_

- [x] https://github.com/dotnet/roslyn/issues/8852 Primary expression of INullCoalescingExpression

- [x] https://github.com/dotnet/roslyn/issues/18915 Analyzers & Fields
- [x] https://github.com/dotnet/roslyn/issues/18000 Multiple Variable Declaration
- [x] https://github.com/dotnet/roslyn/issues/17998 Block Loops vb vs c#
- [x] https://github.com/dotnet/roslyn/issues/11859 BoundCall - constructor
- [x] https://github.com/dotnet/roslyn/issues/7960 argument operation doesn't handle caller info attributes
- [x] https://github.com/dotnet/roslyn/issues/19949: IOperation support for arglist operator
- [ ] https://github.com/dotnet/roslyn/issues/19960: IOperation API for BoundPointerElementAccesss 
- [ ] https://github.com/dotnet/roslyn/issues/19965: IOperation - IOperation API for MemberGroups

- [x] https://github.com/dotnet/roslyn/issues/19924: IOperation API for BoundDeconstructionAssignmentOperator

- [x] https://github.com/dotnet/roslyn/issues/19927: IOperation support for patterns 

- [x] https://github.com/dotnet/roslyn/issues/20095 IMethodBindingExpression missing IConversionExpressions

- [x] https://github.com/dotnet/roslyn/issues/20046 IConversion support for InterpolatedString->IFormattable

- [x] https://github.com/dotnet/roslyn/issues/19902 Operation tree contains no nodes for local functions

- [ ] https://github.com/dotnet/roslyn/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Feature+-+IOperation%22+label%3ADiscussion

# V2 
- [x] https://github.com/dotnet/roslyn/issues/18198: IOperation API for attributes 
- [x] https://github.com/dotnet/roslyn/issues/18351 Hidden sub nodes of valid syntax
- [ ] https://github.com/dotnet/roslyn/issues/8394 __arglist, __makeref, __refvalue, __reftype
- [ ] https://github.com/dotnet/roslyn/issues/8640 IOperation representational issues when raising IL

**Comment by jinujoseph** [comment]
@dotnet/analyzer-ioperation , pls add all API related

**Comment by jinujoseph** [comment]
we have individual items tracking
