### ISSUE TITLE
EnC Manager Replacement for managed code

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn#18350]
Bugs 
- [x] [96078](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/96078): Locking DLLs in shared projects
- [x] [16657](https://github.com/dotnet/roslyn/issues/16657): <s>Redesign EnC Manager to support Lightweight Solution Load</s>
- [ ] [18413](https://github.com/dotnet/roslyn/issues/18413): EncManager: Handle active statements without sequence points
- [x] [407603](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/407603): Add DkmClrModuleInstance.GetBaselineManagedMetaDataPtr API
- [x] [402207](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=402207):  Edit and continue does not work in WPF project on *.xaml.cs - file is read only
- [x] [407766](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/407766): Make DkmENCActiveStatement API public and clean it up
- [ ] [18618](https://github.com/dotnet/roslyn/issues/18618): EnC: Detect and handle changes of #line and conditional compilation directives -- the new API for active statements should give us info about an active statement in ```F()```
- [x] https://github.com/dotnet/roslyn/issues/21170: EnC doesn't work for multi-targeted projects
- [x] [DevDiv 489743](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/489743): Changes are not allowed while code is running in new .NET Core MVC application after changed platform to 'x86 /x64'
- [x] [530575](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/530575): Remove active statement cache from EncMgr 
- [ ] https://github.com/dotnet/roslyn/issues/23865: Changing active exception region span in any way should be rude edit
- [x] https://github.com/dotnet/roslyn/issues/13276 Defer active statements enumeration
- [x] [DevDiv 246053]( https://devdiv.visualstudio.com/DevDiv/_workitems/edit/246053): Debugger sometimes spends a long time in vsdebug!sdm::CDebugEncModule::GetActiveStatementCount during stepping
- [ ] https://github.com/dotnet/roslyn/issues/24320: active statements handling in linked documents
- [x] [DevDiv 551604](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/551604): UIDelay: microsoft.visualstudio.languageservices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.StartDebuggingPE
- [ ] https://github.com/dotnet/roslyn/issues/1204: Force loading of workspace projects before beginning EnC session
- [x] https://github.com/dotnet/roslyn/issues/27735: Avoid making editor buffers read-only during debugging
- [x] https://github.com/dotnet/roslyn/issues/29223: Replacement for managed EnC module updates
- [x] [DevDiv 750649](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/750649): ENC failure to apply change.
- [x] [DevDiv 804116](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/804116): Feature request: Add DkmModuleInstance.IsEncSupported Concord API 
- [x] [DevDiv 804323](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/804323): Feature request: Add IDebugStateChangeListener MEF interface
- [x] https://github.com/dotnet/roslyn/issues/34187: EnC test scenario: Multi-process updates
- [x] https://github.com/dotnet/roslyn/issues/34253: EnC test scenario: Multiple module instance loads
- [x] [DevDiv 849764](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849764): EnC support for unwinding exceptions in the new EnC manager design

Roslyn work:
- [ ] Remove implementation of IVsENCRebuildableProject* from CPS project
- [ ] Remove implementation of IVsENCRebuildableProject* from legacy project
- [x] Review where IVsENCRebuildableProject is used in EncMgr, to make sure we don't fall back to native EnC for managed projects
- [x] Hook IVsDebuggerEvents.OnModeChange event and drive EnC session. Need to know break reason, which is currently not passed.
- [x] Query debugger for active statements (async). LS needs active statements grouped by document, project is irrelevant. The EncMgr currently caches AS by MVID.

### GetPEIdentity

- [x] Roslyn maintains {MVID <-> Project} map. MVID read from output binary metadata (same as today). 

- [x] Notify debugger that EnC started when a file is edited. Module associated with the edited project needs to be initialized (SymReader created). The debugger responds with error code if EnC is not supported for the module. Roslyn reports the error.

- [x] Handle multiple outputs (multi-targeting) when mapping projects to MVIDs

- [x] Need to initialize SymReader for update (InitializeEnc)
Currently the debugger does that when a change is detected in a source file.
Instead: 
    - Hook editor filter
    - Edit -> EditAndContinueService?.OnDocumentEdited() 
    - Determine which project the edited file belongs to
    - Get MVIDs for that project, find modules
    - Dictionary<ProjectId, AsyncLazy<Guid>> ProjectToMvidMap on DebuggingSession
    - DkmXxx.GetModule(Guid).GetSymbolReader -> InitializeForEnc
    - Update CEncMgr::EnterBreakState:
```C++
// Perf: provide the SourceChange manager with a way to get at the enc modules
// to allow for intialization on first edit
m_pSourceChangeMgr->SetManagedEnc(m_pManagedEnc);
```
- [x] Error reporting when EnC not available for given project
    - Need API to determine that we are in StopOne mode (m_DebugModelIsStopOne)
    - Check if any module for the project is loaded.

- [x] GetPEIdentity 
    - Use ProjectToMvidMap and block (it’s ok to block for apply)

- [x] Cleanup HandleActiveStatementsAndExceptionRegions
    - No need to call pencsession->GetENCModule
    - Need to handle case when module is not loaded: need to determine ProjectReadOnlyReason
    - Make EditAndContinueSession.IsProjectReadOnly async and lazily detect whether a module for the project has been loaded.
    - Allow user to edit file but tag changes that were not applied since the module hasn’t been loaded.

### Debugger work

> Known issue: If one module is loaded multiple times an EnC update to the module should be applied to all its instances. This might not work today. Not clear what CLR does exactly.

- [x] Getting baseline metadata from DkmClrModuleInstance [407603](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/407603)

Currently ```DkmClrModuleInstance.GetMetadataBytesPtr``` returns a pointer to the latest metadata snapshot. We need to get the metadata of the original version of the module. 

```C#
class DkmClrModuleInstance
{
  ...
  IntPtr GetBaselineMetaDataBytesPtr(out int size);
  ...
}
```

Adding this API would allow us to avoid locking PE files in obj directory (VSO bug [96078](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/96078))

- [x] Expose active statements provider Concord API [407766](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/407766)

```C#
class DkmClrRuntimeInstance
{
  // TODO: can it be made cancellable (CancallationToken cancellationToken)?
  DkmActiveStatement[] GetCurrentActiveStatements();
}

struct DkmActiveStatement // currently called DkmENCActiveStatement
{
   ... current members of the DkmENCActiveStatement ...
}

enum DkmActiveStatementFlags // Currently called DkmENCActiveStatementFlags
{
    None
    LeafFrame
    PartiallyExecuted
    NonUserCode
}
```

- [x] Is ```IVsDebuggerEvents.OnModeChange``` event isn't fired every time EnterBreakMode/ExitBreakMode on EncMgr is.

For example, ```CDebugger::SetNextStatement``` calls:

```C++
pENC2->ExitBreakState();
hr = GetCodeContextOfPosition(pTextPos, &pCodeContext, &pProgram, true, true);
pENC2->EnterBreakState(m_pSession, GetEncBreakReason());
```

The event seems to be not fired. We might need to add another event.

- [x] Expose Break Reason

Introduce a new OnModeChange event the BreakReason should be communicated thru that event. 

```C#
interface IDkmClrDebuggerService
{
   ...
   event Action<DkmModeChangeEventArgs> OnModeChange;
   ...
}

class DkmModeChangeEventArgs : EventArgs
{
   DkmBreakReason BreakReason;
   DkmDebugState PreviousState;
   DkmDebugState NewState;
}
```

- [x] Applying code changes

See https://github.com/dotnet/roslyn/issues/29223

- [x] Currently the EncMgr implements per-module caches of AS and ER spans. I think these can be removed. The language service gives the debugger exact spans after every edit in ```ManagedCodeChange```.

- [x] EncMgr also calculates line deltas from file updates (see ```CENCModule::GetLineDeltasFromFileUpdates```). This should be avoided. The language service should calculate exactly what's needed to be passed to SymEncUpdate.

**Comment by gregg-miskelly** [comment]
Here are a few more interfaces we will need from a quick review of the EnC APIs --

1. Quickly determine if there are changes to be applied (should ApplyCodeChanges be enabled, and should we actually try to set breakpoints).
2. Mapping from original file/line/column to current positions when there are changes that haven't been applied yet. For example, when we change the current stack frame, so the UI gets the original position from the engine (`IDebugENC2.CurrentPositionFromOriginal`).
3. Determining if there are changes to a method. Looks like this is used to disable going to disassembly, though I am not sure my understanding of this code is correct (`IDebugENC2.AreCodeContextValid`). There is also a similar problem for disabling set next statement inside of exception regions (`IDebugENC2.IsLeafRemapPossible`).

**Comment by tmat** [comment]
@gregg-miskelly 

> 1. Quickly determine if there are changes to be applied (should ApplyCodeChanges be enabled, and should we actually try to set breakpoints).

Added 

```C#
interface IManagedCodeChangeProvider
{
    ...
    // Returns the kind of change made to the modules owned by the provider. The change is aggregated across all modules owned by the provider: if one module has a rude edit and another one has valid change the resulting kind is ManagedCodeChangeStatus.Invalid
    Task<ManagedCodeChangeStatus> GetStatusAsync(CancallationToken cancellationToken);
    ...
}

enum ManagedCodeChangeStatus
{  
   None, // No change made.
   Valid, // All changes are valid, can be applied.
   Invalid, // Some changes are invalid, can't continue.
}
```

above. 

Re 2. and 3. need to investigate.

4. What are the circumstances under which the baseline metadata become invalid? Can it happen during a debugging session?

**Comment by gregg-miskelly** [comment]
4: Depends on how exactly we implement fetching the metadata (ex: making a copy of it vs. just giving out the ICorDebug copy of it). But, at least assuming we are handing out the ICorDebug copy, it would become invalid when that module is unloaded. In the case that the module is still loaded somewhere else, the metadata would still be obtainable, but the language service would need to ask for a new byte ptr since the original one would be gone. In the case that the module is unloaded from all processes, I would guess we wouldn't keep it anymore.

**Comment by tmat** [comment]
It would be good to avoid copies as much as possible. We wouldn't need this API if we didn't care about making a copy -- we could just read it from the file on disk and close the file.

We use the metadata only when we are calculating the IL/metadata delta. I assume the module won't be unloaded during that time (the debugger is in break state). Instead of the debugger notifying us about metadata that were unloaded it would be simpler if we called the method each time we need the metadata. On our side we could then cache symbols built from the metadata based on whether we get the same answer (pointer, size) as we did last time. If we don't we throw the symbols away and rebuild them from the new metadata.

**Comment by gregg-miskelly** [comment]
@tmat sounds reasonable, but I still feel like there should be _something_ that we can use to have in the documentation that we can say 'here is how you can safely use this API'. If that is an event, or if we just have lock/unlock methods for getting the pointers I don't care. But I think there should probably be something.

**Comment by tmat** [comment]
Closing. The issues above are mostly resolved, only minor issues remain and those can be tracked separately.
