### ISSUE TITLE
Checklist for completion of private protected feature

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#18507]
See also https://github.com/dotnet/csharplang/issues/37

- [x] Developer needs to do an IDE test pass to ensure basic functionality is maintained. See [IDE Test Plan](https://github.com/dotnet/roslyn/blob/master/docs/contributing/IDE%20Test%20Plan.md)
- [x] Reviewer needs to create a flavor of the test plan for the feature involved.  In many cases this will just be stripping out unnecessary elements (example expression classification prob not of interest to ref asemblies).  But it should also call out areas of interest particular to this feature. See [Compiler Test Plan](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Compiler%20Test%20Plan.md). *Test plan is at https://github.com/dotnet/roslyn/issues/19722*
- [x] Reviewer needs to validate the test coverage is sufficient for the test plan and note the test gaps
- [x] Add a test that `private protected` members are excluded in reference assemblies. See https://github.com/dotnet/roslyn/pull/18339 for context.

We'll expand these sub-bullets as work progresses.
