### ISSUE TITLE
Reenable analzyers that uses IOperation API

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn#18689]
We have to disable a few IOpeartion based analyzers from PR #18494 onward because it has changed IOperation interface. Will need to enable them as soon as the following prerequisite are met:

 - [x] https://github.com/dotnet/roslyn/issues/18549 Fix the implementation of IHasArgumentsExpression.
 - [x] https://github.com/dotnet/roslyn/issues/19022 update analyzers to use the new API, verify their behavior is correct, and release them.
 - [ ] #19806 update roslyn to reference updated analyzer.

Disabled analyzers:
- RS0012
- RS0014
- CA1825

**Comment by genlu** [comment]
FYI @dotnet/analyzer-ioperation

**Comment by mavasani** [comment]
Can you add the disabled rule IDs here?

**Comment by jinujoseph** [comment]
In Review [here ](https://github.com/dotnet/roslyn/pull/20446)
