### ISSUE TITLE
Author and harness performance tests

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#18911]
**IDE**
- [x] #15673: Typing

- [ ] #15674: Find All References

- [ ] #15675: NavigateTo

- [ ] #15678: Inline Rename

- [ ] #15701: Format Document

- [ ] #15676: Go To Definition

- [ ] #15702: Load Solution

**.NetCore**
- [ ] #15679: .NETCore end-to-end

**Analyzers**
- [ ] https://github.com/dotnet/roslyn/issues/15682: Full solution diagnostics with only 3rd party analyzers (IDE analyzers suppressed)

- [ ] https://github.com/dotnet/roslyn/issues/15681: Full solution diagnostics with only IDE analyzers

- [ ] https://github.com/dotnet/roslyn/issues/15681: Solution build with 3rd party analyzers

**LUT**
- [ ] https://github.com/dotnet/roslyn/issues/18909: Write and harness Live Unit Testing PURIT with a .NetCore solution 

- [ ] https://github.com/dotnet/roslyn/issues/18910: Live Unit Testing perf test(s) to run on Jenkins

**Comment by CyrusNajmabadi** [comment]
Not planning on doing this.
