### ISSUE TITLE
[Work Items] Drive remaining ref assembly issues for mainstream release

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#20418]
- [ ] document and announce the feature
- [ ] project-to-project references (https://github.com/dotnet/project-system/issues/2478, not blocking)
- [ ] Can we improve the build log in Output window to show when compilation was skipped? (https://github.com/dotnet/roslyn/issues/22326, not blocking)
- [ ] Should we consider support in legacy project system after all?
- [x] LUT (https://github.com/dotnet/testimpact/issues/1950, broken, PR https://github.com/dotnet/testimpact/pull/2589)
- [x] lightweight solution load
- [x] dogfood in Roslyn repo
     - [x] Problem with excessive rebuilding https://github.com/dotnet/project-system/issues/2743 (not ref assembly-specific)
     - [x] Problem with excessive rebuilding https://github.com/dotnet/roslyn/pull/21928 (extension was updating target files)
- [x] project-to-project patch for 15.3 (https://github.com/dotnet/roslyn/issues/20412)
- [x] an issue with MSBuildWorkspace (https://github.com/dotnet/roslyn/pull/25376)
- [ ] Should we reconsider legacy project support?
- [ ] Should ref assemblies include xml documentation? (https://github.com/dotnet/roslyn/issues/32215)

Test plan notes for ref assemblies: https://github.com/dotnet/roslyn/issues/18612

**Comment by jcouv** [comment]
All remaining possible work items are tracked as individual issues. We don't need this umbrella anymore.
