### ISSUE TITLE
[Work items] Nullable reference types

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#22152]
**Preview 2:**
- [ ] Intellisense (@333fred)
  - [ ] Public API
  - [ ] Display inferred nullability of variables, fields, properties, type arguments
  - [ ] _Should we display some hint about oblivious vs. non-null?_
- [x] Nullable Specification (Mads)
- [ ] `#nullable`
  - [x] binding (no more scoped context) https://github.com/dotnet/roslyn/pull/31607
  - [x] `#pragma warning nullable (enable|disable|restore)` PR https://github.com/dotnet/roslyn/pull/31806
  - [ ] Code fixer
- [ ] Tuples https://github.com/dotnet/roslyn/issues/29970
- [ ] More attributes e.g.: `[MaybeNull]`
  - [ ] Finalize BCL types
- [ ] `!` suppress conversion warnings https://github.com/dotnet/roslyn/issues/30376
- [ ] `e switch { … }`, `switch (e) { … }` https://github.com/dotnet/roslyn/issues/23944 
- [x] Avoid inferring unspeakable type arguments (PR https://github.com/dotnet/roslyn/pull/31813)
- [ ] Dogfood
  - [ ] WPFRunner
  - [ ] CodeAnalysis
- [x] Nullable value types https://github.com/dotnet/roslyn/issues/29817, PR https://github.com/dotnet/roslyn/pull/31499
- [x] `[Nullable]` metadata encoding (PR https://github.com/dotnet/roslyn/pull/31212)
    - [ ] Sync with F# on format
- [x] Analyze `yield return` https://github.com/dotnet/roslyn/issues/23701

**Non-blocking:**
- [ ] Annotations https://github.com/dotnet/roslyn/issues/29821
  - [ ] File format, MSBuild and loading logic
  - [ ] Some IDE support
- [ ] Intellisense
  - [ ] Display member annotations https://github.com/dotnet/roslyn/issues/26830
  - [ ] Display member annotations from metadata even when feature disabled
- [ ] Codegen for null-check on `parameter!`
- [ ] Lambdas: track nullability of captured variables https://github.com/dotnet/roslyn/issues/29617
- [ ] Local functions: track nullability of captured variables https://github.com/dotnet/roslyn/issues/27233
- [ ] Other annotations
  - [ ] Other attributes (`NullEquals`, `NullInNullOut`, `NotNulled`) https://github.com/dotnet/roslyn/issues/26761
- [ ] `[Nullable]`
  - [ ] Include `NullableAttribute` in framework? See https://github.com/dotnet/roslyn/pull/22820#discussion_r146623094
- [ ] Add attribute types to Core 3
- [ ] Port attribute types to mono
- [ ] Coordinate integration with Razor
- [ ] NullableAttribute: Store flags into a field https://github.com/dotnet/roslyn/issues/30143
- [ ] Codefixer to add `#nullable enable` and `NullableReferenceTypes` https://github.com/dotnet/roslyn/issues/30099
    - [ ] project system property or API https://github.com/dotnet/project-system/issues/4058
- [ ] Other annotations
  - [ ] Nullable property with non-nullable setter https://github.com/dotnet/roslyn/issues/26621
- [ ] `TypeSymbolWithAnnotations`
  - [x] Revert properties (`MethodSymbol.ReturnType`, etc.) to `TypeSymbol` and add `TypeSymbolWithAnnotations` properties
  - [ ] Review use of `TypeMap.AsTypeSymbol` and `TypeMap.AsTypeSymbolWithAnnotations` for cases where nullability is dropped (@jcouv)
- [ ] `SymbolDisplay`
  - [x] Include `?`
  - [ ] Include `!` and `~` https://github.com/dotnet/roslyn/issues/28242
- [ ] Conversions
  - [x] Allow variance of out parameter: `void M(out string x)` invoked with `M(out string? x);`
  - [x] Infer nullability in `out var` https://github.com/dotnet/roslyn/issues/25347
  - [x] Infer nullability in deconstruction https://github.com/dotnet/roslyn/issues/29618
  - [ ] _Which conversions remain?_
- [ ] Flow analysis
  - [x] De-reference should update null state https://github.com/dotnet/roslyn/issues/26749
  - [x] case patterns (`case null:`, `case string:`, `case string s:`) https://github.com/dotnet/roslyn/issues/23944
  - [ ] `x` in `var x = obliviousListOfString;` should be `List<string!>!`
  - [x] Anonymous types https://github.com/dotnet/roslyn/issues/24018
  - [ ] Query clauses and range variables https://github.com/dotnet/roslyn/issues/29863
  - [x] `foreach (var x in maybeNull) { }` https://github.com/dotnet/roslyn/issues/23493
  - [x] No warnings in unreachable code https://github.com/dotnet/roslyn/issues/28798
- [ ] Fields and properties
  - [ ] Report uninitialized warnings for static fields and properties https://github.com/dotnet/roslyn/issues/27014
  - [x] Track nullability of fields and properties
  - [ ] Report warning for `null` initializer https://github.com/dotnet/roslyn/issues/26628
  - [ ] Report warning before assignment https://github.com/dotnet/roslyn/issues/27016
  - [ ] No warnings for constructor that throws exception https://github.com/dotnet/roslyn/issues/25529
- [ ] Use `VisitType` to implement `ContainsNullableReferenceTypes`. See `TestDeepTypeAccessibilityBug18018` test.
- [ ] `!` operator
  - [x] ~~Warning for unnecessary `!`? https://github.com/dotnet/roslyn/issues/25372~~
  - [x] ~~Error for `!!`. See `StaticNullChecking.SuppressNullableWarning_Multiple` https://github.com/dotnet/roslyn/issues/29902~~
  - [ ] Error for `a! = b;`. See `StaticNullChecking.SuppressNullableWarning_Assignment` and https://github.com/dotnet/roslyn/issues/28377
  - [ ] `ERR_NotNullableOperatorNotReferenceType` should be a warning not an error
- [x] Method type inference
  - [ ] `MergeDynamic` and `MergeTupleNames` ignore nullability
  - [ ] `InferExtensionMethodTypeArguments` ignores nullability
  - [ ] `MethodGroupReturnTypeInference` ignores nullability
- [ ] Flow analysis
  - [ ] Intersection with other C# 8.0 features (switch expression, null-coalescing assignment, ...)
    - [x] `??=`
    - [x] recursive patterns
- [ ] Dogfood
  - [ ] Update public API of Microsoft.CodeAnalysis.dll and Microsoft.CSharp.CodeAnalysis.dll
  - [ ] Update tool for tracking public APIs
- [ ] EE
  - [ ] Include `?` annotations in Type for Locals and Watch

**Productivity** Migrated to project https://github.com/dotnet/roslyn/projects/43
  - [ ] QuickInfo
  - [ ] Authoring experience for external annotations
  - [ ] Can we make it easier to see what context we're in?
  - [x] `null` assignment suggests declaring as nullable https://github.com/dotnet/roslyn/pull/26630
  - [ ] `null` test suggests declaring as nullable https://github.com/dotnet/roslyn/pull/26661
  - [ ] Fix interface implementation or override https://github.com/dotnet/roslyn/issues/26833
  - [ ] Grey out unnecessary `!` https://github.com/dotnet/roslyn/issues/26736
  - [ ] Grey out unnecessary `?`
  - [ ] Using `?` or `!` suggests turning feature on  (issue https://github.com/dotnet/roslyn/issues/30099)
    - [ ] locally https://github.com/dotnet/roslyn/pull/30098
    - [ ] globally
  - [ ] help move `#nullable` up/down the scopes
  - [x] classify `#nullable` (PR https://github.com/dotnet/roslyn/pull/31579)
  - [x] Indent `#nullable` to the margin
  - [x] Marshalling options in OOP process (PR https://github.com/dotnet/roslyn/pull/32726)

- [ ] Performance
  - [ ] Measure performance compiling Roslyn
- [ ] IDE: Metadata view

**Work related to project-system:**
- [ ] project-system API for CPS https://github.com/dotnet/project-system/pull/4277
- [ ] project-system API for csproj/legacy
- [ ] add drop-down in UI
- [ ] SDK work to set default value
- [ ] Code fixer to set `NullableReferenceTypes` project property (setting `Project.Configuration.Properties["NullableReferenceTypes"]` and declaring that "NullableReferenceTypes" [BooleanProperty](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml#L63))

**Preview 1:**
- [x] Fix installer https://github.com/dotnet/roslyn/issues/29987
- [x] Merge back to a preview branch
   - [x] Remove/replace PROTOTYPE markers
   - [x] IDE test pass
- [x] `[NonNullTypes]`
  - [ ] ~~Disable warnings with `[NonNullTypes(Warnings=false)]` https://github.com/dotnet/roslyn/issues/29616~~ (no longer applicable)
  - [ ] ~~Fix/verify `[NonNullTypes]` in PE symbols~~ (no longer applicable)
  - [x] Injecting NonNullTypesAttribute https://github.com/dotnet/roslyn/pull/29180
  - [x] Use explicit NonNullTypes context in every TSWA https://github.com/dotnet/roslyn/issues/28766
  - [x] Warning for `!` if no attribute (needs a new solution)
  - [x] Enable warnings with `[NonNullTypes]`
  - [x] Warning for `?` if no attribute or if `[NonNullTypes(false)]`
  - [x] Remove syntax-based cycle breaking (modules, types, members)
  - [x] Enable feature with `[NonNullTypes]` or `[NonNullTypes(value)]` (
https://github.com/dotnet/roslyn/pull/28491)
- [x] Method type inference
  - [x] Incorrect nullability arguments include `~` https://github.com/dotnet/roslyn/issues/27961
- [x] Flow analysis
  - [x] `(object)x != null` https://github.com/dotnet/roslyn/issues/27928
  - [x] L-values https://github.com/dotnet/roslyn/issues/27522
  - [x] `t.ToString();` for unconstrained `T`
  - [x] tuples https://github.com/dotnet/roslyn/issues/28951
  - [x] `?.` https://github.com/dotnet/roslyn/issues/25870
  - [x] `s is string` https://github.com/dotnet/roslyn/issues/26745
  - [x] `is` patterns
    - [x] `x is C y`
    - [x] `x is K` where `K` is a constant other than `null`
- [ ] Type parameters
  - [ ] Substitution with `~` and `?` or `!` (oblivious doesn't survive, LDM 7-11)
  - [x] Support `object` constraint; use `object?` for unconstrained https://github.com/dotnet/roslyn/pull/29809
  - [x] Check constraints https://github.com/dotnet/roslyn/issues/27742
  - [x] Error for `T?` unless `T` is constrained to a reference type or a value type https://github.com/dotnet/roslyn/pull/28804
  - [x] Support `class?` constraint
- [x] Switch old tests to C# 8 (update default test options)
- [x] Track nullability of unconstrained type parameters https://github.com/dotnet/roslyn/issues/28956
- [x] Performance
  - [x] Close allocation gap with null unaware C# 
- [x] Merge 15.8 branch
- [x] Compiler command-line switch https://github.com/dotnet/roslyn/pull/30479 and MSBuild setting

**Comment by jcouv** [comment]
Some various notes from LDM discussions and others:
- [ ] `string.IsNullOrEmpty` should inform flow analysis
- [ ] `TryGetValue` should inform flow analysis
- [ ] Update templates (so new projects have the feature turned on by default)
- [ ] What should IDE show at various points in the method? Does having the feature on or off affect what is shown?
- [ ] Could users annotate some methods to reset flow analysis? (for example, `p.ChangeMiddleNameToNull()`)
- [ ] `string? x = null; x = nonNull; var y = new [] { x };` What is the type of `y`?
- [ ] `string? x = null; x = nonNull; var y = MakeArray(x, 10);` What is the type of `y`?

**Comment by Joe4evr** [comment]
> `string.IsNullOrEmpty` should inform flow analysis

Nit: Should probably add `.IsNullOrWhitespace` while you're at it.

**Comment by jcouv** [comment]
Notation for null-state: `?` means top-level may be `null`, `!` means top-level isn't `null`, and `_` means oblivious.

### Local declaration
Ex: `type local = expr`
Null-state of `local` is passed through from `expr`.
Produces a `W` warning if top-level nullability of `expr` is `?` but type is `!`.

### Assignment
Ex: `local = expr`
Ex: `parameter = expr`
Null-state of `local` or `parameter` is passed through from `expr`
Produce a real warning if top-level nullability of `expr` is `?` and `parameter` is an `out` or `ref`.
Otherwise, produce a `W` warning if top-level nullability of `expr` is `?` but type is `!`. 

### Null-coalescing operator
Ex: `expr1 ?? expr2`
Outputs: null-state of `expr2`
Open issue: should this warn if `expr1` is declared with type non-nullable?

### Cast
Ex: `(type)expr`
Produce a `W` warning if top-level nullability of `expr` is `?` but `type` is `!`. 
Null-state is passed through from `expr`.

### Array creation
Ex: `new[] { expr1, expr2 }`
Null-state is a non-null array whose elements' nullability is the most relaxed from the expressions, with order: `?` > `_` > `!`.

**Comment by jcouv** [comment]
I looked at the remaining issues. Extracted one or two as discrete issues.
I think we can now close this umbrella issue because we now use the [Nullable Board](https://github.com/dotnet/roslyn/projects/44).
