### ISSUE TITLE
[Umbrella] Refresh IL verification

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#22872]
Recent versions of the C# compiler produce unverifiable code (by current spec). All new compiler tests that hit this just disable the verification step, but we'd like to reverse the trend.
Below is a rough plan how we can be back to verifying the compiler output.

- [ ] Switch to ILVerify in compiler test suite (try, file bugs, perf?)
- [ ] Add support for ref return
    - [ ] Propose informal spec on [dotnet/designs](https://github.com/dotnet/designs/issues), review (Xamarin, Jan/Michal, compiler)
    - [ ] Update compiler (separate slots by returnability and tag slots per proposal)
    - [ ] Update ILVerify
    - [ ] Formalize spec
- [ ] Add support for readonliness (after ref return is done)
- [ ] Add support for Span (after ref return is done)

Tagging @VSadov @gafter and folks who have been contributing to ILVerify (with our thanks): @ArztSamuel @gregkalapos @mmayr-at

**Comment by jcouv** [comment]
Tagging @discostu105 too, as FYI

**Comment by jcouv** [comment]
@VSadov posted a proposal for informal spec for ref return: https://github.com/dotnet/designs/pull/17

**Comment by jcouv** [comment]
@VSadov Note that ILVerify is currently only built for target framework `netcoreapp2.0`, but the compiler emit tests aren't yet built or run for this target. We'll either have to change ILVerify to also target `net46`, or we'll have to find a way for emit tests to target `netcoreapp2.0`...

**Comment by ArztSamuel** [comment]
ILVerify is now also targeting `net46`, since https://github.com/dotnet/corert/pull/4862.

**Comment by VSadov** [comment]
FYI: updated with the reference to another draft. Now for the "readonly references" rules.

https://github.com/dotnet/designs/pull/21

**Comment by jcouv** [comment]
I went through the C# emit tests and [classified](https://github.com/dotnet/roslyn/pull/23210/files#diff-21f74235fa50cbcb57190284b2578455) the observable differences in behavior between ILVerify and PEVerify. Also updated the OP notes.

I need to investigate some of them to confirm whether they are a Roslyn problem or an ILVerify problem (for instance, I suspect the one labelled "Mscorlib" may be a Roslyn issue). Also some issues are not high-priority (the one labelled "NoPIA").

The ones I'm pretty sure about: ILVerify doesn't support net modules (only supports assemblies), and it doesn't support TypedReference. I'll file bugs and then we can discuss which issues are more important.

**Comment by VSadov** [comment]
I have tried to order remaining unimplemented error IDs from https://github.com/dotnet/corert/blob/master/src/ILVerify/src/VerifierError.cs

I do not have a lot of insight if some are easier to implement than others within existing infrastructure. I just looked at possibility to see particular violations as a result of some compiler bug. 
In that sense some errors could be more "useful" than others.

I have listed "interesting" errors here: https://github.com/dotnet/corert/issues/4958
