### ISSUE TITLE
[Umbrella] Work items and test plan for async streams

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#24037]
Proposal: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/async-streams.md

## FAQ and known issues
- "missing ManualResetValueTaskSourceLogic": 
The preview1 compiler is looking for that type, but .NET Core 3 preview 1 contains `ManualResetValueTaskSourceCore`. The solution is to include this [code snippet](https://github.com/dotnet/coreclr/issues/21379#issuecomment-444473061) in your program. This will be fixed in preview2.
- enumerator disposed too early (`yield return` in construct with `finally`) (see issue https://github.com/dotnet/roslyn/issues/31268)
- `NullableReferenceTypes` project property doesn't take full effect in legacy projects yet (https://github.com/dotnet/project-system/issues/4058) 

----

## Async-iterator methods
- [x] EnC
  - [x] ~~block~~
  - [x] enable (issue https://github.com/dotnet/roslyn/issues/32266, issue https://github.com/dotnet/roslyn/issues/32589 for `await using` declarations)
- [x] making cancellation token available to producers (PRs https://github.com/dotnet/roslyn/pull/35121 and https://github.com/dotnet/roslyn/pull/35326, API proposal https://github.com/dotnet/corefx/issues/37012)
- [ ] Consider optimizing handling of `yield return` when directly following another `yield return` (to reduce cost in `ManualResetValueTaskSourceCore.SetResult`) (issue https://github.com/dotnet/roslyn/issues/31248, needs LDM)
- [ ] Factor the implementation of `GetStatus` and `OnCompleted` for implementing `IValueTaskSource` and `IValueTaskSource<bool>` https://github.com/dotnet/roslyn/issues/31517
- [ ] Test `goto`, `continue`, `break`
- [ ] Consider optimizing stack consumption https://github.com/dotnet/roslyn/issues/26567
- [ ] Improve message when missing `async` https://github.com/dotnet/roslyn/issues/31113
- [ ] test async method returning a custom type that derives from `IAsyncEnumerable<T>` and `IAsyncEnumerator<T>`.
- [x] BCL design
    - [x] ~~factor some code into a base type?~~ (no)
    - [x] ~~introduce new exception type?~~ (not needed at the moment)
    - [x] Any work needed for mono support? (issue https://github.com/mono/mono/issues/12019, PR https://github.com/mono/mono/pull/12674, `EnumeratorCancellation` issue https://github.com/mono/mono/issues/14454)
- [x] test spilling (maybe need to integrate with Neal's changes in patterns branch)
- [x] Get more test ideas from async method and iterator method tests
- [x] Debugging experience (issue https://github.com/dotnet/roslyn/issues/32246, fixed in preview3)
- [x] Consider adding a guard in `DisposeAsync()`: if state is `-1`, then throw. PR https://github.com/dotnet/roslyn/pull/31764
- [x] Optimize value returned from `MoveNextAsync()` if possible (issue https://github.com/dotnet/roslyn/issues/31246, PR https://github.com/dotnet/roslyn/pull/31645)
- [x] Add optional token to `GetAsyncEnumerator` API (PR https://github.com/dotnet/roslyn/pull/31624)
- [x] Should we add some guards for API mis-use? https://github.com/dotnet/roslyn/issues/30109
- [x] Generate token checks (answer: no)
- [x] Dispose on async-iterator with `finally` issue https://github.com/dotnet/roslyn/issues/30260, PR https://github.com/dotnet/roslyn/pull/31527
- [x] Confirm desired behavior for `DisposeAsync()`. it is ok to dispose before enumerating, and then you start enumerating?
- [x] Consider optimizing disposeModeField away when it isn't needed (answer: the optimization is not worth the loss of regularity)
- [x] Emit `AsyncIteratorStateMachineAttribute` PR https://github.com/dotnet/roslyn/pull/31553
- [x] Test scenario that uses `AwaitOnCompleted` instead of `AwaitUnsafeOnCompleted`
- [x] Adopt new BCL APIs (`AsyncIteratorMethodBuilder`, `ManualResetValueTaskSourceCore`, remove `IStrongBox<T>`) PR https://github.com/dotnet/roslyn/pull/31330
- [x] Returning `IAsyncEnumerator<T>` https://github.com/dotnet/roslyn/issues/31057, PR https://github.com/dotnet/roslyn/pull/31114
- [x] What do exception stack traces look like? Does the stack trace simplifier need to be updated?
- [x] Confirm `threadID` design (see https://github.com/dotnet/corefx/issues/3481)
- [x] `GetAsyncEnumerator()` method should make a new instance in some cases https://github.com/dotnet/roslyn/issues/30275, PR https://github.com/dotnet/roslyn/pull/31105
- [x] `IOperation` and `CFG` should not crash https://github.com/dotnet/roslyn/pull/30363
- [x] Update `IAsyncEnumerable` API https://github.com/dotnet/roslyn/pull/30280
- [x] hand-crafted prototype (https://github.com/jcouv/async-iterators/blob/master/src/Program.cs)
- [x] lowering implementation (https://github.com/dotnet/roslyn/pull/28218)
- [x] CoreCLR testing issue https://github.com/dotnet/coreclr/issues/20032
- [x] support generic methods
- [x] manual testing in IDE (setting up project references, typing, debugging)

## Async using and foreach
- [x] Design and fix IOperation and CFG support https://github.com/dotnet/roslyn/issues/30362
- [ ] test with ref struct iterator (issue https://github.com/dotnet/roslyn/issues/32794)
- [ ] pattern-based disposal should not even consider extensions (issue https://github.com/dotnet/roslyn/issues/32767)
- [ ] add test with pattern-based GetAsyncEnumerator with a Caller attribute on optional parameter (check LINQ behavior)
- [ ] Allow extension methods to contribute to pattern-based binding (issue https://github.com/dotnet/roslyn/issues/32289)
- [ ] Tweak message for `ERR_AwaitForEachMissingMemberWrongAsync`
- [ ] Implement semantic model API similar to `GetAwaitExpressionInfo`
- [ ] Test scripting
- [ ] Test subtleties of `SatisfiesForEachPattern` (special method of looking up `Current`)
- [ ] Test type that is both `IEnumerable<T>` and `IAsyncEnumerable<T>`.
- [ ] Test type that is both `IDisposable` and `IAsyncDisposable`.
- [x] Allow pattern-based disposal in `await foreach` and `await using` (issue https://github.com/dotnet/roslyn/issues/32316)
- [x] Async-enumerable returned by `ConfigureAwait`/`WithCancellation` not recognized by `await foreach` (issue https://github.com/dotnet/roslyn/issues/31609, PR https://github.com/dotnet/roslyn/pull/32233)
- [x] Pattern-based lookup should pass no argument for `CancellationToken` (issue https://github.com/dotnet/roslyn/issues/32111, PR https://github.com/dotnet/roslyn/pull/32184)
- [x] Integration with "enhanced using and foreach" feature https://github.com/dotnet/roslyn/issues/28588
- [x] Test/block expression trees (N/A because they are statements)
- [x] `IOperation` and `CFG` should not crash https://github.com/dotnet/roslyn/pull/30363
- [x] Use `await using` and `await foreach` syntax https://github.com/dotnet/roslyn/pull/30525
- [x] Update `IAsyncEnumerable` API https://github.com/dotnet/roslyn/pull/30280
- [x] Do we prefer pattern-based over interface-based? (I assume perf is better)
- [x] ~~Only convert/deconstruct when `TryGetNext` succeeded https://github.com/dotnet/roslyn/issues/30258~~
- [x] async using (PR https://github.com/dotnet/roslyn/pull/23961)
- [x] async foreach (PR https://github.com/dotnet/roslyn/pull/24750)
- [x] Update `IAsyncEnumerator.WaitForNextAsync` to return a `ValueTask<bool>`.
- [x] Pattern-based foreach should recognize task-like return from `WaitForNextAsync`
- [x] Verify debugging and sequence points
- [x] Handle `foreach await (ref x in ...) ...` (error, ` TestWithPattern_Ref`)
- [x] Test with missing well-known members, if not already covered
- [x] Pattern-based async-foreach should recognized `WaitForNextAsync` that returns a task-like.

## Productivity (code fixers/refactorings/etc):
- [x] ~~ExtractMethod doesn't work on parts of or entire async-iterator method body~~ (that's expected)
- [x] FindAllReferences (moved all FAR issues into https://github.com/dotnet/roslyn/issues/28228)
    - [x] it should find implicit references to `GetAwaiter` from an async-foreach or async-dispose. 
     - [x] it should find implicit references to `DisposeAsync` from an async-foreach or async-dispose. 
- [x] Verify FAR on `AsyncDispose` method
- [x] ~~decompilation feature in IDE~~ (we'll let ILSpy library fix this)
- [ ] Verify proper warnings if any involved member is obsolete (implicit conversions and such)
- [x] Code fixers: 
    - [x] fix `foreach` (by adding/removing `await`) depending on the collection type. (PR https://github.com/dotnet/roslyn/pull/33463)
    - [x] fix `using` (by adding/removing `await`) depending on resource type. (PR https://github.com/dotnet/roslyn/pull/33463)
    - [x] fix method declaration depending on presence/absence of `yield` or `await` (MakeMethodAsync PR https://github.com/dotnet/roslyn/pull/31846)
    - [x] using `foreach await` in non-async method should offer to convert the method to `async` https://github.com/dotnet/roslyn/pull/26632
- [x] IDE logic probably needs to be adjusted for completion inside `await using` and `await foreach`. For instance, see `IsLocalVariableDeclarationContext`.
- [x] Review TypeInferrer https://github.com/dotnet/roslyn/pull/30211#discussion_r221462807 (PR https://github.com/dotnet/roslyn/pull/31046)
- [x] parsing (PR https://github.com/dotnet/roslyn/pull/23866)
- [x] IDE completion and colorizing (https://github.com/dotnet/roslyn/pull/23960)
- [x] Verify highlighting for `async` and `await` (see https://github.com/dotnet/roslyn/pull/25037, PR https://github.com/dotnet/roslyn/pull/25056) (verified manually on method and local function)
- [x] Test with `ConvertForeachToFor` refactoring (verified manually, not triggered)

## LDM open issues:

- [ ] async LINQ
    - [ ] Parsing issue with `return from e in async-collection select await e + 1; // await isn't a keyword`
    - [ ] how does above scenario and `return from e in async-collection select e + 1;` lower into LINQ APIs? (the one with `await` involves `Task<int>` and the other one involves `int` directly) How many overloads of `Select` do we need?
- [ ] Should there be some helper method to convert from IEnumerable to IAsyncEnumerable, or from Task<T> to IAsyncEnumerable?
- [x] Should the generate token checks be in `GetAsyncEnumerator` or in `MoveNextAsync`? (if we do, we need to store the token and maybe dispose it too) (answer: no)
- [x] Revisit blocking off a word (either in parameter list, like `params`, or for variable name, like `value`) for token (answer: we're not going to use a keyword)
- [x] pattern-based `await using` should recognize a `DisposeAsync` method that returns a task-like (or only `ValueTask`)? (not applicable because no ref structs in async methods)
- [x] Should pattern-based `foreach` recognize `... GetAsyncEnumerator()` (without `CancellationToken`)? (yes, LDM 1/9)
- [x] What attributes should be emitted on async-iterator state machines? (answer: `AsyncIteratorStateMachineAttribute`)
- [x] cancellation of async-streams (both as consumer and producer) (see LDM 11/28)
- [x] confirm syntax for async foreach
- [x] Should we disallow `struct` async enumerator? (no, same as regular async, see ` TestWithPattern_WithStruct_MoveNextAsyncReturnsTask`)
- [x] Should `DisposeAsync` return a non-generic `ValueTask`, since there is now one? Or stick with `Task`?
- [x] Extension methods for `GetAsyncEnumerator`, `WaitForNextAsync`, and `TryGetNext` do not contribute. This mirrors behavior for regular `foreach`. But I'd like to confirm. (answer: this is probably something we want to support. Let's queue that for later in the implementation)
- [x] Should the pattern for async enumerators also recognize when a task-like is returned instead of `Task<bool>`? (answer: yes)
- [x] I think we'll need to block `dynamic` since there is no async counterpart to the non-generic `IEnumerable` that would convert `dynamic` to. (answer: seems ok)
- [x] Do we need `async` keyword on async iterator methods? I assume yes.
- [x] Since not enumerable lambdas, I assume the same for async-enumerable. (answer: correct. No async iterator lambda)
- [x] async-iterator without `yield` or `await`, should warn? (answer: without `yield` it's not recognized as an iterator, warn when no `await`)
- [x] I suspect we'll need to declare the loop variable differently: calling `TryGetNext` first, then checking `success` and only then dealing with conversions and deconstructions.

Championed issue: https://github.com/dotnet/csharplang/issues/43 (includes LDM notes)

## Test ideas for async foreach:
- [x] Verify that async-dispose doesn't have a similar bug with struct resource

## Test ideas for async using:
- [ ] Look up Lippert's blog on using with struct or generic type T
- [ ] Does the pattern or the interface get picked up first? Is it observable? (maybe if the pattern allows task-like returning method)

## Test ideas for async iterators:
- [ ] From Andy: we should have at least one test that runs using a non-trivial sync context. 
- [ ] From Andy: would it be useful to emit asserts for invalid/unexpected states for at least a little while? We could do it only for debug codegen.
- [x] Test with yield or await in try/catch/finally
- [ ] More tests with exception thrown in async-iterator
- [ ] There is a case in `GetIteratorElementType` with `IsDirectlyInIterator` that relates to speculation, needs testing
- [ ] yield break disallowed in finally and top-level script (see `BindYieldBreakStatement`); same for yield return (see `BindYieldReturnStatement`)
- [ ] binding for yield return (`BindYieldReturnStatement`) validates escape rules, needs testing
- [x] test yield in async lambda (still error)
- [ ] test with `IAsyncEnumerable<dynamic>`
- [ ] other tests with `dynamic`?
- [x] test should cover both case with `AwaitOnCompleted` and `AwaitUnsafeOnCompleted`
- [ ] test `async IAsyncEnumerable<int> M() { return TaskLike(); }`
- [ ] Can we avoid making `IAsyncEnumerable<T>` special from the start? Making mark it with an attribute like we did for task-like?
- [ ] Do some manual validation on debugging scenarios, including with exceptions (thrown after yield and after await).
- [ ] Test with one or both or the threadID APIs missing.

----
## BCL (Core)
- Add `DefaultCancellationAttribute` type: https://github.com/dotnet/corefx/issues/37012
- Design IAsyncEnumerable and supporting types to BCL: https://github.com/dotnet/corefx/issues/32640 
- Design IAsyncDisposable in BCL: https://github.com/dotnet/corefx/issues/32665
- Design for CancellationToken in IAsyncEnumerable: https://github.com/dotnet/corefx/issues/33338
PRs https://github.com/dotnet/coreclr/pull/20442 and https://github.com/dotnet/corefx/pull/33104
- Stack pretty printing https://github.com/dotnet/coreclr/pull/21103
- Add optional token to `GetAsyncEnumerator` API
- Add extension method `WithCancellation(...)` to call `GetAsyncEnumerator` and wrap the result into an `IAsyncEnumerable`
- AsyncIteratorStateMachineAttribute https://github.com/dotnet/corefx/issues/33770, PR https://github.com/dotnet/coreclr/pull/21313 (and using it https://github.com/dotnet/coreclr/pull/21396)
- Add `CancellationToken` to `GetAsyncEnumerator()` PR https://github.com/dotnet/coreclr/pull/21397, documentation https://github.com/dotnet/corefx/issues/33338#issuecomment-444728011
- Add `WithCancellation` design https://github.com/dotnet/corefx/issues/33909
- Add `IAsyncDisposable.ConfigureAwait` (PRs https://github.com/dotnet/coreclr/pull/22160 and https://github.com/dotnet/corefx/pull/34783)

## BCL (mono)
- Port types to mono (https://github.com/mono/mono/issues/12019)

## BCL (package)
- Add `EnumeratorCancellationAttribute` (PR https://github.com/dotnet/corefx/pull/37719)

-----
## References:
- [ValueTask](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs#L60)
- [IValueTaskSource](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Threading/Tasks/Sources/IValueTaskSource.cs)

**Comment by jcouv** [comment]
Notes from chat with Stephen:

The promise should not just be a TaskCompletionSource. It should be possible to make a re-usable `ValueTask<bool>` and completion machinery, thus avoiding allocating entirely. 
See [`ManualResetValueTaskSource.cs`](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Threading/Tasks/Sources/ManualResetValueTaskSource.cs) in corefx. It should be based on `IValueTaskSource` which should ship in .NET Core 2.1 and down-level (.NET Standard 1.1 or maybe 1.0).
Then `Unpronounceable` would implement `IValueTaskSource`.
It is possible that .NET Core 2.2 would introduce some reusable type(s) for abstracting this sort of stuff. Then we may not need to inline all the extra fields and low-level logic.
As long as the compiler-generated code has a way to tell whether there is no promise, then we’re good. That seems to be possible.
We need to discuss this type dependency.

We’ll have a base type, which common machinery (as both our prototypes did). We should discuss how this type will arrive in the compilation (always generate, or generate if not referenced, or always use reference?). 
If the API can be referenced, then we need to lock API. This question also affects above API dependency.

For ConfigureAwait, we could have an extension `ConfiguredValueTaskAwaitable<bool> ConfigureAwait(this IValueTaskSource)`, and `ConfiguredValueTaskAwaitable<T>` is a task-like.
So we’d need the pattern-based async-foreach to recognize `WaitForNextAsync` methods that return a task-like.
Need to confirm with LDM.

For CancellationToken, we could just treat the token as a regular local, captured and available to use in the user code.
There may have been some pushback on this (Bart, maybe Lucien). Not clear what the problem is (composability) or what the alternative would be (state machine intrinsics?).

For `GetAsyncEnumerable()`, we can use the same logic as currently used in async unpronounceable type. 
But should read this thread (https://github.com/dotnet/corefx/issues/3481) and confirm with Vlad.
The thread check is meant to emulate an interlocked exchange. We should confirm this is indeed better than interlocked.

We discussed trade-off between WaitForNextAsync/TryGetNext vs. MoveNextAsync/Current patterns. 
It just comes down to perf vs. pattern complexity (for implementing LINQ methods like Group, etc that aren’t straight `foreach` loops, for example).

**Comment by jcouv** [comment]
Notes on testing the feature in dev hive:
- add a reference to NuGet package `System.Threading.Tasks.Extensions` (I've used `4.5.1`)
- add the following code to provide types (including `IAsyncEnumerable<T>` and `ManualResetValueTaskSourceLogic<T>`:

```C#

namespace System.Collections.Generic
{
    public interface IAsyncEnumerable<out T>
    {
        IAsyncEnumerator<T> GetAsyncEnumerator();
    }

    public interface IAsyncEnumerator<out T> : System.IAsyncDisposable
    {
        System.Threading.Tasks.ValueTask<bool> WaitForNextAsync();
        T TryGetNext(out bool success);
    }
}
namespace System
{
    public interface IAsyncDisposable
    {
        System.Threading.Tasks.ValueTask DisposeAsync();
    }
}

namespace System.Runtime.CompilerServices
{
    public interface IStrongBox<T>
    {
        ref T Value { get; }
    }
}

namespace System.Threading.Tasks
{
    using System.Runtime.CompilerServices;
    using System.Runtime.ExceptionServices;
    using System.Threading.Tasks.Sources;

    public struct ManualResetValueTaskSourceLogic<TResult>
    {
        private static readonly Action<object> s_sentinel = new Action<object>(s => throw new InvalidOperationException());

        private readonly IStrongBox<ManualResetValueTaskSourceLogic<TResult>> _parent;
        private Action<object> _continuation;
        private object _continuationState;
        private object _capturedContext;
        private ExecutionContext _executionContext;
        private bool _completed;
        private TResult _result;
        private ExceptionDispatchInfo _error;
        private short _version;

        public ManualResetValueTaskSourceLogic(IStrongBox<ManualResetValueTaskSourceLogic<TResult>> parent)
        {
            _parent = parent ?? throw new ArgumentNullException(nameof(parent));
            _continuation = null;
            _continuationState = null;
            _capturedContext = null;
            _executionContext = null;
            _completed = false;
            _result = default;
            _error = null;
            _version = 0;
        }

        public short Version => _version;

        private void ValidateToken(short token)
        {
            if (token != _version)
            {
                throw new InvalidOperationException();
            }
        }

        public ValueTaskSourceStatus GetStatus(short token)
        {
            ValidateToken(token);

            return
                !_completed ? ValueTaskSourceStatus.Pending :
                _error == null ? ValueTaskSourceStatus.Succeeded :
                _error.SourceException is OperationCanceledException ? ValueTaskSourceStatus.Canceled :
                ValueTaskSourceStatus.Faulted;
        }

        public TResult GetResult(short token)
        {
            ValidateToken(token);

            if (!_completed)
            {
                throw new InvalidOperationException();
            }

            _error?.Throw();
            return _result;
        }

        public void Reset()
        {
            _version++;

            _completed = false;
            _continuation = null;
            _continuationState = null;
            _result = default;
            _error = null;
            _executionContext = null;
            _capturedContext = null;
        }

        public void OnCompleted(Action<object> continuation, object state, short token, ValueTaskSourceOnCompletedFlags flags)
        {
            if (continuation == null)
            {
                throw new ArgumentNullException(nameof(continuation));
            }
            ValidateToken(token);

            if ((flags & ValueTaskSourceOnCompletedFlags.FlowExecutionContext) != 0)
            {
                _executionContext = ExecutionContext.Capture();
            }

            if ((flags & ValueTaskSourceOnCompletedFlags.UseSchedulingContext) != 0)
            {
                SynchronizationContext sc = SynchronizationContext.Current;
                if (sc != null && sc.GetType() != typeof(SynchronizationContext))
                {
                    _capturedContext = sc;
                }
                else
                {
                    TaskScheduler ts = TaskScheduler.Current;
                    if (ts != TaskScheduler.Default)
                    {
                        _capturedContext = ts;
                    }
                }
            }

            _continuationState = state;
            if (Interlocked.CompareExchange(ref _continuation, continuation, null) != null)
            {
                _executionContext = null;

                object cc = _capturedContext;
                _capturedContext = null;

                switch (cc)
                {
                    case null:
                        Task.Factory.StartNew(continuation, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
                        break;

                    case SynchronizationContext sc:
                        sc.Post(s =>
                        {
                            var tuple = (Tuple<Action<object>, object>)s;
                            tuple.Item1(tuple.Item2);
                        }, Tuple.Create(continuation, state));
                        break;

                    case TaskScheduler ts:
                        Task.Factory.StartNew(continuation, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach, ts);
                        break;
                }
            }
        }

        public void SetResult(TResult result)
        {
            _result = result;
            SignalCompletion();
        }

        public void SetException(Exception error)
        {
            _error = ExceptionDispatchInfo.Capture(error);
            SignalCompletion();
        }

        private void SignalCompletion()
        {
            if (_completed)
            {
                throw new InvalidOperationException();
            }
            _completed = true;

            if (Interlocked.CompareExchange(ref _continuation, s_sentinel, null) != null)
            {
                if (_executionContext != null)
                {
                    ExecutionContext.Run(
                        _executionContext,
                        s => ((IStrongBox<ManualResetValueTaskSourceLogic<TResult>>)s).Value.InvokeContinuation(),
                        _parent ?? throw new InvalidOperationException());
                }
                else
                {
                    InvokeContinuation();
                }
            }
        }

        private void InvokeContinuation()
        {
            object cc = _capturedContext;
            _capturedContext = null;

            switch (cc)
            {
                case null:
                    _continuation(_continuationState);
                    break;

                case SynchronizationContext sc:
                    sc.Post(s =>
                    {
                        ref ManualResetValueTaskSourceLogic<TResult> logicRef = ref ((IStrongBox<ManualResetValueTaskSourceLogic<TResult>>)s).Value;
                        logicRef._continuation(logicRef._continuationState);
                    }, _parent ?? throw new InvalidOperationException());
                    break;

                case TaskScheduler ts:
                    Task.Factory.StartNew(_continuation, _continuationState, CancellationToken.None, TaskCreationOptions.DenyChildAttach, ts);
                    break;
            }
        }
    }
}
```

**Comment by jcouv** [comment]
Will be adding some notes on WIP design here

**Comment by jcouv** [comment]
Individual issues have been open for follow-ups (optimizations and improved diagnostics)
