### ISSUE TITLE
[Umbrella] Add IgnorePortablePDBsInStackTraces in config files for partner tools

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#25088]
Currently, we need to add this to `machine.config`
```
  <runtime>
     <AppContextSwitchOverrides value="Switch.System.Diagnostics.IgnorePortablePDBsInStackTraces=false" />
  </runtime>
```

Modifying the config file in our repo doesn't work, so we'll need to update the config file for various hosts:
- [ ] vstest (https://github.com/microsoft/vstest)
- [x] TDD.Net (https://github.com/jcansdale/TestDriven.Net-Issues/issues/120)
- [ ] xunit.wpf.runner
- [ ] xunit.console.runner
- [ ] nunit

Tagging @tmat @jaredpar 

Notes to self:
`master` seems to be using [embedded](https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.props#L124), while `dev15.7.x` uses [full](https://github.com/dotnet/roslyn/blob/dev15.7.x/build/Targets/Settings.props#L123) PDB files.

Checking for 4.7.2: `Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\"`

Some background on [4.7.1 issue](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/517815-BCL%20Applications%20making%20heavy%20use%20of%20System.Diagnostics.StackTrace%20might%20run%20more%20slowly%20on%20.NET%204.7.1.md) and [servicing fix](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/517815-BCL%20Stack%20traces%20are%20missing%20source%20information%20for%20frames%20with%20debug%20information%20in%20the%20Portable%20PDB%20format.md).

Our [how to contribute](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md) pages are out-of-date on this issue.

**Comment by tmat** [comment]
The .config files where this is needed are not ours. They are XUnit's.

**Comment by jcouv** [comment]
@tmat 
When I look in the test folder (such as `Binaries\Debug\UnitTests\CSharpCompilerSemanticTest`), I see that there is a config file which I think comes from our repo (not XUnit).
It has own own trace listener and binding redirects that are specific to us.

Why can't we add the `AppContextSwitchOverrides` key there?

**Comment by tmat** [comment]
I'm not sure how these config values are applied by XUnit. You can try it to see if it works.

**Comment by jaredpar** [comment]
Those config files are just for app setting, doubt you can change the runtime. @noahfalk may know. 

FYI though we may be moving off of the XML files soon and onto JSON as it's the universally supported file.

**Comment by jcouv** [comment]
Indeed. Seems that approach didn't work. 

The config file in the test folder (`\roslyn\Binaries\Debug\UnitTests\CSharpCompilerEmitTest\Roslyn.Compilers.CSharp.Emit.UnitTests.dll.config`) looks correct, but it didn't have any apparent effect.

**Comment by jaredpar** [comment]
Note though: changing this setting only fixes xunit. It doesn't fix test explorer or any other source of stack traces.

**Comment by jcouv** [comment]
Putting the flag in the config files for `TestDriven` worked.
`C:\Program Files (x86)\TestDriven.NET 4\ProcessInvocation86.exe.config`
`C:\Program Files (x86)\TestDriven.NET 4\ProcessInvocation.exe.config`

**Comment by jaredpar** [comment]
Other products that need to update: wpf test runner and test explorer.

**Comment by tmat** [comment]
@KevinH-MS

**Comment by KevinH-MS** [comment]
If we need something in testhost (used by test explorer), then we need to file a bug in https://github.com/microsoft/vstest

**Comment by jcouv** [comment]
I've not seen any other reports of problems related to this, so I'll go ahead and close this tracking issue.
