### ISSUE TITLE
Remaining questions on suppression operator

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#28271]
- [ ] Should `!` suppress warnings for nested nullability? (answer: yes) (this relates to the behavior of cast) https://github.com/dotnet/roslyn/issues/29642
- [ ] What is the state resulting from `obliviousValue!`? (answer: Top-level non-null, suppressed warnings for nested.)
- [ ] Should `!!` be an error? https://github.com/dotnet/roslyn/issues/29902
- [x] Should `nonNull!` result in a warning for unnecessary `!`? (answer: no) https://github.com/dotnet/roslyn/issues/25372

**Comment by jcouv** [comment]
The language design questions were answered. See https://github.com/dotnet/csharplang/blob/master/meetings/2018/LDM-2018-08-20.md#remaining-questions-on-suppression-operator

**Comment by jcouv** [comment]
Remaining issues are tracked separately. Closing
