### ISSUE TITLE
CoreClr / Mono test tracking bugs

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#29859]
This is an uber issue tracking all of the runtime issues we are seeing on CoreClr and Mono when executing our suites.

CoreClr Issues:
- [ ] VB emit tests seg fault on Linux https://github.com/dotnet/coreclr/issues/19862

Mono Issues:
- [x] SIGSEGV running semantic tests https://github.com/mono/mono/issues/10309 
- [ ] SIGABRT running symbol tests https://github.com/mono/mono/issues/10332
