### ISSUE TITLE
IDE Threading improvements

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#30463]
- [ ] Use IThreadingContext instead of ThreadHelper

Currently we use both `IThreadingContext` and `ThreadHelper`. We should unify code on the former for two reasons:

1. Consistency
2. `IThreadingContext` allows for work tracking, which improves the ability to isolate tests that run asynchronous code

> ❓  Is there a reason this isn't using `IThreadingContext`? It seems like we should be using that interface to the extent possible.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/30451_

- [ ] Audit uses of ContinueWith. Audit uses of ContinueWith, SafeContinueWith, StartNew, SafeStartNew, and Task.Run to identify cases where simpler approaches are viable
- [ ] Uniformly use a main thread check/assert method. Design, implement, and uniformly use a main thread check/assert method
- [ ] Configure problematic synchronous waits. Configure WaitAndGetResult and WaitAndGetResult_CanCallOnBackground as problematic synchronous waits (blocked on https://github.com/microsoft/vs-threading/issues/344)
- [ ] Review code for additional methods to consider legacy thread switching APIs.  From https://github.com/dotnet/roslyn/pull/28781. This is blocked on https://github.com/microsoft/vs-threading/issues/332, but once available we should review the code for thread-switching APIs and configure them so they are recognized by analyzers in vs-threading.
- [ ] Eliminate JoinableTaskFactoryTaskScheduler. From https://github.com/dotnet/roslyn/pull/28781#discussion_r208393493. Eliminate JoinableTaskFactoryTaskScheduler, or at least add it to the set of legacy thread switching types. Related to https://github.com/dotnet/roslyn/issues/29277

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.
