### ISSUE TITLE
Test plan for "Parameter null-checking"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#36024]
This is a place to collect test ideas.

Proposal: https://github.com/dotnet/csharplang/issues/2145

### Specification
- [x] Specification checked in to `csharplang` [link](https://github.com/dotnet/csharplang/blob/main/proposals/param-nullchecking.md)
- [x] Confirm codegen (use helper method from BCL, and/or fallback to generating `if/throw`)

### Infrastructure

- [x] LangVersion check
- [x] IOperation/CFG nodes

### Parsing
- [x] `string s !!= null` parsed as `string s!! = null`

### Generics
- [x] `void M<T>(T value!) { }` is OK
- [x] `void M<T>(T value!) where T : struct { }` is an error
- [x] `void M<T>(T value!) where T : unmanaged { }` is an error
- [x] `void M<T>(T value!) where T : notnull { }` is OK
- [x] `void M<T>(T value!) where T : class { }` is OK
- [x] `void M<T>(T value!) where T : SomeStruct { }` is an error
- [x] `void M<T>(T value!) where T : SomeClass { }` is OK

### Iterators

Null checking should always happen in initial call, not lowered methods

- [x] Top-level iterator method returning IEnumerable
- [x] Top-level iterator method returning IEnumerator
- [x] Local function returning IEnumerable
- [x] Local function return IEnumerator

### Constructors

Null checking should be the first thing in a constructor

- [x] Constructor with field initializers
- [x] Constructor with `this` call
- [x] Constructor with `base` call
- [x] Record and record struct primary constructors

### Nested functions
- [x] Null-checked lambda parameter
- [x] Null-checked local function parameter
- [x] Null-checked lambda parameter inside field initializer
- [x] allowed in anonymous method syntax `delegate (object o!!) { }`
- [x] allowed in lambda parameter without explicit type (with and without parentheses) `x!! => x`, `(x, y!!) => y`
- [x] allowed in lambda discard parameter `_!! => { }`

### Warnings and errors
- [x] Warn on null-checked parameter with default `null` value
- [x] Warn on `string? x!` (null-check doesn't make sense on those)
- [x] Error on `int x!` parameters
- [x] Error on `out string x!` (null-check doesn't make sense on `out` parameter)
- [x] Error on null-check on declarations without bodies (`interface` members, `abstract`, `extern`, declaration portion of a `partial` method)

### Misc.
- [x] uses reference equality (user-defined conversions are ignored)
- [x] no boxing in check for `S? s!!` for `struct` type `S`
- [x] check argument in getter and setter of indexer

### Misc (from discussion in LDM)
- [x] Null-checked `params` parameter (allowed, checks the array, not the elements)
- [x] test `void M<T>(T t!) where T : notnull { ... }` (ok)
- [x] should we use [helper type](https://github.com/dotnet/runtime/issues/48573) from BCL to throw exception?
- [x] Null-checked pointers and function pointers (works as expected)
- [x] error on `__arglist!!`

### From test plan review
- [x] confirm CFG design with API review **(delaying resolution till after feature merge)**  #58307
- [x] LDM: allow on lambda parameter without type or parentheses? resolution: Allow.
- [x] LDM: allow on lambda discard parameter? resolution: Disallow. **(delaying till after feature merge)** #58952
- [x] `async` iterator methods
- [x] LDM: allow on `ref` or `in` parameters? resolution: Allow. #58938
- [ ] check for unconstrained `T` does not box when `T` is a nullable value type (include a `ThrowIfNull<T>(T value, string parameterName)` helper method?)  **(delaying till after feature merge)**
    - We don't box, but we also don't call the 'Throw' helper, which could improve inlining behavior of methods with null checked `Nullable<T>` parameters.
- [x] disallow in `delegate` declaration
- [x] `override` and `interface` implementation with/without `!!` is allowed
- [x] `SymbolDisplay` is not affected
- [x] IDE: classification, formatting, `SyntaxNormalizer`, quick info, typing, completion

### Productivity
- [x] Verify formatting in IDE
- [x] verify that IDE doesn't gray out null-checked parameter which is otherwise unused
- [x] need an analyzer/fixer to convert codebase **(delaying till after feature merge)** #58182
- [ ] Update F1 service a la #60156

**Comment by jcouv** [comment]
I added a bunch of test scenarios from today's LDM decision.

**Comment by 333fred** [comment]
Need to consider `(_!!, _!!) => {}` behavior.

**Comment by jcouv** [comment]
From discussion with BCL and runtime folks, we've landed on:
"Roslyn injects an internal ThrowIfNull(object argument, string argumentName) <PrivateImplementationDetails> helper into every assembly that uses the feature, similar to how it injects helpers into assemblies for other purposes, like switching on strings (SharpLab) or use of nullability annotations (SharpLab)"

**Comment by Youssef1313** [comment]
> Warn on null-checked parameter with default null value

Caller member infos may be an exception to this.

**Comment by Youssef1313** [comment]
Also consider `__arglist`, it shouldn't be allowed to have `!!` after it.

**Comment by 333fred** [comment]
> > Warn on null-checked parameter with default null value
> 
> Caller member infos may be an exception to this.

I don't agree, fwiw. If you already get a warning if you do `M(string s = null)` in nullable-enabled code. I don't see why this would follow different reasoning.

**Comment by CyrusNajmabadi** [comment]
I started agreeing with @Youssef1313   but came around to Fred's thinking. You find have `[callerxxx] string s!! = ""`.

**Comment by Youssef1313** [comment]
Hmm.. I met a case while working on caller argument expression that actually made me agree with @333fred.

```
using System;
using System.Runtime.CompilerServices;

public class MyAttribute : Attribute
{
    public MyAttribute([CallerMemberName] string callerName = null)
    {
    }
}

[My]
public class Program
{
    static void Main()
    {
    }
}
```

This code will provide the default parameter value `null`. I didn't knew it was possible for the compiler to provide the default argument value for caller info.

**Comment by 333fred** [comment]
>  I didn't knew it was possible for the compiler to provide the default argument value for caller info.

Even if it wasn't, it's always possible for the user to explicitly supply one, and if the parameter was annotated as nullable then null should be perfectly valid to pass.

**Comment by hez2010** [comment]
I think this shouldn't emit a null reference return warning: https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAcoKgW1QOzgBsiBjACwlIGsBLfAcwBoYQE58AfAYkJKmBEIAAgj4BQgLAAoAAIAmAIwyZsxQAZhAUXzJEEAHIB7GAeJEAFGvUB+YcgCEDgJQyA3jOFfhsgOz2AbhkAXxU5RQBOCx09JGNTcwsAIkAeDcAQfaTnZwCgA

**Comment by Youssef1313** [comment]
@hez2010 It looks like there are few attributes that should be generated by the compiler but are not currently.:

```diff
 [CompilerGenerated]
 internal sealed class <PrivateImplementationDetails>
 {
+    [DoesNotReturn]
     internal static void Throw(string paramName)
     {
         throw new ArgumentNullException(paramName);
     }

-    internal static void ThrowIfNull(object argument, string paramName)
+    internal static void ThrowIfNull([NotNull] object argument, string paramName)
     {
         if (argument == null)
         {
             Throw(paramName);
         }
     }
 }

```

**Comment by RikkiGibson** [comment]
The `Throw`/`ThrowIfNull` functions don't exist in the bound tree used by nullable analysis, so I think we would want to solve this by ensuring the "initial state" of a parameter with `!!` is properly updated to not-null.

Thanks for catching this issue @hez2010!

**Comment by Youssef1313** [comment]
@jaredpar Should this be closed?
