### ISSUE TITLE
Remove unused references/nuget packages 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/roslyn#36068]
**User Scenario**
Users should be able to
- see unused assemblies, packages, and project references
- remove unused references

**Design**

- [ ] 1.	https://github.com/dotnet/roslyn/issues/37768 The compiler team will provide an API to list used references in the compilation (or the same: unused references in the compilation). These are individual assembly references.

- [ ] 2.	https://github.com/dotnet/cli/issues/12168 The build team will generate a file with a map of assemblies, packages which can be checked for usage/non-usage.  MS Build will generated the file. If other environments are used, they have to provide this file on their own.

- [ ] 3.	https://github.com/dotnet/project-system/issues/5258 The project-system team will provide an API for fixing issues.

- [ ] 4.	https://github.com/dotnet/roslyn/issues/37769 The IDE team will look for both the compiler API, the file generated and the project-system API, and provide an analyzer with a fixer that will report references which can be removed.

- [ ] 5.	The project-system team will help with driving UI implementation. It can be grey out references with actions in the context menu or  a special user control like one described below. This can be decided later based on restrictions found on previous steps.

**UX Model**
The functionality should be available in the Solution Explorer. In an ideal case, we should grey out unused references directly in the Solution Explorer and add an option in the context menu to remove them. If this is not available e.g. due to performance reasons, please see the UX model below.

Here is the UX model in case if we cannot arrange this directly in the Solution Explorer:
1. In the Solution Explorer right click on either a project, a solution or the References node of a project.

2. Have 2 of the following options:
A. Right-click the selection and choose an option to Remove Unused References in the context menu.
B. Or a keyboard shortcut to Remove Unused References.

3. When selecting Remove Unused References have a dialogue that displays all references that have no actual usages in source code in a tree view grouped by projects. By default, all references are selected for deletion. If necessary, deselect references that you want to keep.

![nuget-package!](https://user-images.githubusercontent.com/46729679/60834821-6a1cdc80-a176-11e9-9bae-51a9e0fe5cf3.png)

4. Then select update to remove the unused references/nuget packages.

**Comment by gafter** [comment]
Please let the compiler team know if you want to do this, as it will likely require a compiler API or hidden diagnostics.

**Comment by dpoeschl** [comment]
Related: https://github.com/dotnet/roslyn/issues/6763

**Comment by jinujoseph** [comment]
Closing as to be tracked [here](https://github.com/dotnet/roslyn/issues/6763)
