### ISSUE TITLE
Test plan for "generic attributes"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#36285]
[Championed issue](https://github.com/dotnet/csharplang/issues/124) 
Latest [LDM notes](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-02-21.md#generic-attributes).

## Specification
- [x] Specification checked in to `csharplang` (https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/generic-attributes.md)

## Compiler
- [x] LangVersion
- [x] test GetAttributes and any other relevant compiler APIs
- [x] test consuming a generic attribute from a C# 7 compiler
    - netcoreapp2.1 programs can consume them just fine and even reflect on them even though certain APIs have bugs. Also, when an analyzer running with an old compiler encounters such attributes from metadata symbols, everything still works properly.
- [x] AllowMultiple (original definition is considered, not construction)
- [ ] Ambiguity when both `MyAttribute<T>` and `My<T>` are present (bug #54772)
- [x] Inheriting from a generic attribute
- [ ] Parameters of type parameter types with various constructions (revealed bug #55190)
- [x] Properties of type parameter types with various constructions
- [x] Update compiler test plan
- [x] Type parameter constraints are checked
- [x] Restricted types as type arguments (pointers, func pointers, TypedReference, ...)
- [x] Abstract static interface constraints are checked `where T : INumeric<..>` then argument is `IIntegral`
- [x] LookupSymbols should give substituted types as appropriate
- [x] Generic attributes on lambdas / expression lambdas (?)
- [x] Well-known attributes with additional type parameters are not recognized (`Obsolete<T>`)
- [x] VB consuming generic attributes
- [ ] consuming generic attributes from F# (non-blocking)
- [x] How do reflection APIs behave on generic attributes?
    - In new .NET versions they "just work" however pre-netcoreapp3.1 has some bugs. Runtime team considers the recent changes for generic attributes to be bug-fix level so we don't expect to check the user's target runtime for support--same situation as parameterless struct constructors. Related: dotnet/coreclr#9189
- [x] adding runtime support (https://github.com/dotnet/coreclr/pull/9189)
- [x] mono support or detection (issue https://github.com/dotnet/runtime/issues/56887)
- [x] Assembly-level attributes https://github.com/dotnet/msbuild/issues/6734
- [x] Query for open generics in typeof `Attribute.GetCustomAttributes(typeof(Program), typeof(Attr<>))`
- [ ] C++/CLI support ([tracking issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1448854))

## Productivity
- [x] verify typing, highlighting, formatting and completion behavior in IDE

**Comment by tmat** [comment]
- [ ] Add EnC compiler and IDE test

**Comment by ThaDaVos** [comment]
I don't know if this is fully related but the following logic fails when trying to resolve a Generic Attribute using the MetadataReader - it results in an exception of:
```
Unhandled exception. System.InvalidCastException: Specified cast is not valid.
     at System.Reflection.Throw.InvalidCast()
     at System.Reflection.Metadata.TypeReferenceHandle.op_Explicit(EntityHandle handle)
     at DNNE.Assembly.Attributors.Attributor.ParseCustomAttribute(MetadataReader reader, CustomAttribute attribute)
     at DNNE.Assembly.Attributors.Attributor.IsApplicable(MetadataReader reader, CustomAttribute attribute, Boolean isReturn)
     at DNNE.Assembly.AssemblyReader.<>c__DisplayClass12_0.<Read>b__0(IAttributor attributor)
     at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
     at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
     at DNNE.Assembly.AssemblyReader.Read()
     at DNNE.Program.Main(String[] args)
```

Maybe I am doing something wrong below - but I am not sure, can't really find much information about the `MetadataReader` and trying to add support for certain features to `DNNE`:

The following line throws the exception:
```C#
TypeReference refType = reader.GetTypeReference((TypeReferenceHandle)refConstructor.Parent);
```

which is in:

```C#
internal static (StringHandle? parsedNamespace, StringHandle? parsedName) ParseCustomAttribute(MetadataReader reader, CustomAttribute attribute)
{
    switch (attribute.Constructor.Kind)
    {
        case HandleKind.MemberReference:
            MemberReference refConstructor = reader.GetMemberReference((MemberReferenceHandle)attribute.Constructor);

            if (refConstructor.Parent.IsNil)
            {
                Debug.Assert(false, "Unknown parent reference kind");
                return (null, null);
            }

            switch (refConstructor.Parent.Kind)
            {
                case HandleKind.TypeReference:
                    TypeReference refType = reader.GetTypeReference((TypeReferenceHandle)refConstructor.Parent);
                    return (refType.Namespace, refType.Name);
                default:
                    Debug.Assert(false, "Unknown parent reference kind");
                    return (null, null);
            }
        case HandleKind.MethodDefinition:
            MethodDefinition defConstructor = reader.GetMethodDefinition((MethodDefinitionHandle)attribute.Constructor);
            TypeDefinition defType = reader.GetTypeDefinition(defConstructor.GetDeclaringType());
            return (defType.Namespace, defType.Name);

        default:
            Debug.Assert(false, "Unknown attribute constructor kind");
            return (null, null);
    }
}
```

**Comment by RikkiGibson** [comment]
Closing out the test plan as the feature has shipped.

If you are still experiencing a problem related to the feature, please file a new issue.
