### ISSUE TITLE
Test plan for "extended nameof scope"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#40524]
Championed issue: https://github.com/dotnet/csharplang/issues/373
Speclet: https://github.com/dotnet/csharplang/blob/main/proposals/extended-nameof-scope.md

- [x] Test with attributes on local functions
- [x] Test with attributes on lambdas
- [x] Test with attributes on delegates
- [x] Test with attributes on methods/constructors/operators
- [x] ~~Test with `main:`-targeted attributes (shouldn't work, since they are not on a method declaration)~~ (no longer applicable)
- [ ] Keep the breaks under LangVer preview for now, but remove that condition before shipping C# 11 (tracked by https://github.com/dotnet/roslyn/issues/60640)
- [ ] Speculation in attributes on local functions is broken (https://github.com/dotnet/roslyn/issues/60801)
- [ ] Remove LangVer condition (https://github.com/dotnet/roslyn/issues/60640)

## LDM
- [x] Breaking change (yes, but under preview LangVer for now)
- [x] Should we put type parameters in scope too? (yes)

## Productivity
- [ ] Completion (issue https://github.com/dotnet/roslyn/issues/60812)
- [ ] QuickInfo

**Comment by Youssef1313** [comment]
- Should have some tests with `CallerArgumentExpression`

**Comment by jcouv** [comment]
Feature was merged into 17.3p2

**Comment by jcouv** [comment]
Remaining follow-up issues are tracked by dedicated issues. Closing the test plan
