### ISSUE TITLE
Test plan for "records"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#40726]
Relates to championed issue: https://github.com/dotnet/csharplang/issues/39
Spec: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/records.md
Records board: https://github.com/dotnet/roslyn/projects/57

LDM:
- [x] `ToString`: should we always print a trailing comma `R { Property1 = 42, Property2 = 43, }`? (no)
- [x] `ToString`: can we deal with stack overflow potential? (do nothing special for now)
- [x] `ToString`: should we try to quote/escape values, for example `R { IntProperty = 42, StringProperty = "hello" }`? (no)
- [x] `ToString`: should we omit `ToString` on abstract records? (no)
- [x] `ToString`: should `PrintMembers` call `ToString()` on values to avoid boxing them in `builder.Append((object)value)`? (yes)
- [x] `ToString`: should we try and avoid the double space in empty record `R {  }`? (yes)
- [x] `ToString`: do we want to economize a call to `StringBuilder.Append` to print `<name> { `? (maybe)
- [x] warn on declaring type named "record" in C# 9? (yes)
- [x] Can we omit `EqualityContract` if the record type is sealed and derives from `System.Object`? (no)
- [x] Should we allow base syntax on record without parameter list? `record Derived : Base(0) { }` (yes)
- [ ] nullability expectations for `bool Equals(R? other)` and `Type EqualityContract { get; }` and `R? <Clone>$()` and `void Deconstruct(out string? NotNullableStringProperty)`. (issue https://github.com/dotnet/roslyn/issues/47627)
- [ ] Ensure spec forbids an empty parameter list.
- [ ] LDM: How to give base ctor arguments if there are no record parameters
- [x] Should records have a base type that isn't `object`? (no)
- [x] Allow `with` on non-record types (maybe with user-defined `Clone()` method)? (out of scope for C# 9)
- [x] Confirm syntax model for `data` properties (out of scope for C# 9)
- [x] Constraint for `with`-able? Allows `t with { ... }` with use of `: where T : I, with` (like we could do `: where T : I, new`)? (out of scope for C# 9)
- [x] Should anonymous objects be `with`-able? (out of scope for C# 9)
- [x] bringing structs closer to ideal value semantics (out of scope for C# 9)
- [x] `.ToString()` (yes)
- [x] xml docs (issue https://github.com/dotnet/roslyn/issues/44571, support `params` for now)
- [x] Should we allow `record Base { public int P => 0; } record Derived(int P);` and how does it work? (maybe `Derived` gets `new int P { get; init; }`, or maybe it's an error)
- [x] allow deriving from non-record types? (not in C# 9)
- [x] tagging record types (supports MetadataAsSource scenario, using unspeakable clone method for now)
- [x] confirm `data` vs. `record` syntax (`record Person(...)` for next preview)
- [x] init-only: should `_ = new C() { readonlyField = null };` be allowed in a method on type `C`? ([comment](https://github.com/dotnet/roslyn/pull/43275#discussion_r415209454)) (punted out of C# 9)
- [x] init-only: confirm metadata encoding (modreq?) and rules for dealing with ambiguous `IsExternalInit` type (confirmed)
- [x] init-only methods ? `init void Init()` (punted out of C# 9, strong interest, issue with `Add` methods in BCL immutable collection types)
- [x] `with` initializer with expressions allowed in other kinds of initializers, such as `[0] = 2` or values for `IEnumerable/Add` collection. (punted out of C# 9)

## Record declarations

Compiler:
- [x] Block or handle EnC (https://github.com/dotnet/roslyn/issues/44877)
- [x] xml docs (params should apply to primary constructor parameters) (https://github.com/dotnet/roslyn/issues/44571)
- [ ] LangVer diagnostic quality (https://github.com/dotnet/roslyn/issues/45900)
- [ ] nullability analysis: warn on bad user-provided methods (issue https://github.com/dotnet/roslyn/issues/47627)
- [ ] nullability analysis: set property state based on constructor arguments (https://github.com/dotnet/roslyn/issues/44763)
- [ ] probably need some public APIs for detecting record, identifying primary constructor and mapping parameters with properties
- [x] operator== (https://github.com/dotnet/roslyn/issues/46381)
- [x] ToString (https://github.com/dotnet/roslyn/issues/46382)
- [x] attributes on record parameters targeted to parameter (default) or field or property
- [x] parsing with different LangVersions (and document breaking change)
- [x] Disallow declaring members with name "Clone"
- [x] parsing of `record` is conditional on LangVersion ("preview" now and "9" later)
  - [x] `abstract record M(int i, int j);` (parses differently based on LangVersion)
  - [x] `bool record;` (remains a field or local, regardless of LangVersion)
- [x] `Clone` extension method allowed? (no)
- [x] `Clone` with `params` or optional parameters? (no)
- [x] record with custom copy constructor
- [x] out vars in with initializer (verifies scoping and execution order)
- [ ] two copy constructors, one is correct and the other adds params or optional parameter
- [x] verify sequence points
- [x] default values on positional members (`data class Person(string Name = null, decimal height = 0) { }`)
- [x] test type named "@record" (see `TypeNamedRecord_*`)
- [ ] generic or retargeted records
- [ ] can positional `partial record` reiterate its base without providing arguments https://github.com/dotnet/roslyn/pull/44876#discussion_r436069358
- [x] Inherit from a record containing `sealed override <>Clone`
- [x] `record C(Property int) { public int Property { set { } } }` (no getter in user-defined property)
- [x] test IOperation on record base
- [x] test covering user-defined copy ctor without initializer and synthesized copy ctor when System.Object lacks parameter-less constructor.
- [ ] test synthesized copy ctor where base copy ctor produces use-site diagnostic ([comment](https://github.com/dotnet/roslyn/pull/45022#discussion_r438762631)) or has unsupported metadata ([comment](https://github.com/dotnet/roslyn/pull/45022#discussion_r438862580))
- [x] Test caller line number supplied by compiler constructor initialiser based on base arguments (see LocalRewriter.GetCallerLocation, see `AttributesOnPrimaryConstructorParameters_09_CallerMemberName`)
- [ ] Test implementation of SyntaxExtensions.IsInContextWhichNeedsDynamicAttribute in relation to PrimaryConstructorBaseType
- [ ] Test implementation of SyntaxFacts.IsInTypeOnlyContext and SyntaxFacts.IsNamedArgumentName in relation to PrimaryConstructorBaseType
- [ ] Test nullability analysis within base arguments.
- [x] attributes on record (AttributesOnPrimaryConstructorParameters_*)
- [x] modifiers followed by partial (PartialTypes_04_PartialBeforeModifiers)
- [ ] only one partial declaration can have the parameter list (PartialTypes_01, missing from SPEC)
- [x] Can't provide Equals(Base) in source (BaseEquals_05)
- [x] Can't provide Equals(object) in source (ObjectEquals_06)
- [x] scope of positional parameters
- [x] Verify that field initializers on 'partial' records can access primary constructor parameters, even if the lexically containing partial declaration doesn't include a parameter list (see `PartialRecord_ParametersInScopeOfBothParts`)
- [x] ping F# team for records design
- [x] `Deconstruct` and deconstruct (see ` Deconstruct_*`)
- [x] record nested in generic type (see `RecordInsideGenericType`)
- [x] Fix 'error CS8850: A positional record must have both a 'data' modifier and non-empty parameter list' message
- [ ] spec: Explaining what is a "record" type (ie. has a clone method)
- [x] record synthesized property can implement interface (see `InterfaceImplementation`)

Productivity:
- [x] completion for `class`, `data` and `with` (PR https://github.com/dotnet/roslyn/pull/43971)
- [x] display records with `record` keyword
- [x] classification/colorization
- [x] formatting
- [ ] Confirm expected QuickInfo behavior (issue https://github.com/dotnet/roslyn/issues/44556)
- [ ] Rename Tracking (issue https://github.com/dotnet/roslyn/issues/44560)
- [ ] Find All References (issue https://github.com/dotnet/roslyn/issues/44559)
- [x] Change Signature (issue https://github.com/dotnet/roslyn/issues/44558)
- [ ] Add parameter/member
- [ ] go to definition on deconstruction
- [ ] MetadataAsSource (issue https://github.com/dotnet/roslyn/issues/44566)
- [ ] BCL analyzer "don't use lower-case names for types"
- [ ] recommended casing for positional parameters
- [x] FAR on user-defined `Clone()` method (not applicable since unspeakable)
- [ ] completion for `in` but not `ref`/`out`/`this` in record parameters

## `with` expressions

- [ ] ref safe-to-escape
- [ ] disallow as expression-statement (https://github.com/dotnet/roslyn/issues/44688)
- [ ] semantic model on `with` expression (get the `Clone()` method)
- [ ] `with` on a ref local
- [x] `GetSymbolInfo` on the properties inside a `with` (see `WithExpr28_WithAwait`)
- [x] data flow in `with` (see `TestWithExpression`)
- [x] `with` on TRecord (fixed)
- [x] `_ = tRecordAndInterface with { /* try to set interface members */ };` (fixed)
- [x] `with` expression on `dynamic` type (disallow, see `WithExpr24_Dynamic`)
- [x] should `Obsolete` on record type carry over to synthesized methods? (no)
- [x] test in exception filter (see `WithExpr27_InExceptionFilter`)
- [x] `await` inside a `with` (see `WithExpr28_WithAwait`)
- [x] test `new Person() with { First = null, First = null }` (WithExpr_NullableAnalysis_*)
- [x] should we consider going even one step further and parsing `with` initializers with kind = `ObjectInitializerExpression` instead of `WithInitializerExpression`? (done)
- [x] `OperationCloner` and CFG should support `with` expressions (added `IWithOperation`)
- [x] block `with` in expression trees (`TestInExpressionTree`)
- [x] IOperation/CFG for `with` expression ([PR](https://github.com/dotnet/roslyn/pull/44712))

## init only

Speclet: https://github.com/dotnet/csharplang/blob/master/proposals/init.md

- [x] add `IsExternalInit` ([API request](https://github.com/dotnet/runtime/issues/34978), [PR](https://github.com/dotnet/runtime/issues/34978))
- [x] Allow setting from attribute (issue https://github.com/dotnet/csharplang/pull/3425)
- [x] VB
- [x] ping F# team
- [x] HaloFour's comment on modreqs: https://github.com/dotnet/csharplang/issues/3323#issuecomment-616005297 and https://github.com/dotnet/csharplang/issues/3376 (confirmed metadata encoding with LDM)
- [x] Address remaining PROTOTYPE comments

Productivity:
- [x] recommend the keyword (PR https://github.com/dotnet/roslyn/pull/43865)
- [x] generate implementations and overrides with the init accessor (PR https://github.com/dotnet/roslyn/pull/44077)
- [x] FAR on the accessor (verified in https://github.com/dotnet/roslyn/pull/43865)
- [x] hide the modreq from MetadataAsSource and generated syntax (verified in https://github.com/dotnet/roslyn/pull/44077)
- [x] analyzer to upgrade LangVersion when a method returns type named `record` ([exists](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1709?view=vs-2019))

API:
- [x] Confirm behavior of `IsInitOnly` on `static int Property { init { } }`
- [x] Confirm name of API (`IsInitOnly`) and feature in spec

## `data` properties (out of scope for C# 9)

- [ ] Test that analyzer events are created/received for the symbol and the initializer pieces
- [ ] IOperation test for the initializer
- [ ] allow `sealed` modifier (LDM 7/6/2020)

**Comment by PathogenDavid** [comment]
> * `ToString`: can we deal with stack overflow potential?

`Equals` and `GetHashCode` too. Basically all of the synthesized methods can overflow the stack due to infinite recursion if there's a reference cycle.

Here's a simplified example of where I ran into this while experimenting with using records: ([SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQZuhAnABSZwDuABACoISZQA2E8AJgBE4AYx7sYASwD2mGgEo5AbjIUAzEwQipCPq3ace/IaIjjpmMgG8yTW01zq2HbrziCRY3uaYB5BBIBzCUwILiZLJgC4GEUmAF8mAHpEpgBlODgwYICuAE8mYMwpYThMGA04ADNEUpKmGCl6gAs4Jm1A4NCCzhgOEps7B3tCAAYmADkIMFaIqJjuiXm4gdsV7vgEELCnA1d3EzMZeTW7JgBeAD5ffyCt8+aJKGVSZfJSEOmoAAcIOsoAOgASlhJNN/gBhKRgL4SLiIdIIABuEhKUHC9nUBCYAEkoABRAAeGy22Mwi3RCVeQA))

```csharp
public record TranslatedDeclaration
{
    public TranslatedDeclaration Original { get; } // Seemingly innocent reference to the original instance
    public string Name { get; init; }
    
    internal TranslatedDeclaration()
        => Original = this;
}
```

(The idea here is that external consumers can create variants of `TranslatedDeclaration` but there's always a reference to the original, unmodified version available.)

------

Not sure what (if anything) the compiler can really do about this except maybe emit a warning if it detects the potential for a cycle to form.

Although such a warning wouldn't be especially actionable beyond removing the potential cycle without some ability to customize the synthesized methods beyond implementing them all manually. (At which point records basically become glorified classes-with-`with`-support.)

It may just be that records-with-cycles becomes an anti-pattern to be avoided, but I do feel like it's significantly easier to bump into this problem compared to similar ones when you're implementing things manually.

**Comment by tmat** [comment]
@PathogenDavid Filed https://github.com/dotnet/roslyn/issues/48646.

**Comment by PathogenDavid** [comment]
@tmat Thanks! Gave that issue a follow.

**Comment by uxsoft** [comment]
Hmm, I'm not sure if this is a good place to mention this, but positional records don't work with System.Text.Json deserialization because they "miss a parameterless constructor". It seems very important to add functionality to System.Text.Json to be able to deserialize positional records as I reckon that will be a pretty regular use-case. At least it is for me.

**Comment by PathogenDavid** [comment]
@uxsoft 
[dotnet/runtime](https://github.com/dotnet/runtime) is probably a better place for that, but have you tried recently?

I believe the issue you're talking about is https://github.com/dotnet/runtime/issues/38539 which was fixed in https://github.com/dotnet/runtime/pull/38959

It's working fine for me on RC2:

```csharp
using System;
using System.Text.Json;

Console.WriteLine("Hello World!");
Person david = new("David", "Maas");
Console.WriteLine($"Record: {david}");

string json = JsonSerializer.Serialize(david);
Console.WriteLine($"Serialized: {json}");

Person david2 = JsonSerializer.Deserialize<Person>(json);
Console.WriteLine($"Deserialized: {david2}");

record Person(string FirstName, string LastName);
```

Output:

```
Hello World!
Record: Person { FirstName = David, LastName = Maas }
Serialized: {"FirstName":"David","LastName":"Maas"}
Deserialized: Person { FirstName = David, LastName = Maas }
```

**Comment by jcouv** [comment]
We have individual issues tracking follow-up work. Closing this umbrella issue
