### ISSUE TITLE
Remaining work for C# 9 pattern-matching changes

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#41502]
The following is the remaining work items not yet implemented for the C# 9 pattern-matching changes described in https://github.com/dotnet/csharplang/issues/2850

- [x] Update license comments in recently added files on the branch. (https://github.com/dotnet/roslyn/pull/41503)
- [x] Support relational patterns for `decimal`. (https://github.com/dotnet/roslyn/pull/41697)
- [X] In the decision DAG builder, collapse states that have identical behavior so that the generated decision dag is simpler in some cases. (https://github.com/dotnet/roslyn/pull/42012)
- [x] In an `and` pattern, use the type from the left as the input type for the right.  This requires some spec work.
- [x] Overhaul the lowering of the is-pattern expression to support `or`, `not`, etc.
- [x] Improve lowering (code gen) for a sequence of relational pattern tests.  See https://github.com/dotnet/roslyn/issues/42054
- [X] The semantic model is not yet supported for relational operators (https://github.com/dotnet/roslyn/pull/42357)
- [X] IOperation not yet supported for the new forms. (https://github.com/dotnet/roslyn/pull/42474)
- [X] CFG for new pattern forms (https://github.com/dotnet/roslyn/pull/42548)
- [x] For the *type pattern*, we can give the same set of warnings as we do for the *is type* expression.
- [x] Implement single-element ITuple-based positional pattern (once the open issue is resolved)
- [x] Additional testing (see https://github.com/dotnet/roslyn/issues/40727)
- [x] Document the "breaking" change around completeness for enumerated `byte` and `sbyte` switches. (https://github.com/dotnet/roslyn/pull/42632)
- [x] Are formatter changes required?
- [x] Document breaking change: `not` is considered a type in C# 8 and a pattern in C# 9. (https://github.com/dotnet/roslyn/pull/42632)
- [x] Document breaking change: `and` and `or` are allowed as variable names in C# 8, but are pattern combinators in C# 9. (https://github.com/dotnet/roslyn/pull/42632)

## Open Issues
- [x] What is the *narrowed type* for a  for an `or` pattern? The current spec (common type) doesn't work as the common type permits representation-changing conversions (e.g. for `int or long`).
- [ ] Is `e is dynamic` a "pure" null check? [See #40960 ; not a pattern-matching issue]

**Comment by alrz** [comment]
>What syntactic forms are permitted for an ITuple-based recursive pattern, and how would you write a single-element ITuple-based pattern? There is no way to do it currently.

To my surprise, both of these [work already](https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUA9gEYBWApgMYAuitAlJtrlwG4CGATogAeABkQBeFogCWAZ0SlpAO2bTWAfQDcnLjj6ChECVLmJ9pIa20wuAX1i2gA===).
```cs
var x0 = obj is (int i) _;
var x1 = obj is var (x);
```

**Comment by gafter** [comment]
@alrz Then I have to make sure they continue to work.

**Comment by gafter** [comment]
@alrz I was concerned about this not working:
```csharp
_ = o is (int) _;
```
This does not work because the right-hand-side is interpreted as a *cast expression*, which casts `_` to the type `int`.  You would have to write this
```csharp
_ = o is (int _) _;
```
which [does work](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAdYwggdsgZgBoYQBLAGyIBMQBqAHwAEAmAAgGE2BvAWACg2QtkwAsbALIAKAPbAAVhADGMNjICUPAcJ1sA+mwC8atmWRspZXKr2a9Abm3CAvgOdA===).

**Comment by alrz** [comment]
FWIW, another way to disambigute would be `o is ((int)) _`
Rare but this will also work if we had named constants: `o is ((constant)) _`
