### ISSUE TITLE
Move Solution Crawler OOP

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#42181]
Depends on

- [x] https://github.com/dotnet/roslyn/issues/42176: Revisit RenameTrackingDiagnosticAnalyzer to unblock moving analyzers OOP
- [x] https://github.com/dotnet/roslyn/issues/42185: Move CodeModelIncrementalAnalyzerProvider to OOP
- [x] https://github.com/dotnet/roslyn/issues/42186: Move DesignerAttributeIncrementalAnalyzer OOP
- [x] https://github.com/dotnet/roslyn/issues/42188: Move TodoCommentIncrementalAnalyzerProvider OOP 
- [x] https://github.com/dotnet/roslyn/issues/42793: Move SemanticChangeNotificationService OOP
- [x] https://github.com/dotnet/roslyn/issues/42794: Move ProjectTelemetryIncrementalAnalyzer OOP
- [x] https://github.com/dotnet/roslyn/issues/41127: Add host provided analyzers to solution snapshot
- [ ] https://github.com/dotnet/roslyn/issues/42187: Remove UnitTestingIncrementalAnalyzer
- [x] https://github.com/dotnet/roslyn/issues/42179: Move Edit and Continue analyzer OOP
- [ ] https://github.com/dotnet/roslyn/issues/42183: Move XamlDocumentDiagnosticAnalyzer to OOP
- [ ] Diagnostics to be moved to LSP 

Removing side channels used by diagnostic analyzers:
- [x] https://github.com/dotnet/roslyn/issues/41127: Add host provided analyzers to solution snapshot
- [ ] https://github.com/dotnet/roslyn/issues/42796: Analyzer load exception reporting OOP

**Comment by tmat** [comment]
FYI @jinujoseph

**Comment by CyrusNajmabadi** [comment]
@tmat can likely close this out.
