### ISSUE TITLE
Test plan for nullable annotations on unconstrained type parameters

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#44578]
See initial PR https://github.com/dotnet/roslyn/pull/45993

- [x] draft [spec](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/unconstrained-type-parameter-annotations.md) on dotnet/csharplang
- [x] language version errors for `T?` and `where T : default`
- [x] nullability of `default(T)` and `default(T?)`
- [x] nullability of `var`: `var t = new T();` https://github.com/dotnet/roslyn/issues/46236
- [x] nullability of `(T?)t`
- [x] nullability of `(T)default(T)`
- [x] interop with `T` from outside nullable context: see `UnconstrainedTypeParameter_45`, `_46`
- [x] `T?` outside nullable context
- [x] `T?` with no constraints, with `class?` constraint, with `notnull` constraint
- [x] `T?` as type argument
- [x] `T?` as constraint
- [x] `T?` substituted with `U` or `U?` `where U : { T, T?, class, class?, struct, notnull }`
- [x] `T?` in variance
- [x] `T?` in method type inference
- [x] `T?` in lambda return type inference
- [x] `T?` and `T` in best common type
- [x] `T?` in `ref` types
- [x] `T?` in `out` parameters: see `UnconstrainedTypeParameter_47`, https://github.com/dotnet/roslyn/issues/49131
- [x] `T?` in `ref` parameters
- [x] `T?` in type argument constraint checks
- [x] `T?` with `[AllowNull]`, `[MaybeNull]`: see `UnconstrainedTypeParameter_16`
- [x] `T?` with `[DisallowNull]`, `[NotNull]`: see `UnconstrainedTypeParameter_41`, `_42`
- [x] ~~non-safety warnings for assignment or explicit cast of `T?` to `T`~~ https://github.com/dotnet/roslyn/issues/46044
- [x] conversions from `U` or `U?` to `T` or `T?` `where U : { T, T? }` https://github.com/dotnet/roslyn/issues/46150
- [x] `default` constraint on method overrides and explicit implementations
- [x] `default` constraint on other methods
- [x] `default` constraint combined with other constraints
- [x] `default` constraint required to treat `T?` as unconstrained
- [x] overrides that differ by `default` and `struct` constraints
- [x] overrides that differ by `default` and other constraints { `class`, `class?`, `notnull`, `I`, `I?` }
- [x] overrides that differ by `T` and `T?`: see `UnconstrainedTypeParameter_09`, `_10`
- [x] `T?` consumed in C#8
- [x] `T?` consumed in C#8 with `[AllowNull]`, `[MaybeNull]`
- [x] overrides and implementations with `T?` and `[MaybeNull]T`, etc.
- [x] symbol display of `T?` and `IEnumerable<T?>`
- [ ] symbol display of method with `where T : default` constraint
- [x] unassigned fields of type `T` and `T?`
- [x] annotations from `GetDeclaredSymbol()`
- [x] flow state from `GetSymbolInfo()` on a method re-inferred with `T?`
- [ ] flow state from `IOperation` on a method re-inferred with `T?`

Productivity:
- [ ] check publicAPI analyzer on `T?`
- [x] recommend `default` keyword
- [ ] UseExplicitType
