### ISSUE TITLE
[LSP] Support classification protocol

### ISSUE THREAD

**Issue by dibarbet** [dotnet/roslyn#46052]
We should migrate the custom handling of classifications from our [custom liveshare implementation](http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices.LiveShare/AbstractClassificationsHandler.cs,4924c3bb12db73ea) to the proper [LSP protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_semanticTokens).

There are a few work items that need to be completed.

- [x] [DavidW] Order messages in the LSP server correctly - https://github.com/dotnet/roslyn/issues/46051
- [ ] [External] Support for custom token types in the VS LSP client - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1085998 / #46582
- [x] [DavidW] Use LSP text synchronization instead of text buffer synchronization - https://github.com/dotnet/roslyn/issues/45427
- [x] [Allison] Implement support for the LSP semantic tokens and remove the custom roslyn implementation (this issue)

**Comment by CyrusNajmabadi** [comment]
> In LiveShare specifically, there's a series of race conditions that can cause the LiveShare guests or CodeSpaces client's colors to get out of sync if the user types quickly enough, even if the source LSP server is 100% correctly synchronized.

😱

**Comment by gundermanc** [comment]
>😱

Just in case it wasn't clear, this has been mitigated for the [time being](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FRemoteLanguage%2FImpl%2FFeatures%2FSemanticTokens%2FTagger%2FSemanticTokensDocumentClassificationTagger.cs&version=GBdevelop). Talks are in progress to get this fixed.

**Comment by allisonchou** [comment]
Since #46582 tracks support for custom token types (the last remaining work item in this issue), will close out this issue.
