### ISSUE TITLE
[loc] Please lock all strings that shouldn't be localized.

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn#48364]
This request is from https://github.com/dotnet/roslyn/issues/39286.
Several strings were not locked, as result, the translation was applied on them.
Could you please apply commenting and lock them?

### **\*.resx**

* [ ] src/Analyzers/CSharp/Analyzers/CSharpAnalyzersResources.resx
* [ ] src/Analyzers/CSharp/CodeFixes/CSharpCodeFixesResources.resx
* [ ] src/Analyzers/Core/Analyzers/AnalyzersResources.resx
* [ ] src/Analyzers/Core/CodeFixes/CodeFixesResources.resx
* [ ] src/Analyzers/VisualBasic/Analyzers/VisualBasicAnalyzersResources.resx
* [ ] src/Analyzers/VisualBasic/CodeFixes/VisualBasicCodeFixesResources.resx
* [x] src/CodeStyle/CSharp/Analyzers/CSharpCodeStyleResources.resx (no change needed)
* [x] src/CodeStyle/CSharp/CodeFixes/CSharpCodeStyleFixesResources.resx (#48416)
* [ ] src/CodeStyle/Core/Analyzers/CodeStyleResources.resx
* [x] src/CodeStyle/Core/CodeFixes/CodeStyleFixesResources.resx (#48416)
* [x] src/CodeStyle/VisualBasic/Analyzers/VBCodeStyleResources.resx (#48416)
* [x] src/CodeStyle/VisualBasic/CodeFixes/VBCodeStyleFixesResources.resx (#48416)
* [ ] src/Compilers/CSharp/Portable/CSharpResources.resx
* [ ] src/Compilers/CSharp/Test/Syntax/Resources.resx
* [ ] src/Compilers/Core/CodeAnalysisTest/Resources.resx
* [ ] src/Compilers/Core/MSBuildTask/ErrorString.resx
* [ ] src/Compilers/Core/Portable/CodeAnalysisResources.resx
* [ ] src/Compilers/VisualBasic/Portable/VBResources.resx
* [ ] src/EditorFeatures/CSharp/CSharpEditorResources.resx
* [ ] src/EditorFeatures/Core.Wpf/EditorFeaturesWpfResources.resx
* [ ] src/EditorFeatures/Core.Wpf/Interactive/InteractiveEditorFeaturesResources.resx
* [ ] src/EditorFeatures/Core/EditorFeaturesResources.resx
* [ ] src/EditorFeatures/Text/TextEditorResources.resx
* [ ] src/EditorFeatures/VisualBasic/VBEditorResources.resx
* [ ] src/EditorFeatures/VisualBasicTest/Formatting/XmlLiterals.resx
* [ ] src/ExpressionEvaluator/Core/Source/ResultProvider/Portable/Resources.resx
* [ ] src/ExpressionEvaluator/VisualBasic/Source/ExpressionCompiler/Resources.resx
* [ ] src/Features/CSharp/Portable/CSharpFeaturesResources.resx
* [ ] src/Features/Core/Portable/FeaturesResources.resx
* [ ] src/Features/VisualBasic/Portable/VBFeaturesResources.resx
* [ ] src/Interactive/Host/InteractiveHostResources.resx
* [ ] src/Scripting/CSharp/CSharpScriptingResources.resx
* [ ] src/Scripting/Core/ScriptingResources.resx
* [ ] src/Scripting/VisualBasic/VBScriptingResources.resx
* [ ] src/Test/Utilities/Portable/TestResource.resx
* [ ] src/Tools/ExternalAccess/FSharp/ExternalAccessFSharpResources.resx
* [ ] src/VisualStudio/CSharp/Impl/CSharpVSResources.resx
* [ ] src/VisualStudio/CSharp/Impl/VSPackage.resx
* [ ] src/VisualStudio/CodeLens/CodeLensVSResources.resx
* [ ] src/VisualStudio/Core/Def/ServicesVSResources.resx
* [ ] src/VisualStudio/Core/Def/VSPackage.resx
* [ ] src/VisualStudio/Core/SolutionExplorerShim/SolutionExplorerShim.resx
* [ ] src/VisualStudio/IntegrationTest/TestSetup/IntegrationTestServicePackage.resx
* [ ] src/VisualStudio/VisualBasic/Impl/BasicVSResources.resx
* [ ] src/VisualStudio/VisualBasic/Impl/VSPackage.resx
* [ ] src/VisualStudio/VisualStudioDiagnosticsToolWindow/Resources.resx
* [ ] src/VisualStudio/VisualStudioDiagnosticsToolWindow/VSPackage.resx
* [x] src/VisualStudio/Xaml/Impl/Resources.resx (#48416)
* [x] src/Workspaces/CSharp/Portable/CSharpWorkspaceResources.resx (#48416)
* [x] src/Workspaces/Core/MSBuild/WorkspaceMSBuildResources.resx (#48416)
* [x] src/Workspaces/Core/Portable/WorkspacesResources.resx (#48416)
* [x] src/Workspaces/Remote/Core/RemoteWorkspacesResources.resx (#48416)
* [x] src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CSharpCompilerExtensionsResources.resx (#48416)
* [x] src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/CompilerExtensionsResources.resx (#48416)
* [x] src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/VisualBasicCompilerExtensionsResources.resx (#48416)
* [x] src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/CSharpWorkspaceExtensionsResources.resx (#48416)
* [x] src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensionsResources.resx (#48416)
* [x] src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/VisualBasicWorkspaceExtensionsResources.resx (#48416)
* [x] src/Workspaces/VisualBasic/Portable/VBWorkspaceResources.resx (#48416)

### **\*.vsct**

* [ ] src/VisualStudio/CSharp/Impl/Interactive/Commands.vsct
* [ ] src/VisualStudio/Core/Def/Commands.vsct
* [ ] src/VisualStudio/IntegrationTest/TestSetup/IntegrationTestServiceCommands.vsct
* [ ] src/VisualStudio/VisualStudioDiagnosticsToolWindow/VisualStudioDiagnosticsWindow.vsct

**Comment by sharwell** [comment]
@cristianosuzuki77 What is the expected syntax for locking? It is easy for us to maintain these comments in new strings as long as the available syntax is documented.

**Comment by cristianosuzuki77** [comment]
Inside the trans-unit, add {Locked} to the <note> element to lock the entire string or {Locked="lorem ipsum"} if you just want to lock the substring "lorem ipsum" from the entire string.
Eg:
<trans-unit id="AddLaunche">
        <source>'addlauncher' command to the path.</source>
        <target state="new">'addlauncher' command to the path.</target>
        <note>{Locked}</note>
      </trans-unit>
or

<trans-unit id="AddLaunche">
        <source>'addlauncher' command to the path.</source>
        <target state="new">'addlauncher' command to the path.</target>
        <note>{Locked="addlauncher"}</note>
      </trans-unit>

**Comment by sharwell** [comment]
@cristianosuzuki77 Thanks, that's _super_ helpful! I have also seen some request for clarification of placeholders (e.g. `{0}`). Is there a syntax we can use to document those, or should we just respond to those if/when they are raised during translation?

**Comment by cristianosuzuki77** [comment]
The <note> can be used for adding explanations of placeholders or of any other contextual information that will help localization.

**Comment by cristianosuzuki77** [comment]
Sorry, the "note" tag can be used for adding explanations of placeholders or of any other contextual information that will help localization.
