### ISSUE TITLE
Test plan for "record structs"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#51199]
Championed issue: https://github.com/dotnet/csharplang/issues/4334
Spec: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-10.0/record-structs.md

Relates to parameterless ctor and field initializers in structs: https://github.com/dotnet/csharplang/issues/99

## Compiler

- [x] Syntax tests
  - [x] 'record' 'struct'
  - [x] 'record' 'class'
  - [x] Appropriate language version checks are in place
  - [ ] Etc.
- [ ] Type kind, validate Record Struct is a struct and has treatment appropriate to a struct
  - [ ] 'default'
  - [ ] Creation 
  - [x] Generic constraint checks (see `TypeDeclaration_IsStruct_InConstraints`, `TypeDeclaration_IsStruct_Unmanaged`)
  - [x] Derives from ValueType (see `TypeDeclaration_IsStruct`)
  - [ ] Etc.
- [x] Record struct members
  - [x] A member named "Clone" is disallowed (see `Clone_DisallowedInSource`)
  - [x] A field inside a Record Struct cannot have an unsafe type (see `RestrictedTypesAndPointerTypes`)
  - [x] Destructors are not allowed (see `TypeDeclaration_NoDestructor`)
  - [x] Equality members (explicit declaration / implicit declaration and code generation)
    - [x] `Equals` for this type (see `Equality_xy`)
    - [x] `Equals` for `object` type (see `Equality_01` and `ObjectEquals_06` for user-defined)
    - [x] `GetHashCode` (see `RecordEquals_xy`, `GetHashCode_UserDefined`
    - [x] `==` and `!=` operators for this type (see `EqualityOperators_xy`)
  - [x] Printing members (explicit declaration / implicit declaration and code generation) 
    - [x] `PrintMembers`
    - [x] `ToString`
  - [x] Primary Constructor
    - [x] Parameter-less Primary Constructor is disallowed (see `RecordProperties_01_EmptyParameterList`, `TypeDeclaration_NoParameterlessConstructor`, `TypeDeclaration_NoInstanceInitializers`)
    - [x] Test a signature conflict with an explicitly declared constructor (see `RecordProperties_02`)
    - [x] Any user-defined constructor must have an explicit `this` constructor initializer. (see `RecordProperties_02`)
    - [x] A warning is produced if a parameter of the primary constructor is not read. (see `RecordProperties_03`)
    - [ ] The definite assignment rules for struct instance constructors apply to the primary constructor of record structs.
    - [x] XML Doc comments on the type declaration can be used to document parameters and can refer to the parameters (see `XmlDoc`)
  - [x] Positional struct members
    - [x] Conditionally synthesized based on Primary Constructor's signature
    - [x] A public `get` and `init` auto-property is created if the record struct has `readonly` modifier, `get` and `set` otherwise. (see `RecordProperties_01_Readonly`)
    - [x] The auto-property is initialized to the value of the corresponding primary constructor parameter. (see `RecordProperties_01`)
    - [x] Attributes can be applied to the synthesized auto-property and its backing field by using property: or field: targets for attributes syntactically applied to the corresponding record struct parameter. (see `AttributesOnPrimaryConstructorParameters_01`)
    - [ ] Etc.
  - [x] Deconstruct
    - [x] Synthesized for a positional record struct with at least one parameter, unless explicitly declared
  - [x] Instance field initializers 
    - [x] Parameters of the primary constructor as well as members of the record struct are in scope within initializers of instance fields or properties. Instance members would be an error in these locations
    - [x] If there is a Primary Constructor, only the primary constructor executes the instance initializers appearing in the record-struct-body.
    - [x] If there is no primary constructor, the instance initializers execute as part of the parameter-less constructor.
    - [x] We have an open design issue around instance initializers in record structs which we should close on, perhaps under umbrella of "Parameter-less struct constructors" feature.
- [x] `with` expression on structs
  - [x] Test on regular struct instances
  - [x] Test in generic context on type parameters with appropriate constraints
- [x] Allow user-defined positional members of records to be fields
  - [x]  Appropriate language version checks are in place
  - [ ] Etc.
- [x] SemanticModel around new syntax
- [x] IOperation around new syntax
- [x] Analyzer actions around new syntax and new members
- [x] SymbolDisplay

## Work items
- [x] parameters less primary constructor, including field initializers (tracking issue https://github.com/dotnet/roslyn/issues/52240)
- [ ] Consider improving parsing recovery of `struct Point(int x, int y);`
- [ ] Consider improving parsing error for `record interface C(int X, int Y);` (`RecordInterfaceParsing`)
- [x] LDM: Emitting GetHashCode and Equals as `readonly` (conditionally) (answer: yes, issue https://github.com/dotnet/roslyn/issues/54419)
- [x] `left` and `right` parameter names in equality/inequality operators (PR https://github.com/dotnet/roslyn/pull/52236)
- [x] `with` on structs (PR https://github.com/dotnet/roslyn/pull/52319)
- [x] allowing record positional members to be implemented as fields (PR https://github.com/dotnet/roslyn/pull/52480)
- [x] take C# 9 compat break on hidden positional members (tracking issue https://github.com/dotnet/roslyn/issues/52630)
- [x] `with` expressions on anonymous types (PR https://github.com/dotnet/roslyn/pull/53248)
- [x] SyntaxNormalizer
- [x] public API: metadata scenario for `IsRecord` (tracking issue https://github.com/dotnet/roslyn/issues/52233, PR https://github.com/dotnet/roslyn/pull/52256)
- [x] LDM: Should records implement `ISpanFormattable`? (answer: no)
- [x] LDM: Should `ToString`/`PrintMembers` use `InterpolatedStringBuilder`? ([discussion](https://github.com/dotnet/roslyn/discussions/52975)) (answer: no)
- [x] LDM: Confirm we'll allow parameterless primary constructor (answer: yes)
- [x] LDM: What about initializers when no primary constructor? (question relates to parameterless constructors in structs)
- [x] LDM: Confirm that `Equals(R)` API doesn't need `in` (answer: we won't add `in` overloads, too heuristic-dependant)
- [x] LDM: Confirm `with` on generic structs (did we have LDM notes and/or decision already? current behavior is fine )
- [x] LDM: Confirm whether `GetHashCode` should include a hash of the type (this isn't needed per email thread, current behavior is fine)
- [x] LDM: Confirm whether property should come first, or field from current type should come before property from base
- [x] remove PROTOTYPE markers
- [x] EnC: https://github.com/dotnet/roslyn/issues/51200

## Productivity
- [x] completion (done in https://github.com/dotnet/roslyn/pull/51304)
- [x] formatting
- [x] Intellisense
- [x] QuickInfo (PR https://github.com/dotnet/roslyn/pull/52455)
- [x] Should appear correctly in solution explorer. (see https://github.com/dotnet/roslyn/pull/48451/ where this was done for C# 9.0 records)
- [x] Also name suggestion for positional parameters should be PascalCased. (see https://github.com/dotnet/roslyn/pull/48329)
- [x] Also destructor intellisense. (see https://github.com/dotnet/roslyn/pull/48297)
- [x] Also navigation. (see https://github.com/dotnet/roslyn/pull/48116)
- [x] Make type abstract. (see https://github.com/dotnet/roslyn/pull/48227)
- [x] FAR works like for record classes
- [x] record structs in help service (similar to #46343)
- [x] Complete statement command will need to handle the new RecordStructDeclarationSyntax node. (see https://github.com/dotnet/roslyn/pull/48128)
- [ ] CodeLens support (issue https://github.com/dotnet/roslyn/issues/52430)
- [x] GoToTypes support (issue https://github.com/dotnet/roslyn/issues/51672)
- [ ] Make sure that explicit `PrintMembers` isn't reported as unused by IDE analyzers. See https://github.com/dotnet/roslyn/issues/52421
- [x] attribute target completion (see issue https://github.com/dotnet/roslyn/issues/51756)
- [ ] Add ConvertTupleToRecordStruct
- [x] IDE to handle xml docs (PR https://github.com/dotnet/roslyn/pull/52737 for records)

**Comment by Youssef1313** [comment]
Have the implementation of the feature started?

**Comment by jcouv** [comment]
It's about to

**Comment by Youssef1313** [comment]
- Complete statement command will need to handle the new RecordStructDeclarationSyntax node. (see https://github.com/dotnet/roslyn/pull/48128)

**Comment by jcouv** [comment]
PR https://github.com/dotnet/roslyn/pull/52261 added the coverage and fixes suggested by @Youssef1313. Thanks!
I'll do some manual validation in next few days.

**Comment by Youssef1313** [comment]
One more minor scenario:

- Make sure that explicit `PrintMembers` isn't reported as unused by IDE analyzers. See https://github.com/dotnet/roslyn/issues/52421

**Comment by Youssef1313** [comment]
One more scenario: https://github.com/dotnet/roslyn/issues/51756. I've a fix for it for records in #51760. A similar fix for record structs will be needed.

**Comment by Youssef1313** [comment]
@jcouv `Make type abstract.` is marked as done, but it doesn't seem to.

**Comment by jcouv** [comment]
@Youssef1313 MakeTypeAbstract  is "done" because a test was added, but purposefully not supporting because structs can't be abstract.

**Comment by Youssef1313** [comment]
@jcouv Can you add handling record structs in help service to the original issue? This is something that should be done a little bit late (after a doc page is created in dotnet/docs with f1_keywords `recordstruct_CSharpKeyword`). This will be similar to https://github.com/dotnet/roslyn/pull/46343. Thanks.

**Comment by jcouv** [comment]
@Youssef1313 Added. Thanks

**Comment by jcouv** [comment]
Remaining issues are tracked as separate issues (linked). I'll go ahead and close this.
