### ISSUE TITLE
Test Plan for "List Patterns"

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#51289]
Championed issue: https://github.com/dotnet/csharplang/issues/3435
Specification: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/list-patterns.md

## Compilers

Work items:
* [x] refactoring and PROTOTYPE markers (PR https://github.com/dotnet/roslyn/pull/57318)
* [ ] EnC

Scenarios:
* [x] Check of building VS/runtime repo
* [x] Need to test ref escape, such as indexer returning by ref instead of by value
* [x] Verify symbols/PDB
* [x] Update the test plan with new patterns
* [x] `inputIsCountable is INotCountable and [..]` (see `ListPattern_NotCountableInterface`)
* [x] `inputHasExplicitIListImplAndIsNotListPatternable is IList and [..]` (see `ListPattern_ExplicitInterfaceImplementation`)
* [x] LangVer
* [x] Spec checked in ([PR](https://github.com/dotnet/csharplang/pull/3245/files))
* [ ] Static indexer, inaccessible indexer or accessor, missing getter, `void` or `string` returning `Length`, `ref`/`in` parameters
  * [ ] list pattern on type with `this[Index i]` indexer
  * [ ] list pattern on type with `this[Index i, int ignored = 0]` indexer
  * [ ] list pattern on type with `this[int i, int ignored = 0]` indexer
  * [ ] slice pattern on type with `this[Range r]` indexer
  * [ ] slice pattern on type with `this[Range r, int ignored = 0]` indexer
  * [ ] slice pattern on type with `this[int start, int end, int ignored = 0]` indexer
  * [ ] real indexers preferred over implicit indexers
  * [x] extensions ignored (see `SlicePattern_ExtensionIgnored`)
  * [x] `Length` field doesn't count (see `ListPattern_LengthFieldNotApplicable`)
* [x] verify IL for list and slice patterns on `string` and array types (ranges spec calls out special cases for those, see `ListPattern`)
* [x] verify order of evaluation
* [x] verify that properties/indexers are only read once per DAG
* [x] verify NormalizeWhitespaces (see `TestNormalizeListPattern_*`)
* [x] `this[params Range[] p]` (see `ListPattern_Range`)
* [x] `this[params Index[] p]` (see `ListPattern_Index`)
* [x] `this[params int[] p]` (see `ListPattern_Index`)
* [x] `this[long p]` (see `ListPattern_MemberLookup_Index_ErrorCases_4`)
* [x] `Slice(int start, int end, int ignored = 0)` (invalid, see `ListPattern_MemberLookup_Range_ErrorCases_3`)
* [x] `this[int start, int end, int ignored = 0]` (invalid, see `ListPattern_MemberLookup_Index_ErrorCases_3`)
* [x] In short, we should cover anything that is valid with `expr[N]` or `expr[^N]` or `expr[N..^M]` (using either explicit or implicit indexer pattern) but not any other.
* [x] CallerInfo, optional parameters, params (see `ListPattern_CallerInfo`, `ListPattern_Index`)
* [x] Missing or obsolete types or members (property, accessor, ...) (see `ListPattern_ObsoleteMembers`, `ListPattern_ObsoleteAccessors`, `ListPattern_IndexAndSliceReturnMissingTypes`
  * [x] `Index` and `Range` are required but optimized away (see `ListPattern_IndexAndRangeAreNecessaryButOptimizedAway`)
* [x] Accessor from base (see `IndexerOverrideLacksAccessor`)
* [x] Misplaced slice pattern (see `SlicePattern_Misplaced`)
* [x] Fallback from inaccessible `this[Index]` or `this[Range]` indexer (see `ListPattern_MemberLookup_Fallback_InaccessibleIndexer`)
* [x] `ref` returning indexers (see `ListPattern_RefReturns`)
* [x] list-pattern and `Length` property checks interact (see `Pattern_Nullability_Exhaustiveness`)
* [x] break with `is { Length: -1 }` or `{ Count: -1 } but not both (see `ListPattern_LengthAndCountAreOrthogonal`)
* [x] effect of missing `Index` type on break (see `LengthPattern_NegativeLengthTest_MissingIndex`)
* [x] subsumption and exhaustiveness checking (see spec) (PR https://github.com/dotnet/roslyn/pull/53891)
  * [x] `switch { [<10] => ..., [>10] => ...}` (should warn)
  * [x] `[0, ..] => ..., [.., not 0] => ..., [var unreachable] => ...`, `[null, ..] => ..., [.., not null] => ..., [var unreachable] => ...`
  * [x] list-pattern nested in slice `[0] => ..., [..[not 0]] => ..., [var unreachable] => ...`
  * [x] `[1, 2, 3] => ..., [1, .., 3] => ...`
  * [x] no interaction with positional patterns, even on `ITuple` (see `ListPattern_Tuples`)
* [x] Verify that no length or slice calls are emitted for `{ .. }` and `{ .._ }`, and no slice call for `{ 1, 2, .. }`, `{ 1, 2,  ..var unused }` (like for `{ Property: var unused }`) (see `SlicePattern_Subpattern`)
* [x] Verify that we can efficiently use a linked list with `{ var head, ..var tail }` (no)
* [x] Indexer override lacks a get accessor a la https://github.com/dotnet/roslyn/issues/51801#issuecomment-924386405
* [x] Test on tuples (fails) and ITuple (works, but no de-aliasing between positional and list patterns, see `ListPattern_Tuples`)
* [x] explainer ([PR](https://github.com/dotnet/roslyn/pull/55327))
* [x] IOperation and ControlFlowGraph ([PR](https://github.com/dotnet/roslyn/pull/56008))
* [x] val escape ([PR](https://github.com/dotnet/roslyn/pull/57336))
* [x] list-pattern on interface, on nullable value type, on narrowed type (see `ListPattern_NullableValueType`, `ListPattern_ExplicitInterfaceImplementation`)
* [x] `GetDeclaredSymbol` and `GetTypeInfo` on designations (see `ListPattern_Symbols_01`)
* [x] SyntaxNormalizer ([PR](https://github.com/dotnet/roslyn/pull/53850))
* [x] definite assignment (see `SlicePattern_DefiniteAssignment`)
* [x] nullability analysis (`case [var x]:` should give `x` the right annotation/state) (PR https://github.com/dotnet/roslyn/pull/53822)
  * [x] maybe-null receiver (see `ListPattern_Nullability_MaybeNullReceiver`)
  * [x] semantic model for `var` designations (see `ListPattern_Nullability`)
  * [ ] IOperation symbols reflect updated nullability (issue `https://github.com/dotnet/roslyn/issues/57884`)
* [x] subsumption checking for nullability (`case [null, ..]: case [.., not null]: case [var unreachable]:`)
* [x] Downgrade unreachable diagnostic for negative Length check to a warning (see [notes](https://github.com/dotnet/csharplang/issues/5201#issuecomment-926049786), no longer applicable)
* [x] document negative Length break (PR https://github.com/dotnet/roslyn/pull/57149)
* [x] Adjust formatting for slice patterns ([PR](https://github.com/dotnet/roslyn/pull/53850))
* [x] disallowed on `dynamic` receiver (see `ListPattern_Dynamic`)
* [x] disallowed in expression tree (see `ListPattern_ExpressionTree`)

## Language
* [x] LDM: Should list-patterns interact with constant string patterns? (answer: no)
* [x] LDM: Should we use `...` for slice pattern to work better with collection literals? (answer: [no](https://github.com/dotnet/csharplang/blob/main/meetings/2022/LDM-2022-03-09.md))
* [x] SPEC: tweak assumption around slicing and nullability to reflect LDM decision
* [x] clarify spec for evaluation of `..` (no nested pattern) versus `.. <nested pattern>`
* [x] LDM: non-negative assumption should apply to both Count and Length (issue https://github.com/dotnet/csharplang/issues/5137)
* [x] LDM: should we allow indexers and `Slice` methods with `uint`, `nint` and other numeric types to make a type indexable/rangeable? (orthogonal and out-of-scope)
* [x] LDM: can we do something to simplify [safe collection access](https://twitter.com/controlflow/status/1385688833249923075) scenario? `if (index > 0 && index < xs.Count) { var x = xs[index]; DoSmth(x); }` (out-of-scope)
* [x] LDM: confirm plan for IEnumerable (answer: C# 11 timeframe, ideally)
* [x] LDM: confirm plan for indexer/property pattern `{ [0]: ... }` or `{ [var x]: ... }` (answer: separate championed issue)
* [x] LDM: confirm on special `length: ...` pattern (answer: not a thing anymore)
* [x] LDM: confirm that `[ .._ ]` requires a sliceable type, whereas `[ 1, .. ]` doesn't (answer: correct)
* [x] LDM: do we really want a breaking change for `{ Length: -1 }`? (answer: initially we thought we'd reduce the break to a warning, but we went back to taking the break) (https://github.com/dotnet/csharplang/issues/5226)
* [x] LDM: should list- and positional-patterns on `ITuple` interact? ([question](https://github.com/dotnet/csharplang/pull/4982#issuecomment-891256637) and comments below: "Should iTuple switch { (1,2,3) => 1, [1,2,3] => 2, _ => 0 } produce an error? ITuple is both countable and indexable.") (answer: no)
* [x] LDM: confirm formatting for slice pattern (answer: space)
* [x] LDM: various open questions: https://gist.github.com/jcouv/fa62923b3ee36de7f8553d2c1c58ec43
* [x] LDM: when a slice returns a type that is indexable/rangeable, do we assume that well-behaved types have certain consistency of behavior? (see `ListPattern_Exhaustiveness_NestedSlice`) (answer: [yes](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-06-07.md#exhaustiveness))

## IDE

* [x] completion for pattern ([PR](https://github.com/dotnet/roslyn/pull/53850))
* [x] formatting for slice-pattern (`..var` or `.. var`?) ([PR](https://github.com/dotnet/roslyn/pull/53850))
* [x] formatting for length-pattern on array type (`is string[] [>0]`) (not applicable)
* [x] QuickInfo on `..var x` ([PR](https://github.com/dotnet/roslyn/pull/53850))
* [ ] FindAllReferences on `Length`/`Count`/indexers when they're used by list pattern (issue https://github.com/dotnet/roslyn/issues/58190)
* [ ] Add parens for clarity on slices with `and` or `or`
* [ ] Switch common patterns to use list-pattern: `if (expr[0] is pattern1&& expr[^1] is pattern2)`

**Comment by alrz** [comment]
Initial tests are green https://github.com/dotnet/roslyn/blob/95515b557ea35317c077ecef3d2acc70250152f1/src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_ListPatterns.cs

Next steps:
- Flesh out syntax PR after LDM confirmation
- Cover some of the remaining edge cases and add tests
- Refactoring of ForEachBinder against master
- Tidy and open PR for code review
- Covering of the test plan and finalization
- Update PatternExplainer, IOp, etc
- Optimizations

**Comment by alrz** [comment]
A couple of more scenarios to test:

- `this[params Range[] p]`
- `this[params Index[] p]`
- `this[params int[] p]`
- `this[short p]`
- `Slice(int start, int end, int ignored = 0)` (invalid)
- `this[int start, int end, int ignored = 0]` (invalid)

In short, we should cover anything that is valid with `expr[N]` or `expr[^N]` or `expr[N..^M]` (using either explicit or implicit indexer pattern) but not any other.

**Comment by alrz** [comment]
> LDM: can we do something to simplify safe collection access scenario?

Indexer patterns are already mentioned several times in LDM so I think we have a clear understanding on how they should look like. I have a [draft proposal](https://gist.github.com/alrz/cd04f85a793b6c81441b0ba15102c1ca) to address this. Will open an issue in csharplang later if there's interest.

**Comment by Youssef1313** [comment]
Note: Make sure obsoletion errors are correctly reported.

**Comment by alrz** [comment]
Do we want to report a subsumption error here?
```cs
case { .., 1 }:
case { 1, .. }:
```
If so, I'm gonna need to go get more coffee.

**Comment by alrz** [comment]
That was a hypothetical scenario. I think if you do that sorta things you're on your own. Doesn't seem to worth it to cover. 

We already can spot a lot of erroneous cases only by the length value set. That's probably good enough for the program to be correct.

**Comment by jcouv** [comment]
> Do we want to report a subsumption error here?

What would be the error? "The slice is unnecessary"?

**Comment by alrz** [comment]
A better example:
```cs
case {1, .., 4}:
case {1, 2, 3, 4}: 
// ^ error CS8120: The switch case is unreachable. It has already been handled by a previous case or it is impossible to match.
```

**Comment by jcouv** [comment]
That does seem useful, but I don't know how hard that would be to check. 
Let's keep it on the plan and I'll get back to you to confirm. My feeling is that this could be added after we merge the feature (no IDE impact for this part).

**Comment by alrz** [comment]
FWIW I did this for enumerable patterns to avoid calling MoveNext at the end of the sequence. didn't think we need it here too. 
I discovered it while working on pattern explainer and subsumption checking tests. Anyways, needs to be thoroughly tested so expect it to take a bit of time to verify correctness.

**Comment by alrz** [comment]
>should list- and positional-patterns on ITuple interact?

Just to mention, they do already partially interact (except for elements).
```cs
_ = iTuple switch {
    {Length:3}=>0,
    (_,_,_)=>0,  // unreachable
};
_ = iTuple switch {
    [_,_,_]=>0,
    (_,_,_)=>0,  // unreachable
};
_ = iTuple switch {
    [1,2,3]=>0,
    (1,2,3)=>0,  // compiles
};
```

**Comment by jcouv** [comment]
LDM discussion today (on constant string patterns on `Span<char>`) brought up the question of whether list-patterns should interact with constant string patterns. Added an open question above.
For example: `someString is { ['s', ..] => 0, "subsumed" => 1, ... }`.

**Comment by jcouv** [comment]
Closing test plan as completed. Issue with [FAR](https://github.com/dotnet/roslyn/issues/58190) isn't blocking.
