### ISSUE TITLE
[Test Plan] Interpolated String Improvements

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn#51499]
Proposal:  ​
https://github.com/dotnet/csharplang/issues/4487

Spec: 
https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/improved-interpolated-strings.md

Feature Branch:
https://github.com/dotnet/roslyn/tree/features/interpolated-string

Compiler:

- [x] LangVersion
- [x] `DefaultInterpolatedStringHandler`
  - [x] Not present
  - [x] Present 
  - [x] Malformed
  - [x] In an `async` method with no `await` holes
  - [x] In an `async` method with `await` holes
- [x] Binary operator combination of interpolated strings
  - [x] `+` operator
  - [x] `+` operator with non interp string
- [x] Custom `InterpolatedStringHandler`
  - [x] Incorrect ctor
    - [x] implicit conversions to `int`?
 - [x] Missing `AppendLiteral`
 - [x] Incorect `AppendLiteral`
   - [x] Not return `bool` or `void`
 - [x] Missing `AppendFormatted`
 - [x] Incorrect `AppendFormatted`
   - [x] Not return `bool` or `void`
 - [x] Mismatched `AppendFormatted` and `AppendLiteral` return types
- [x] Handler overloads
  - [x] Pick handler over regular string for non-const
  - [x] Regular string over handler for const
  - [x] Handler over conversion to string
  - [x] Handler overloads with arguments:
    - [x] `val` over `in`
    - [x] `val` over `ref`
- [x] Handler args as:
  - [x] `val` 
  - [x] `ref`
  - [x] `in`
  - [x] implicit `ref` (allow mismatch)
  - [x] `out` 
  - [x] normal / expanded form
  - [x] other params after handler param
  - [x] default values
  - [x] reordered at call site
- [x] `InterpolatedStringHandlerArgumentAttribute`
  - [x] Missing
  - [x] Malformed
- [x] Parameter names
  - [x] Single parameter name
  - [x] Multiple parameters
  - [x] `""`
    - [x] Passes `this`
    - [x] On a static method
    - [x] On a ctor
  - [x] Incorrect parameter name
  - [x] Mix of correct and incorrect param names
  - [x] Referring to self
- [x] Nullable analysis for format holes and handler constructor (issue https://github.com/dotnet/roslyn/issues/54583)
- [x] Await in interpolation hole
  - [ ] `Ref` parameter
- [x] Dynamic handler
- [x] IOperation
- [x] Control Flow Graph
- [x] Semantic model
  - [x] GetConstantValue on additive expressions

Productivity:
- [ ] Intellisense for methods that have builder arguments
- [ ] Verify experience on some methods/overloads that will get builders (`string.Create`, `Debug.Assert`, `Debug.Write{Line}If`, `StringBuilder.Append{Line}`, `MemoryExtensions.TryWrite`)
- [ ] Extract interpolated string to a local (risks changing meaning/perf)
- [ ] Find all refs on custom handler type and constructor, and append methods
- [ ] go to definition

LDM:
- [x] conversion operator to string? ([details](https://github.com/dotnet/csharplang/issues/5077)) (answer: no)
- [x] parentheses and additive expressions ([details](https://github.com/dotnet/csharplang/issues/5106)) (answer: allow parens and suppressions)

**Comment by 333fred** [comment]
Test ideas from review:

* Test with `InterpolatedStringHandlerArgumentAttribute` on an `out` parameter.
* Test arguments on delegates, lambdas, and local functions.
* Test with handler having a default argument.
* Test on dictionary initializers.
* Test on extension methods
* Test when an explicit conversion to a handler would fail, but would succeed in an argument position.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/54585#discussion_r665711537

**Comment by 333fred** [comment]
The only remaining work here is in the IDE. Closing out.
