### ISSUE TITLE
Test plan for lambda improvements

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#52192]
Proposal: [lambda-improvements.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/lambda-improvements.md)
Branch: [features/lambdas](https://github.com/dotnet/roslyn/tree/features/lambdas)

Championed issue (explicit return type, attributes): https://github.com/dotnet/csharplang/issues/4934
Championed issue (direct invocation): https://github.com/dotnet/csharplang/issues/4748

### Remaining work items
- [x] using explicit return type in inference (PR https://github.com/dotnet/roslyn/pull/56534)
- [x] `ref` return types should parse (PR https://github.com/dotnet/roslyn/pull/56814)
- [ ] add LangVer hint to diagnostics that depend on LangVer (issue https://github.com/dotnet/roslyn/issues/56391)
- [x] conversions (to `object` and interfaces)
- [x] function types in method type and best type inference

#### Parsing
- [X] `static` lambdas
- [X] `async` lambdas
- [X] With parameter types
- [X] Without parameter types
- [X] With parameter ref specifiers
- [X] Without parameter ref specifiers
- [X] Nonparenthesized parameter list (should be a binding error)
- [X] Conditional array accesses
- [X] Object/collection initializers
- [X] After ternaries
- [X] Switch expression arms
- [X] Operator precedence
- [X] Disallow on lambda converted to expression tree

#### Semantics

- [ ] Nullability enforcements on lambda returns when there is an explicit return type and/or attributes (PR https://github.com/dotnet/roslyn/pull/56590)
    - [x] DisallowNull
    - [x] NotNull/NotNullWhen
    - [x] AllowNull
    - [x] MaybeNull/MaybeNullWhen
    - [ ] MemberNotNull/MemberNotNullWhen
    - [x] DoesNotReturn/DoesNotReturnIf
- [ ] Special attributes
    - [X] UnmanagedCallersOnlyAttribute
    - [X] ObsoleteAttribute/ExperimentalAttribute/DeprecatedAttribute
    - [X] SkipLocalsInitAttribute
    - [X] ExcludeFromCodeCoverageAttribute
    - [X] Security attributes
    - [ ] ~CallerFilePathAttribute~
    - [ ] ~CallerLineNumberAttribute~
    - [ ] ~CallerMemberNameAttribute~
    - [X] ConditionalAttribute
    - [ ] MethodImplAttribute
    - [ ] PreserveSigAttribute
    - [X] MarshalAsAttribute
    - [X] DllImportAttribute (error)
    - [ ] EnumeratorCancellationAttribute
- [X] GetTypeInfo (see `LambdaTests.LambdaAttributes_AttributeSemanticModel()`)
- [X] GetSymbolInfo
- [X] SyntaxNormalizer

#### IDE/Public API

- [ ] Attribute type completion inside brackets
- [ ] Automatic close bracket insertion
- [ ] Smart complete statement
- [ ] Speculation inside attribute brackets
    - [ ] New attributes
    - [ ] Argument positions
- [ ] Debugging: DebuggerStepThroughAttribute
- [ ] DebuggerDisplay
- [ ] Find all refs on attribute types
- [ ] IDE syntax formatter
- [ ] EnC
- [ ] Convert to local function/method refactorings

#### Syntax
- [X] `async async(async async) => async`
- [X] `async MyMethod() => null;` on the top level parses as a local function statement with a return type of `async`
- [ ] Other async contexts
- [x] `static` lambdas
- [x] `void` return type
- [x] disallow `var` return type (reserved)
- [x] ref/ref readonly return
    - [x] Errors on `void` return
- [x] Nested lambdas
- [x] After `is`
- [x] switch expression arms
- [x] Ternary arms
- [ ] Operator precedence
- [x] Type-tuple patterns in switch expression arms continue to be parsed as type-tuple patterns
- [x] Before and after range operators
- [ ] Everywhere a method can be used

#### Semantics

- [X] Mismatched `return` statement types and declared return type
    - [X] Nullable-only
    - [X] Inconvertible types
- [x] Target-typing for contained return statements
- [x] Type inference
  - [x] LDM: Should the explicit return type contribute to type inference? (Yes) (see `TypeInference_ExplicitReturnType_01`, ...) 
- [X] Pathological inference case short-circuiting (see `OverloadResolutionPerfTests.NestedLambdas_WithParameterAndReturnTypes()`)
- [X] GetTypeInfo (see `LambdaTests.LambdaReturnType_SemanticModel()`)
- [X] GetSymbolInfo (see `LambdaTests.LambdaReturnType_SemanticModel()`)
- [X] SyntaxNormalizer (issue https://github.com/dotnet/roslyn/issues/59653)

#### IDE/Public API

- [x] FindAllRefs finds return type
- [ ] Convert to local function/method
- [ ] Intellisense shows types (including after things like `static` or `async`)
- [x] IDE formatter

#### Syntax

- None

#### Semantics

- [ ] ~revert conditional binding patch from 16.11~ (ie. revert https://github.com/dotnet/roslyn/pull/53241)
- [X] Implicit and explicit conversions of lambda expression to:
  - [X] `System.MulticastDelegate` and base types and interfaces
  - [X] `System.Linq.Expressions.Expression<TDelegate>`
  - [X] `System.Linq.Expressions.Expression`, `System.Linq.Expressions.LambdaExpression`
- [X] Implicit and explicit conversions of method group to
  - [X] `System.MulticastDelegate` and base types and interfaces
- [ ] ~Directly invoke lambda expressions~
- [X] Breaking change tests
- [ ] Type inference based on lambdas
    - [X] Covariant on return natural type for value returns (see also issue https://github.com/dotnet/roslyn/issues/55909)
    - [X] Contravariant on parameter natural type for value parameters (see also issue https://github.com/dotnet/roslyn/issues/55909)
    - [X] Invariant for ref returns/parameters
    - [ ] Variance inversion handled correctly
- [X] `var`
    - [X] direct lambda/method group assignment
    - [X] variant assignment through ternaries
- [X] dicard: `_ = () => {};` (disallowed)
- [X] Method group with multiple candidates
  - [X] instance and static methods with same/different signature invoked with implicit/explicit receiver or explicit type qualifier
  - [X] instance and extension methods with same/different signature invoked with implicit/explicit receiver
  - [X] overridden method
  - [X] hidden method
  - [X] accessible and inaccessible overloads
  - [X] overloads that differ by parameter types/ref or return type/ref
  - [X] overloads that differ by object/dynamic, tuple element names, nullability, etc.
  - [X] overloads with different arity, invoked with implicit/explicit type arguments
  - [X] overloads with different type parameter constraints
- [X] Missing `Action` or `Func` types
- [X] Missing `System.Delegate` type
- [X] `modopt` and `modreq` do not affect delegate type
- [X] Delegate parameter types or return type that cannot be used as type arguments
- [ ] Delegate type includes inferred nullability
- [X] Synthesized types are shared
- [ ] Handling of parameter names (see VB)
- [X] Delegate type is only synthesized when required (not when converting to explicit type)
- [X] `ErrorCode.ERR_CannotInferDelegateType` only reported when delegate type is required
- [ ] Pattern-based language constructs
    - [ ] Query expression on lambda expression/method group with extension Select on delegate type
    - [X] Extension GetAwaiter
    - [X] Extension GetEnumerator
    - [ ] Extension GetAsyncEnumerator
    - [X] Extension deconstruct
- [ ] Address of on single-method method groups correctly infers function pointer type
- [X] Interaction with discard parameters
- [X] Lambdas that just throw
- [ ] GetTypeInfo on lambdas and method groups (issue https://github.com/dotnet/roslyn/issues/52874)
  - [ ] Does `.Type` return `null` or the `Action`/`Func`/synthesized delegate type? How does ASP.NET source generator obtain the lambda signature? (see [here](https://github.com/davidfowl/uController/blob/aa8bcb4b30764e42bd72d326cb2718a4d4eaf4a9/src/uController.SourceGenerator/uControllerGenerator.cs#L62-L81))
- [ ] GetSymbolInfo on lambdas and method groups (issue https://github.com/dotnet/roslyn/issues/52870)
- [X] IOperation nodes adjusted to give natural types
- [X] ClassifyConversion (see `DelegateTypeTests.ClassifyConversionFromExpression()`)
- [X] `ToDisplayString` on synthesized delegate types

#### IDE/Public API

- [ ] QuickInfo
- [ ] FindAllReferences to Action/Func type
- [ ] Maybe FindAllReferences on the delegate shows synthesized?
- [ ] Remove unnecessary cast
- [ ] Introduce local
- [ ] To/from `var` (issue https://github.com/dotnet/roslyn/issues/58404)

# Open issues
- [x] LDM: potential breaking change with overload resolution (issue https://github.com/dotnet/csharplang/issues/4674)
- [x] LDM: LambdaExpression

**Comment by 333fred** [comment]
Updated with initial test plan for Monday.

**Comment by Youssef1313** [comment]
`SyntaxGenerator.WithType` and also `SyntaxGenerator.GetType` may need to be updated to handle explicit return type:

https://github.com/dotnet/roslyn/blob/0254fbdf1322c008bb3fb006134131a29a878fa8/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L1857-L1867

https://github.com/dotnet/roslyn/blob/0254fbdf1322c008bb3fb006134131a29a878fa8/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L1816-L1842

**Comment by jcouv** [comment]
Thanks for adding the remaining tests @cston. Closing the test plan.
