### ISSUE TITLE
Test plan for "extended property patterns"

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn#52468]
Championed issue: https://github.com/dotnet/csharplang/issues/4394
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/extended-property-patterns.md

Initial PR: https://github.com/dotnet/roslyn/pull/52139

## Compilers
- [x] Verify a conditional access is not allowed in place of the name
- [x] IOperation and CFG (using `{ Prop1: { Prop2: pattern } }` translation, see `ExtendedPropertyPatterns_IOperation_*`, `ExtendedPropertyPatterns_IOperationOnMissing`)
- [x] Semantic Model (`GetSymbolInfo`, `GetTypeInfo`, see `ExtendedPropertyPatterns_SymbolInfo_*`)
- [x] nullable analysis 
  - [x] do we learn from member accesses, i.e. not null state for nested members?
  - [x] do we learn from pure null tests? (see `OtherComparisonsAsPureNullTests_ExtendedProperties_PureNullTest`)
  - [x] nullable value types
- [x] Pattern Explainer (do we give correct examples in a non-exhaustive match, see `ExtendedPropertyPatterns_Explainer`)
- [x] definite assignment (mark read fields, see `ExtendedPropertyPatterns_05`)
- [x] Verify all existing scenarios (where the name is optional or disallowed) work as expected with a member access (see `ExtendedPropertyPatterns_ExpressionColonIn*`)
- [x] inaccessible properties/fields (see `ExtendedPropertyPatterns_Inaccessible*`)
- [x] expression tree (see `ExtendedPropertyPatterns_ExpressionTree`)
- [x] Language Version
- [x] SyntaxNormalizer (see `TestNormalizeExtendedPropertyPattern`)
- [x] Obsolete (see `ExtendedPropertyPatterns_Obsolete*`)
- [x] Keep rejecting null-suppression and pointer access in patterns (issue https://github.com/dotnet/roslyn/issues/53484)
- [x] Count checked fields as used (issue https://github.com/dotnet/roslyn/issues/52956)
- [x] evaluation order
- [x] static properties/fields (errors)
- [x] API shape ([unshipped](https://github.com/dotnet/roslyn/blob/features/extended-property-patterns/src/Compilers/CSharp/Portable/PublicAPI.Unshipped.txt), [syntax](https://github.com/dotnet/roslyn/blob/features/extended-property-patterns/src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4#L603-L614))
- [x] EnC (nothing special)
- [x] exhaustiveness of `switch` expression
- [x] spec: no formal commitment to only evaluate once

## IDE
- [x] Completion for nested members and patterns
  - [x] Test completion with two possible bindings (see `CompletionOnListPattern_FirstNested` and test above)
- [x] QuickInfo/GoToDef
- [x] FindAllReferences on nested members
  - [x] Add one highlight or rename test (see `RenameExtendedProperty`)
- [x] formatting
  - [x] Add an indentation test (see `ExtendedPropertyPattern_Before` and `ExtendedPropertyPattern_After`) 
- [x] TypeInferrer (see `TestEnumInPatterns_SwitchStatement_ExtendedPropertyPattern`)
- [x] GenerateVariable (see `TestPropertyPatternInCasePattern2`)
- [x] Add test for `{ A.B: MissingConstant$$ }` (see `TestConstantPatternInExtendedPropertyPattern`)
- [ ] Offer to collapse pattern (`is { P1: { P2: ... } }` => `is { P1.P2: ... }`) (issue https://github.com/dotnet/roslyn/issues/55545)

**Comment by alrz** [comment]
@333fred

> chained member references for subpattern operation


 Is this the right thing to do if we had nullable value types? In this case `Member` belongs to the underlying type, not the receiver. Do we want to reflect that in the operation tree?

**Comment by 333fred** [comment]
> Is this the right thing to do if we had nullable value types? In this case Member belongs to the underlying type, not the receiver. How do we want to reflect that in the operation tree?

We shouldn't represent these any differently in the operation tree from nested property patterns. It's a shorthand for writing, but the semantics are exactly the same as if the user wrote it out the long way. Thus, the IOperation tree should be identical. If a user cares about the syntax form used to write out the pattern, they can go back to syntax at that point.
