### ISSUE TITLE
Test plan for CallerArgumentExpressionAttribute

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#52745]
Proposal: https://github.com/dotnet/csharplang/issues/287
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/caller-argument-expression.md

## General Concerns

* [x] LangVersion - No lang version impact for caller info attributes.
* [x] VB Interop
    * [x] VB does case-insensitive identifier matching
    * [x] VB emits correct casing, regardless of user's casing in source
* [x] Update spec with implicit conversion rules
* [x] Remove feature flag after Aleksey reviews.

## Semantics

* [x] Syntax is reflected exactly
    * [x] Leading comments ignored
    * [x] Trailing comments ignored
    * [x] Middle comments included
    * [x] Leading pragmas ignored
    * [x] Trailing pragmas ignored
    * [x] Middle pragmas included
* [x] Parameter remapping
    * [x] Extension methods
        * [x] Info of `this` parameter
        * [x] Info of non-`this` parameter
    * [x] Delegate Invoke
    * [x] Delegate BeginInvoke
    * [x] Delegate EndInvoke
* [x] Overridden by existing caller info attributes
    * [x] CallerFilePathAttribute
    * [x] CallerLineNumberAttribute
    * [x] CallerMemberNameAttribute
* [x] Self-referential attribute
* [x] Explicit argument reordering
* [x] Applied multiple times
* [x] Invalid parameter name
* [x] No default value provided for parameter
* [x] Referenced parameter uses default value
* [x] Attribute added to overridden method
* [x] Attribute removed from overridden method
* [x] Attribute applied to type with implicit conversion from string
    * [x] Reference conversion
    * [x] User-defined conversion
    * [x] No conversion
* [x] Compiler generated calls with user-written code
    * [x] Extension GetEnumerator
    * [x] Extension Deconstruct
    * [x] Implicit Index/Slice (should be default)
    * [x] Extension GetAwaiter
* [ ] Ref/out parameters
    * [ ] Out variable declarations
    * [ ] Out discards
* [x] Implicit base constructor calls (should be ignored, like other Caller info attributes)

# Open issues:
- [ ] could we add `CallerArgumentExpression` to `Debug.Assert` and have that new overload get picked?

FYI @Youssef1313

**Comment by Youssef1313** [comment]
There is already `Debug.Assert(bool condition)` and `Debug.Assert(bool condition, string message)`.

Overload resolution will currently pick `Debug.Assert(bool condition)` over `Debug.Assert(bool condition, [CallerArgumentExpression("condition")] string expression ="")`.

It could be tweaked to prefer the other overload *only* because it has caller member attribute, but that will make the language inconsistent.

Another solution I can think of (which I'm not sure if it's good) is introducing a new language feature, a special attribute `MethodForwardAttribute` which causes the overload resolution to be instructed to pick another specific compatible overload.

I can't think of other use cases of such a new language feature, so I don't think it's a great idea to introduce a whole language feature just for this?

**Comment by alrz** [comment]
> could we add CallerArgumentExpression to Debug.Assert and have that new overload get picked?

Make `Assert(bool)` obsolete and remove obsolete members from the candidate set? (cons: too scary)

**Comment by 333fred** [comment]
> Make `Assert(bool)` obsolete and remove obsolete members from the candidate set? (cons: too scary)

Probably a breaking change unfortunately.

**Comment by alrz** [comment]
Consider existing code with an obsolete overload:

- In cases currently resolved to the obsolete method, an error is already produced (with `error: true`). If this rule causes another method to get picked it's not a breaking change by definition.

- With this rule in place, user would never see the obsolete error for `Assert(bool)` because it gets removed from the set and `Assert(bool, string=null)` wins.

- Lastly, since the method is there, the change is binary compatible anyways.


Now the question is, can this possibly make the overload resolution to pick another method where it already compiles without any error? that is, it's not ambiguous and it's not resolved to the obsolete method.

I'm leaning towards *no, it can't* but I'm not completely sure.

**Comment by AlekseyTs** [comment]
1) I think discussions like that do not belong in a Test Plan issue.
2) It is fine to consume an obsolete APIs in another obsolete API, not an error, not even a warning

**Comment by Youssef1313** [comment]
### TODO

```csharp
using System;
using System.Runtime.CompilerServices;

public class MyAttribute : Attribute
{
    public MyAttribute(string s, [CallerArgumentExpression("s")] string x = "") { }
}

[My("Hello")]
public class Program { }
```

**Comment by Youssef1313** [comment]
Open questions:

- [ ] VB support
- [ ]Should caller argument expression be given an argument that's compiler generated? for example, the argument expression refers to a parameter that is a CallerMemberName. Should the argument expression take the default value or take the value supplied by the compiler for CallerMemberName (my current implementation won't supply compiler generated arguments)
- [ ] Should there be a warning if the caller argument expression refers to itself? void M([CallerArgumentExpression("p") string p = null)
- [ ] Should comments be included as part of the caller argument expression?
- [ ] If yes to previous point, there are cases where part of the comment doesn't parse as part of the ArgumentSyntax, would that be okay?

**Comment by 333fred** [comment]
Open questions were answered in https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-06-14.md.

**Comment by jcouv** [comment]
FYI `LanguageVersion.CSharp10` was to the `main` branch. Before merging this feature to `main` please ensure that it is attached to the correct language version.

**Comment by Youssef1313** [comment]
@jcouv Thanks. I'll do when https://github.com/dotnet/roslyn/pull/54064 goes in.

**Comment by Youssef1313** [comment]
TODO: https://github.com/dotnet/roslyn/pull/54355#issuecomment-879386305

**Comment by 333fred** [comment]
Updated the test plan in preparation for review this afternoon. I went through and checked off all the boxes I could find tests for.

**Comment by jerviscui** [comment]
@Youssef1313 Thank you very much! 
The tool SharpLab is also very useful. Thank you for your sharing!

And I'm about to try VS 2022.
I think 64bit would be useful to me.
Thank you.
