### ISSUE TITLE
Test plan for "field keyword in properties"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#57012]
Championed proposal: https://github.com/dotnet/csharplang/issues/8635
Spec: [proposals/field-keyword.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-14.0/field-keyword.md)

```csharp
public string PropertyConstraint
{
    get;
    set => field = value ?? throw new ArgumentNullException();
} = "";
```

Compiler:
- [x] language version
- [x] `field` keyword
  - [x] based on language version
  - [x] as *primary_expression* only
  - [x] escaped with `@`
  - [x] `this.field`, `base.field`, `Qualifier.field`
  - [x] in simple property: `object P => expr;`
  - [x] in property accessors: expression body; block body
  - [x] in indexer accessors
  - [x] in event accessors
  - [x] in nested lambdas and local functions
  - [x] in property initializer
  - [x] in attributes on property, accessor, nested function
  - [x] in nested function signature as default value
  - [x] in `nameof()`
  - [x] in call to `[Conditional]`
- [x] warning when previously binding to other symbol
  - [x] based on language version
  - [x] member of containing type, base type
  - [x] local, in same or nested function
  - [x] parameter in nested function
  - [x] type parameter, in containing type or nested function
- [x] mixed auto- and manually-implemented accessors (see `FieldKeywordTests.ImplicitAccessorBody_*`)
  - [x] `get`, `set`, `init`
  - [x] in `interface`
- [ ] field use
  - [x] static and instance properties on `class`, `struct`, `ref struct`, `interface`, `record*`
  - [x] `get`-only, `set`-only, `init`-only (see `FieldKeywordTests.AutoPropertyMustHaveGetAccessor_*`)
  - [x] `field` references in multiple properties: each get private backing field
  - [x] auto-implemented properties (including `field`) must override all accessors (see `FieldKeywordTests.Override_*`, `New_*`)
  - [x] in nested function, including `static` field reference in `static` function (see `FieldKeywordTests.Lambda_*`, `LocalFunction_*`)
  - [x] in attribute arguments (see `FieldKeywordTests.Attribute_*`)
  - [x] `ref` returning property (see `FieldKeywordTests.RefReturning_*`)
  - [x] properties with restricted types (see `FieldKeywordTests.RestrictedTypes`)
  - [x] properties with by-ref-like types (see `FieldKeywordTests.ByRefLikeType_*`)
  - [ ] `@field` with and without backing field
  - [ ] `Color Color`
  - [x] passing by reference: (see `FieldKeywordTests.PassByReference_*`)
    ```csharp
    struct S
    {
        readonly object P { set { M1(ref field); M2(in field); } }
        static void M1(ref object o) { }
        static void M2(in object o) { }
    }
    ```
- [x] synthesized backing field
  - [x] backing field emitted when any auto-implemented accessor or `field` reference
  - [x] backing field marked `[CompilerGenerated]` (see `FieldKeywordTests.Attribute_03`)
  - [x] emitted when used in `[Conditional]` code only (see `FieldKeywordTests.Conditional`) (see [open LDM question](https://github.com/dotnet/csharplang/blob/main/proposals/field-keyword.md#conditional-code))
    ```csharp
        object P { set { Debug.Assert(field is null); } }
    ```
  - [x] emitted to ref assembly
- [x] `[field:]` attributes
  - [x] emitted on synthesized backing field (see `FieldKeywordTests.Attribute_03`)
  - [x] not emitted on property (see `FieldKeywordTests.Attribute_03`)
  - [x] error if no auto-implemented accessors and no `field` references (see `FieldKeywordTests.PartialProperty_Attribute_03`)
  - [x] `[field: Obsolete]` (see `FieldKeywordTests.ObsoleteAttribute`)
- [x] `nameof(field)`
  - [ ] `nameof(field)` as invocation
- [x] property initializer (see `FieldKeywordTests.Initializer_*`)
  - [x] allowed when any auto-implemented accessor or `field` reference
  - [x] static and instance properties on `class`, `struct`, `ref struct`, `interface`
  - [x] written to field directly
- [x] constructor assignment (see `FieldKeywordTests.ConstructorAssignment_*`)
  - [x] assigns to setter if available, otherwise getter
  - [x] static and instance properties on `class`, `struct`, `ref struct`, `interface`
  - [x] assigned in other initializer
  - [x] assigned in nested function
- [ ] flow analysis
  - [ ] warning CS0414: The field is assigned but its value is never used
  - [ ] warning CS0649: Field is never assigned to, and will always have its default value
  - [x] auto-default initialization of `struct` backing fields and warnings when property is accessed in constructor (see `FieldKeywordTests.DefaultInitialization_*`)
    - [x] expect no auto-default inserted when a field initializer is used
    - [x] expect an auto-default when assigning in constructor
- [x] `readonly` properties (see `FieldKeywordTests.ReadOnly_*`)
  - [x] backing field is `initonly` when type, property, or accessor is `readonly`
  - [x] error reporting when modifying `field` in `get`, `set` accessors
- [x] `set` accessor in `readonly` context for property using `field` (see [open LDM question](https://github.com/dotnet/csharplang/blob/main/proposals/field-keyword.md#readonly-context-and-set)) (see `FieldKeywordTests.ReadOnly_01`)
- [ ] partial properties (see `FieldKeywordTests.PartialProperty_*`)
  - [x] mix of auto- and manually-implemented accessors
  - [x] static and instance properties on `class`, `struct`, `ref struct`, `interface`, `record*`
  - [x] `field` in accessors
  - [x] initializer on definition *or* implementation
  - [x] initializer on definition *and* implementation with same or different values
  - [x] initializer with no `field` or auto-implementation
  - [x] `field` references on definition *or* implementation
  - [x] `field` references on definition *and* implementation
  - [x] `field` references on `readonly` property or accessor with same or different modifiers on parts
  - [x] `[field:]` attributes concatenated across parts
    - [ ] error when the attributes are the same and `AllowMultiple=false`
  - [ ] partial properties where the implementation uses `field` and one or both parts have `field:` targeted attribute lists. (See also `PartialPropertiesTests.Attributes_Property_BackingField`. This issue referenced in source.)
  - [ ] Check warning `WRN_SequentialOnPartialClass` is produced when needed (see also [comment](https://github.com/dotnet/roslyn/pull/74706#discussion_r1714213347))
  - [x] [comment](https://github.com/dotnet/roslyn/pull/73773#discussion_r1621441043) from `partial` properties
  - [x] [comment](https://github.com/dotnet/roslyn/pull/73773#discussion_r1621442045) from `partial` properties
- [x] nullability (initial implementation) (see `FieldKeywordTests.Nullability_*`) #75244
  - [x] `field` has annotations of containing type
  - [x] `[field:MaybeNull]` etc. affect `field`
  - [x] `NullableWalker.Scan().getFieldSymbolToBeInitialized()`: Is checking IsAutoProperty sufficient or should we check the appropriate accessors are missing or auto-implemented (see [comment](https://github.com/dotnet/roslyn/pull/75116#discussion_r1769280504))?
      - Moving to standalone issue #75245
  - [x] `NullableWalker.TryGetReceiverAndMember()`: call `Binder.AccessingAutoPropertyFromConstructor` to match `DefiniteAssignment` implementation (see [comment](https://github.com/dotnet/roslyn/pull/75116#discussion_r1769283496))?
      - (wontfix) It feels like the churn of reversing this, just to be consistent with definite assignment, is not worth it right now.
- [ ] SemanticModel
  - [x] `GetSymbolInfo(fieldExpr)` returns backing field
  - [ ] add `field` reference in the speculative semantic model https://github.com/dotnet/roslyn/issues/75398
  - [x] `IOperation` for expression referencing `field`
- [ ] `struct` fulfills `unmanaged` constraint and managed type rules (see pointer types) depending on synthesized fields
- [ ] ref safety:
  ```csharp
  struct S
  {
      [UnscopedRef]
      Span<int> Prop1 => M(ref field); // should not error

      // Should error
      Span<int> Prop2 => M(ref field); // should error
    
      static Span<int> M(ref Span<int> span) => default;
  }
  ```
- [x] public API review: https://github.com/dotnet/roslyn/issues/74937
- [ ] update compiler test plan

Productivity:
- [ ] Fixer for compat break
- [ ] QuickInfo
- [ ] Completion
- [ ] Colorization
- [ ] Conversion?
- [ ] F1 help on `field`
- [x] EnC: https://github.com/dotnet/roslyn/issues/77951

**Comment by CyrusNajmabadi** [comment]
Moving to 17.2.  The work for thsi hasn't gotten merged in yet anyways.

**Comment by Youssef1313** [comment]
Note to self: The following properties for `SynthesizedBackingFieldSymbol` needs to be revised:

- DeclaringSyntaxReferences (should it remain empty or return the first usage of `field` keyword?)
- IsImplicitlyDeclared (should it always return true or return false for field-keyword backing fields?)

**Comment by Youssef1313** [comment]
There are interesting scenarios around overriding virtual properties.

```csharp
public class Base
{
    public virtual int P1 { get; set; }
    public virtual int P2 { get; set; }
    public virtual int P3 { get; set; }
    public virtual int P4 { get; set; }
    public virtual int P5 { get; set; }

    public virtual int P6 { get => 0; set { } }
}

public class Derived : Base
{
    // no error.
    public override int P1 { get => 0; }
    
    // This produces Auto-implemented properties must have get accessors.
    // However, per the spec updates, a set-only with semicolon is allowed.
    // Should this now produce an error similar to ERR_AutoPropertyMustOverrideSet?
    //public override int P2 { set; }

    // This synthesizes a sealed setter. Make sure we have this behavior for semi-auto.
    public sealed override int P3 { get => 0; }

    // Auto-implemented properties must override all accessors of the overridden property.
    //public override int P4 { get; }

    // Will this be allowed? It's not allowed for old-style auto properties (see P4).
    //public override int P5 { get => field; }

    public override int P6 { get => field; }

    public Derived()
    {
        // P6 looks like a property that's assignable through backing field.
        // But this shouldn't be the case due to the inherited setter.
        // We should use 'GetOwnOrInheritedSetMethod' for the logic of assignability through backing field.
        // Add a test to confirm that.
        P6 = 10;
    }
}
```

Do these scenarios have clear answer as to what's the expected behavior? Are there any that needs to be discussed in LDM?

cc @AlekseyTs @333fred @CyrusNajmabadi

**Comment by AlekseyTs** [comment]
> per the spec updates, a set-only with semicolon is allowed.

Could you add a quote from the relevant portion of the spec?

> Should this now produce an error similar to ERR_AutoPropertyMustOverrideSet?

Please include exact wording of the message.

> // Will this be allowed? It's not allowed for old-style auto properties (see P4).

We probably should treat this as a property with a user provided body. Presence of the `field` keyword probably shouldn't make any difference.

**Comment by AlekseyTs** [comment]
@Youssef1313 BTW, consider not "polluting" the Test Plan issue with "random" discussions. Open a separate issue for each specific question.

**Comment by CyrusNajmabadi** [comment]
Note: `Fixer for compat break`

Productivity does not own this.  We've been explicit on compiler semantic breaks that the best people who understand the breaks perfectly, and know exactly how to fix them, are the compiler team (since they put in the new rules/code), and know exactly what change will result in code with the exact same semantics as before.

As such, if we want such a fixer, it should be part of the compiler, potentially driven by known compiler diags (hidden or not) and with exact fixes for all the scenarios enumerated and tested.
