### ISSUE TITLE
Test plan for "required members"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#57046]
Championed proposal: https://github.com/dotnet/csharplang/issues/3630
Specification: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/required-members.md

## Compiler
- [x] Notify F#, C++/CLI, etc.
- [x] VB (disallow attribute usage? tracking issue https://github.com/dotnet/roslyn/issues/61435)
- [x] update test plan
- [x] Review public API
- [x] Any breaking changes? (parsing issues?)
- [x] SyntaxNormalizer
- [x] SymbolDisplay
- [x] address PROTOTYPE markers
- [x] local named "required" in top-level statements (C# 10 vs 11), will be handled as bug fix after merge (issue https://github.com/dotnet/roslyn/issues/61510)
- [x] make type named "required" an error
- [x] consider filtering `RequiredMembers` attribute in compiler layer/API (issue https://github.com/dotnet/roslyn/issues/61511)

### declaration
- [x] `required` as contextual keyword ("required" type, type parameter, etc exists in scope)
- [x] where `required` modifier is allowed/disallowed
- [x] disallow `required` modifier based on LangVer
- [x] disallow `required` type name based on LangVer
- [x] missing attribute type or ctor
- [x] RequiredMember attribute emitted on type and members
- [x] Overriding can tighten requirement
- [x] Cannot hide required member
- [x] Required member must as accessible as containing type
- [x] `RequiredMember` attribute disallowed in source
- [x] field/property without setter
- [x] field/property with less accessible setter
- [x] different kinds of members (field, property, indexer, event, nested type, ...)
- [x] different kinds of containing types (class, struct, record; disallow interface)
- [x] `required` with field/property initializer (allowed)
- [x] rules with obsolete
- [x] no definite assignment for `SetsRequired`
- [x] must specify `SetsRequired` when `SetsRequired` on `base` or `this`
- [ ] combination with other modifiers (`fixed`, `ref readonly`, `ref`, `const`, `static` disallowed; others such as `extern`, `partial`, `virtual` allowed)
- [ ] record with required positional member declared explicitly
- [x] modifier can be parsed in different orders

#### metadata
- [x] `Required` attribute cannot be manually applied
- [x] `required` members are marked `Required` and the type too. But not if merely derived from a type with required members.
- [x] `CompilerFeatureRequired` with marker string
- [x] `Obsolete` with marker string
- [x] invalid type from metadata
- [x] `SetsRequired` set on record copy ctor

### usage
- [x] object initialization
- [x] nested object initializers `new C { Inner = new D { ... } }` versus `new C { Inner = { ... } }`
- [x] attribute construction with named arguments
- [x] `new()` constraint not satisfied

### nullability
- [x] nullable analysis of constructors in presence or absence of `[SetsRequiredMembers]` with required members
- [x] initial nullable flow state of required setters, when the type contains some combination of required and non-required non-nullable reference properties.

## LDM
- [x] LDM: should we give a diagnostic for `required` property with an initializer (useless)? (answer: no, can be useful)
- [x] LDM: should we do something about ref-returning properties (useless)? (disallow)
- [x] LDM: should we do something about `readonly` modifier? (disallow)
- [x] LDM: what if the required property is obsolete?

## BCL
- [x] Confirm we want types in BCL and complete API review
- [x] Implement types (https://github.com/dotnet/runtime/pull/64287)
- [ ] Can/should Reflection APIs honor `required`?

## Productivity:
- [x] typing/completion
  - [ ] https://github.com/dotnet/roslyn/issues/61439 covers soft-select during override completion, also broken for partial.
- [x] override completion
- [x] MetadataAsSource ([done](https://github.com/dotnet/roslyn/pull/61440))
- [ ] formatting
- [ ] colorization
- [x] F1/help ([done](https://github.com/dotnet/roslyn/pull/61440))
- [x] QuickInfo (P0: should not crash, P2: consider whether to show `required`) (no change, manually verified)
- [x] Sorting modifiers ([done](https://github.com/dotnet/roslyn/pull/61440))
- [ ] completion of object creation should call out required members
- [ ] snippet-style completion?
- [ ] some existing refactorings produce/modify constructors
- [ ] add option to generate required property for refactorings that generate properties

**Comment by hez2010** [comment]
Any updates for `record with required positional member declared explicitly`?

**Comment by 333fred** [comment]
I'm not sure what you're asking about. This issue is tracking adding tests m

**Comment by SunnieShine** [comment]
It seems that @hez2010 wants to describe about this usage:

```csharp
#nullable enable

using System.Runtime.CompilerServices;

sealed file record R(
	// 'required' modifier on arguments in record primary constructor
    required int Property1,

	// Or use attribute (At present this usage is disallowed)
    [property: RequiredMember] string Property2
);

namespace System.Runtime.CompilerServices
{
    sealed file class RequiredMemberAttribute : Attribute { }

    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
    sealed file class CompilerFeatureRequiredAttribute : Attribute
    {
        public CompilerFeatureRequiredAttribute(string featureName)
            => FeatureName = featureName;
        
        public string FeatureName { get; }
    }
}
```

**Comment by hez2010** [comment]
> I'm not sure what you're asking about. This issue is tracking adding tests.

See https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTAnApgYwHtsATAAgDFDCAKPARwFco9zYAXMgDQEoBuIA

We still cannot use `required` in primary constructor of records.

**Comment by 333fred** [comment]
> We still cannot use required in primary constructor of records.

For new additions to the feature, please use csharplang.

However, for this particular request, I'll save you some time by telling you that you don't really want it. If you mark a property as required, it must be set with a property initializer. No ifs, ands, or buts. This would create a primary constructor that takes a parameter to set the property, and you must then use an object initializer to set the property again.

**Comment by jcouv** [comment]
@jasonmalinowski I think we're ready to close this test plan from the compiler side. The follow-up compiler work is tracked by separate issues. 
Can you create follow-up issues for bullets that still need IDE work?

**Comment by jcouv** [comment]
@333fred will follow-up with runtime team on possibility of Reflection API and file an issue if there's interest.
Chatted with @jasonmalinowski about remaining IDE items. I think all the basics are covered and there's no urgent follow-up.
I'll go ahead and close this test plan as completed. Thanks
