### ISSUE TITLE
Provide interactive help to reflow expressions

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#58093]
We want to help the developer restyle their code dynamically. We can present an interface that shows the developer a set of different styles simultaneously and allows them to quickly select the option that looks best.

-----

## Tracking Issues

- [ ] [Formatting rule for columnar formatting](https://github.com/dotnet/roslyn/issues/28729)
- [ ] [Comment indentation](https://github.com/dotnet/roslyn/issues/32485)
- [ ] ["Wrap" refactorings should be a part of code-style](https://github.com/dotnet/roslyn/issues/53464)
- [ ] [Feature request: Allow me to specify a desired max-column that code shoudl be wrapped against.](https://github.com/dotnet/roslyn/issues/15406)
- [ ] [I would like a refactor in the C# editor that will reflow a multiline comment at some margin.](https://github.com/dotnet/roslyn/issues/33066)
- [ ] [Prettier-style line breaking](https://github.com/dotnet/format/issues/246)
- [ ] [Alignment Refactoring ordering should be stable](https://github.com/dotnet/roslyn/issues/37962)
