### ISSUE TITLE
Refine and Improve the .NET Tooling Ecosystem

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#58269]
---
## Related Work
- [ ] [https://github.com/dotnet/roslyn/issues/56763](https://github.com/dotnet/roslyn/issues/56763)
- [ ] [https://github.com/dotnet/roslyn/issues/7842](https://github.com/dotnet/roslyn/issues/7842)
- [ ] [https://github.com/dotnet/roslyn/issues/18093](https://github.com/dotnet/roslyn/issues/18093)
