### ISSUE TITLE
Developers get guidance on best practices when writing C# or Visual Basic code

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#58267]
---
## Related Work
- [ ] [https://github.com/dotnet/roslyn/issues/11499](https://github.com/dotnet/roslyn/issues/11499)
- [ ] [https://github.com/dotnet/roslyn/issues/16625](https://github.com/dotnet/roslyn/issues/16625)
- [ ] [https://github.com/dotnet/roslyn/issues/11021](https://github.com/dotnet/roslyn/issues/11021)
- [ ] [https://github.com/dotnet/roslyn/issues/45198](https://github.com/dotnet/roslyn/issues/45198)
