### ISSUE TITLE
Improve .NET Productivity inner-loop performance

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn#58268]
---
## Related Work
- [ ] [https://github.com/dotnet/roslyn/issues/56843](https://github.com/dotnet/roslyn/issues/56843)
- [ ] [https://github.com/dotnet/roslyn/issues/57607](https://github.com/dotnet/roslyn/issues/57607)
- [ ] [https://github.com/dotnet/roslyn/issues/45534](https://github.com/dotnet/roslyn/issues/45534)
- [ ] [https://github.com/dotnet/roslyn/issues/55228](https://github.com/dotnet/roslyn/issues/55228)
- [ ] [https://github.com/dotnet/roslyn/issues/57544](https://github.com/dotnet/roslyn/issues/57544)
