### ISSUE TITLE
Options master plan

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#58717]
Work items:
- [x] Finish #55728
- [ ] Eliminate editorconfig options mapping (`TryMapEditorConfigKeyToOption`)
  - Moved to `IEditorConfigOptionMappingService`
  - May be possible to hardcode public options, we shouldn't need mapping for other
- [ ] Move `IGlobalOptionService` to LSP layer, later on to EditorFeatures once solution crawler is removed
      Currently also used by LSP server to read Pull/Push diagnostics option.
      #57283
- Internally obsolete/remove:
  - [x] `OptionSet`,
  - [x] `DocumentOptionSet`, 
  - [x] `SerializableOptionSet` - replaced with `SolutionOptionSet`
  - [x] `WorkspaceOptionSet`,
  - [ ] `AnalyzerConfigOptionSet`
- [x] Remove `IDocumentOptionsProvider`, 
       Remove `RazorDocumentOptionsProvider`. Razor only uses this to override indentation options. These should flow via LSP/EditorOptions.
       Refactor `InferredIndentationDocumentOptionsProviderFactory` to avoid `IDocumentOptionsProvider`. These should be just flow from EditorOptions.
- [x] Remove `IOptionService` (replaced with `ILegacyWorkspaceOptionService`)
- [x] Obsolete `Document.GetOptionsAsync`
- [ ] Obsolete `Solution.Options` and `Workspace.Options`
  Services that currently read Solution options should be passed their options explicitly using specific option record (as described in #55728). 
  The source of these options would be either `IGlobalOptionService` service accessed in client code in EditorFeatures layer or above, or LSP server who receives the options from the LSP client.
  Note: Need to serialize values for options read from editorconfig.
  - [x] AddImportOptions
  - [x] CodeActionOptions
  - [x] FadingOptions
  - [x] FormattingOptionsMetadata
  - [x] CompletionOptions
  - [x] DiagnosticOptions
  - [x] DocumentationCommentOptions
  - [x] RegularExpressionsOptions
  - [x] ExtractMethodOptions
  - [x] GenerateOverridesOptions
  - [x] ImplementTypeOptions
  - [x] InlineParameterHintsOptions
  - [x] InlineTypeHintsOptions
  - [x] NavigationOptionsProvider
  - [x] QuickInfoOptions
  - [x] BlockStructureOptions
  - [x] ValidateFormatStringOptionProvider
  - [x] ClassificationOptions
  - [x] CodeStyleOptionsProvider
  - [x] GenerationOptionsProvider
  - [x] PythiaOptions
  - [x] AutoFormattingOptions
  - [x] SimplificationOptionProvider
  - [x] SolutionCrawlerOnOffOptionsProvider
  - [x] StorageOptions
  - [x] SymbolSearchOptions
  - [x] TodoCommentOptions
  - [x] FormattingOptions2
  - [x] SyntaxTreeConfigurationOptions
  - [x] VisualStudioSyntaxTreeConfigurationService
  - [x] GenerateEqualsAndGetHashCodeFromMembersOptions
- [x] Public options:
  The corresponding APIs need to load these from `Solution.Options` for backward compat. These will not be available OOP.
  - [x] CSharpFormattingOptions
  - [x] RenameOptions
  - [x] SimplificationOptions
  - [x] CodeStyleOptions
- [ ] Remove IOptionProvider, ExportOption attributes
  All options should be global options or .editorconfig options. SolutionExportOptionAttirbute is only needed for serialization to SerializableOptionSet. GlobalExportOptionAttribute is not needed.
- [x] Analyzers will read their settings from `AnalyzerConfigOptions`
  Remove `AnalyzerConfigOptionsImpl`, which combines `AnalyzerConfigOptions` with `OptionSet`. Instead, represent .editorconfig option values that are stored in VS registry settings and used as defaults when no .editorconfig applies as `AnalyzerConfigOptions` implementing a global .editorconfig. This instance of `AnalyzerConfigOptions` can be stored in on `WorkspaceAnalyzerOptions` and trivially serializable.

Editor/Platform prerequisites:
- [x] Make `IVsTextView.IndentStyle` available through `ITextView.Options`: [VS #1412138](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1412138)
- [x] Custom editorconfig properties are not exposed through editor options: [VS #1429383](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1429383)
- [ ] Editorconfig options in the editor do not have lowercased keys and the dictionary is not case-insensitive [VS #1556206](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1556206)
- [x] Add free-threaded API that replaces IVsTextManager4.GetUserPreferences4: [VS #1307188](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1307188)
- [ ] LSP options design and implementation

Related:
- [x] #62683
- [x] #57554 
- [x] https://github.com/dotnet/roslyn/issues/57553
- [x] https://github.com/dotnet/roslyn/issues/58745
- [x] https://github.com/dotnet/roslyn/issues/58874
- [x] https://github.com/dotnet/roslyn/issues/58823
- [x] https://github.com/dotnet/roslyn/issues/58745
- [ ] https://github.com/dotnet/roslyn/issues/58917
- [ ] https://github.com/dotnet/roslyn/issues/59089
- [x] https://github.com/dotnet/roslyn/issues/59090
- [x] https://github.com/dotnet/roslyn/issues/59184
- [x] https://github.com/dotnet/roslyn/issues/59267
- [ ] https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1314635
- [x] https://github.com/dotnet/roslyn/issues/60795
- [x] https://github.com/dotnet/roslyn/issues/60794
- [ ] https://github.com/dotnet/roslyn/issues/60786
- [ ] https://github.com/dotnet/roslyn/pull/62684 follow ups
- [ ] #62748

**Comment by CyrusNajmabadi** [comment]
@tmat ANything left to do on this?  If so, reactive and assign a milestone for it.  tnx.
