### ISSUE TITLE
Test plan for ref fields

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#59194]
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md
Tracking issue in runtime repo: https://github.com/dotnet/runtime/issues/63768

Guideline for addressing remaining issues:
- Base local testing off of 17.4 branch (verify behavior shipping in .NET 7)
- Base PRs on main (verify behavior in VS 17.5).
- Issues which we plan to address in 17.5, open new standalone issues and check-off in here
- Scenarios which we *do not plan* to test, either delete the line or add ❌ at start of line at your discretion.

## Compiler
- [x] spec: add grammar
- [x] spec: `scoped` can only be applied to a `ref` type or a type that is a `ref struct`
- [x] import of `ref` field when runtime feature flag is missing: `RefFieldTests.RuntimeFeature`
- [x] ref assemblies and consumption by old compilers
  - [x] `ref` fields _are_ emitted as `ref` for reference assemblies (no change). Note that our ability to control what old compilers actually do with these fields is somewhat limited. We prefer if it just gives a use site error when the ref field is used, but may not be able to make changes if the behavior does not end up being ideal. (RefFieldTests.RefAssembly)
  - [x] ~~ref assemblies which contain ref fields not consumable by old compilers (even if ref field is private)~~ (not a supported scenario)
  - [x] ~~Test metadata compatibility with previous compiler release (C# and VB)~~ (not a supported scenario)
- [x] check internal enumerations of local variable kinds (ensure that all LocalDeclarationKind values which can by by-ref or ref struct are given correct val escape and ref escape, with or without `scoped` keyword) #62039
- [x] spec: OHI
- [x] ~~manual test of C++/CLI (can reference local assemblies with ref fields)~~ (known issue, tracked by C++/CLI team)
- [x] spec
- [x] add to compiler test plan
- [x] `-langversion:11`
  - [x] for `ref` field declarations in source (also requires RuntimeFeature.ByRefFields)
  - [x] for use-site of `ref` fields from metadata or compilation reference (RefFieldTests.LanguageVersionDiagnostics)
- [x] updated escape rules enabled by
  - [x] `-langversion:11` _or_
  - [x] `System.Runtime.CompilerServices.RuntimeFeature.ByRefFields` https://github.com/dotnet/roslyn/issues/62131
- [x] `ref` and `ref readonly` fields for `ref struct` only
  - [x] declaration error for `ref` field in `class`, `struct`, `record` in source https://github.com/dotnet/roslyn/issues/62596
  - [x] declaration error for `ref` parameter in `record` in source
  - [x] use-site error for `ref` field in `class` or `struct` from metadata for C# and VB https://github.com/dotnet/roslyn/issues/64682
- [x] field must be declared `readonly ref` in `readonly ref struct`
- [x] escape analysis within `readonly` methods (RefFieldTests.MethodArgumentsMustMatch_13)
- [x] `readonly ref` emitted as `initonly`
- [x] `ref readonly` emitted with `System.Runtime.CompilerServices.IsReadOnlyAttribute`
- [x] `ref struct` with a `ref` field is not considered `unmanaged` https://github.com/dotnet/roslyn/issues/63104
- [x] field initializers:
  - [x] `ref` initializer https://github.com/dotnet/roslyn/issues/64720
  - [x] error reported for value initializer https://github.com/dotnet/roslyn/issues/64725
  - [x] `ref struct` field initializer _safe-to-escape_: see [#60577 comment](https://github.com/dotnet/roslyn/pull/60577#discussion_r843103935)
- [x] `ref` field modifiers
  - [x] `static ref` fields disallowed
  - [x] `const ref` fields disallowed
  - [x] `volatile ref` fields disallowed
  - [x] `fixed ref` fields disallowed
- [x] `ref` auto-properties disallowed
    ```csharp
    ref T P0 { get; }       // error
    ref T P1 { get; set; }  // error
    ref T P2 { get; init; } // error
    ```
- [x] `ref` in object initializers supported: `new S { F = ref t }` https://github.com/dotnet/roslyn/issues/62120
- [x] `ref` field of the containing type: https://github.com/dotnet/roslyn/issues/62098
    ```csharp
    ref struct R<T>
    {
        public ref R<T> Next;
    }
    ```
- [x] `_ = s.F;` should throw `NullReferenceException` if ref field is `null` - see https://github.com/dotnet/roslyn/pull/60910#discussion_r857040380
- [x] `scoped` as type name
  - [x] supported with `-langversion:10` and earlier for compat
  - [x] error with `-langversion:11`
- [x] `scoped` modifier roundtripped to metadata
- [x] `scoped` considered in overrides and interface implementation
- [x] conversion errors for mismatch of `scoped`
  - [x] for delegate conversions
  - [x] for function pointer conversions
  - [x] allow `scoped` to be added to a `ref` or `in` parameter, or to a `ref struct` parameter https://github.com/dotnet/roslyn/issues/62340
  - [x] allow `[UnscopedRef]` to be removed from an `out` parameter or from a `ref` parameter of a `ref struct` https://github.com/dotnet/roslyn/issues/62340
- [x] `scoped` included in inferred delegate types: `var f = (R x, scoped R y) => x;`
- [x] `scoped` parameters
  - [x] `ref`, `in`, `out`
  - [x] `scoped this` in extension method
  - [x] `params scoped`
- [x] `scoped` locals
  - [x] `ref`, `ref readonly`
  - [x] `const`
  - [x] `foreach` iteration variable
  - [x] `using` variable
  - [x] deconstruction declaration
  - [x] `out` declaration
  - [x] `var` and `ref var`
- [x] local with/without `scoped` modifier with scoped/unscoped initializer
- [x] `ScopedRefAttribute` changes scoped default when targeting:
  - [x] `ref` to `ref struct` parameters
  - [x] `out` parameters
- [x] `ScopedRefAttribute` disallowed in source https://github.com/dotnet/roslyn/issues/62124
- [x] `UnscopedRefAttribute`:
  - [x] member annotated with `[UnscopedRef]` cannot implement an interface member https://github.com/dotnet/roslyn/issues/64508
- [x] updated escape rules
  - [x] _ref-safe-to-escape_ for `ref` fields
  - [x] ref reassignment
  - [x] _ref-safe-to-escape_ and _safe-to-escape_ for `scoped`, `scoped ref`, `ref scoped` parameters and locals
  - [x] `struct` `this` is implicitly `scoped ref T`
  - [x] `out` parameters are implicitly `scoped out`
  - [x] `scoped` parameters affect argument contribution for _ref-safe-to-escape_ and _safe-to-escape_ of method invocation
  - [x] `scoped` parameters affect "method arguments must match" rule (arg "mixing") 
- [x] warn when a parameter could be marked `scoped` https://github.com/dotnet/roslyn/issues/64344
- [x] `SymbolDisplay`
  - [x] `ref` qualifier and ref custom modifiers
  - [x] `scoped` and `scoped ref` for parameters and locals
  - [x] `out` parameters (should we show the implicit `scoped`?)
- [x] document breaking changes:
  - [x] cannot return `out` parameter by reference
  - [x] rvalue from method invocation that returns a ref struct is _safe-to-escape_ from ... the _ref-safe-to-escape_ of all ref arguments
- [x] Test when `scoped ref` or `scoped in` cannot be passed as an argument to an ordinary `ref`/`in` parameter.
  - [x] when the target method also returns `ref struct` (RefFieldTests.ReturnRefFieldByValue)
  - [x] when the target method also returns `ref`/`ref readonly` (RefFieldTests.ReturnRefFieldByRef_03)
  - [x] when the target method also has a `ref` parameter whose type is `ref struct` (RefFieldTests.MethodArgumentsMustMatch_03)
- [x] auto-default: constructor must implicitly ref-assign a null-ref to `ref` fields which are not explicitly `ref`-assigned before all usages and returns. https://github.com/dotnet/roslyn/pull/63065
- [x] cannot make an anonymous type with ref members
- [x] disallow `void F([UnscopedRef] scoped ref int i) { }` (RefFieldTests.UnscopedScoped)
- [x] allow updated escape rules with either `-langversion:11` or RuntimeFeature.ByRefFields (i.e. NET 7) (RefFieldTests.UseUpdatedEscapeRules)
- [x] `required` ref fields (RefFieldTests.RequiredField_01, _02)
- [x] unskip test `RefFieldTests.InitRefField_UnsafeNullRef`
- [x] unskip tests from RefFieldTests.vb

## Public API 
- [x] `ScopedTypeSyntax`
- [x] `IFieldSymbol.RefKind` and `RefCustomModifiers`
- [x] `IParameterSymbol.ScopedKind`
- [x] `ILocalSymbol.ScopedKind`
- [x] `SymbolDisplay*Options` https://github.com/dotnet/roslyn/issues/63208
- [x] `ScopedRefAttribute`

## Productivity
- [x] classification for `scoped`
- [x] formatting for `scoped`
- [x] metadata as source for `scoped` attributes (extracted to #64906)
- [x] QuickInfo for `out` parameters (should we show the implicit `scoped`?) (extracted to #64906)
- [x] EE:
  - [x] Expression using `ref` field
  - [x] Expansion of instance with `ref` field https://github.com/dotnet/roslyn/issues/62156

## Open questions
- [x] diagnostic for `scoped` modifier when `ref` or `ref struct` value cannot escape?
    ```csharp
    static void F1<T>(scoped ref T t) { ... }   // warning: scoped is unnecessary
    static void F2<T>(scoped Span<T> s) { ... } // warning: scoped is unnecessary
    ```
  **Answer: don't give such a diagnostic, it will be inconvenient and disruptive to those who use scoped ref on refs which do not escape as a matter of style.**
- [x] diagnostic for `scoped out` since `out` parameters are implicitly `scoped`? **Answer: No, unless we hear further interest in such behavior.**
- [x] should we emit the `[ScopedRef]` attribute in metadata for an `out` parameter? The spec says it's implicitly `scoped out`. **Answer: Don't emit ScopedRef when parameters are implicitly scoped.**

**Comment by RikkiGibson** [comment]
Test plan contains the following item.
> - [ ] QuickInfo for `out` parameters (should we show the implicit `scoped`?)
i.e. if I have a method `void M(out int x) { }` should it display in Quick Info as `void M(scoped out int x)`.  My gut feeling here is *no*. @sharwell @dotnet/roslyn-ide for input.

**Comment by RikkiGibson** [comment]
Assigning @sharwell to the feature to reflect their IDE buddy role.

**Comment by RikkiGibson** [comment]
We've addressed everything needed for .NET 7 and moved everything else out to separate issues. Closing out the test plan.
