### ISSUE TITLE
Test plan for CheckedUserDefinedOperators feature

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#59458]
Feature branch - https://github.com/dotnet/roslyn/tree/features/CheckedUserDefinedOperators
Specification - https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/checked-user-defined-operators.md
Proposal: https://github.com/dotnet/csharplang/issues/4665

## Compiler
- [x] LangVer
- [x] sync with F# team
- [x] Confirm VB behavior (operators are ignored)
- [x] Confirm C++/CLI does not crash
- [x] Build VS

### Compiler Public APIs

- [x] SyntaxNormalizer
- [x] ClassifyConversion
    - [x] Specified position is a checked context
    - [x] No position specified (should we have an overload for specified whether to treat the conversion as checked?)
- [x] SymbolDisplay

### Syntax

- [x] `checked` on
    - [x] concrete conversion operators
    - [x] abstract conversion operators
        - [x] Definitions
        - [x] Explicit implementations
    - [x] implicit conversion operators (error)
    - [x] explicit conversion operators
    - [x] concrete unary operators
    - [x] abstract unary operators
    - [x] concrete binary operators
    - [x] abstract binary operators
- [x] Misplaced `checked`
- [x] `checked` in cref
- [x] graceful recovery on `unchecked` ([issue](https://github.com/dotnet/roslyn/issues/60394))

### Semantics

- [x] `checked` expression context calls operator
    - [x] Regular operators
    - [x] Compound assignment operators
- [x] `checked` method context calls operator
    - [x] Regular operators
    - [x] Compound assignment operators
- [x] `-checked` compiler switch calls operator
    - [x] Regular operators
    - [x] Compound assignment operators
- [x] Source requires matching unchecked operator
- [x] Paired operators in metadata can differ by everything but parameter/return type
- [x] In `unchecked` contexts, `checked` operators are ignored during lookup
    - [x] Binary operators
    - [x] Unary operators
    - [x] Conversion operators
- [x] In `checked` contexts, `unchecked` operators (regular operators that have a paired `checked` operator) are ignored during lookup
    - [x] Binary operators
    - [x] Unary operators
    - [x] Conversion operators
- [x] In `checked` contexts, regular operators that are not `unchecked` are included during lookup
    - [x] Binary operators
    - [x] Unary operators
    - [x] Conversion operators
- [x] Lifted conversion chooses `checked` conversions in `checked` contexts
- [x] DLR behavior
- [x] Expression trees contain new operator types
    - [x] Binary operators
    - [x] Unary operators
    - [x] Conversion operators
- [x] Obsolete
    - [x] Binary operators
    - [x] Unary operators
    - [x] Conversion operators

## Productivity
- [x] Declaring checked operators
- [x] Using operators in expressions
- [x] QuickInfo should show whether a checked or regular operator is used
    - [x] User-defined operators
    - [x] Intrinsic operators
- [x] `checked` keyword classification
- [x] Syntax normalizer for declarations
- [x] `checked` keyword completion https://github.com/dotnet/roslyn/pull/60183
- [x] Go to definition from operator usage and explicit interface implementation
- [x] Find all references for checked operators - doesn't work #60216
- [x] Go To Implementation
- [x] Operator completion for explicit implementation - doesn't work #60215
- [x] Implement interface fixer - doesn't work #60214 
- [x] F1 on `checked` keyword on the declaration goes to the doc page for `checked` keyword.
- [x] Formatter tests https://github.com/dotnet/roslyn/pull/60375
    - [x] Signature formatting
    - [x] Indentation inside operator
- [x] Navbar - https://github.com/dotnet/roslyn/pull/60727/
- [x] Object Browser - https://github.com/dotnet/roslyn/pull/60727/
- [x] Metadata as source - https://github.com/dotnet/roslyn/pull/60727/

## Docs
- [x] We might need to adjust F1 behavior on `checked` keyword in declarations, depending on structure of the docs. Right now it goes to a general `checked` keyword topic.

**Comment by 333fred** [comment]
I've added more to the test plan. I'll go through and check things off on Monday.

**Comment by AlFasGD** [comment]
Just tried the feature out, and I think it would be nice to have a more specific error when a user types:
```csharp
public static int operator unchecked +(int left, int right);
//                         ~~~~~~~~~
```
Saying that unchecked operators do not require the modifier. Currently, multiple unrelated errors are being shown:
![image](https://user-images.githubusercontent.com/8298332/168272401-47704cbc-b1ac-4d15-a5dc-7b83ad74e87d.png)

**Comment by AlekseyTs** [comment]
@AlFasGD This issue is not meant for tracking and discussing different aspects of the feature. If you would like to report a bug or suggestion, please, open a dedicated issue.
