### ISSUE TITLE
Test plan for "auto-default structs"

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/roslyn#60167]
Spec: dotnet/csharplang#5737

- #60176
- EnC (implicit initializations should occur after sequence point for opening `{` in constructor?)

## Compiler
- [x] add proposal to dotnet/csharplang (dotnet/csharplang#5964)
- [x] add to compiler test plan
- [x] `-langversion`
- [x] field initialization:
  - [x] when all fields are explicitly assigned
  - [x] when no fields are assigned (use `initobj`?)
      - implementation initializes each field individually.
  - [x] when no fields
  - [x] with auto-properties with `get` only; with `set`; with `init`
      - `SemanticErrorTests.CS0843ERR_UnassignedThisAutoProperty`,
      - `FlowDiagnosticTests.AutoPropInitialization4`
      - `StructConstructorTests.FieldInitializers_08`
  - [x] with field-like events
  - [x] when all sub-fields of a field are explicitly assigned
  - [x] when some sub-fields of a field are explicitly assigned
  - [x] when field is conditionally assigned
  - [x] when explicitly calling declared constructor `: this(...)`
  - [x] when explicitly calling default parameterless constructor `: this()`
  - [x] when assigning `this = default;`
  - [x] when assigning `this = default;` conditionally
  - [x] ~~when assigning to backing field of semi-auto property (i.e. using a field initializer)~~ moved to #57012
  - [x] ~~when assigning to property of semi-auto property (i.e. in a constructor)~~ moved to #57012
  - [x] when reading field before assigning
- [x] fields assigned where C#10 produces warnings with `/warn:5`
- [x] `record`
  - [x] with explicit fields
  - [x] with explicit auto-properties
- [x] disabled-by-default diagnostics:
  - [x] when all fields are explicitly assigned
  - [x] when no fields are assigned
  - [x] when diagnostics are elevated to warnings or errors
- [x] `default` assigned:
  - [x] to backing fields of auto-properties
  - [x] for field of type parameter type
  - [x] for field of `struct` type with parameterless constructor
  - [x] for field of empty `struct` type (no assignment?)
- [x] field initialization when parameters have `!!` (which runs first?)
- [x] nullable analysis treats auto-initialized fields as nullable
- [x] `#pragma warning restore` should not enable disabled diagnostics

## Productivity
- [x] Add new error codes to UpgradeProject fixer
  - [ ] upgrade from warnings?
- [x] Debugger: reposition to first sequence point in constructor (init fields?)
