### ISSUE TITLE
Test plan for "numeric IntPtr"

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#60578]
Championed issue: https://github.com/dotnet/csharplang/issues/6065
Speclet: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/numeric-intptr.md

## Compiler
- [x] Public API:
  - [x] `IsNativeIntegerType`
  - [x] `CreateNativeIntegerTypeSymbol()`
- [x] Built-in conversions are standard implicit and explicit (see PR https://github.com/dotnet/roslyn/pull/61034)
- [x] Add `TargetFramework.Net70` and use that for our tests (issue https://github.com/dotnet/roslyn/issues/61463)
- [x] spec ([PR](https://github.com/dotnet/csharplang/pull/6031))
- [x] Tied to runtime feature flag
- [x] Not tied to `-langversion`
- [x] No `[NativeInteger]` attributes emitted
- [x] Members defined on IntPtr/UIntPtr are available from IntPtr/UIntPtr and nint/nuint:
  - [x] interfaces
  - [x] static members
  - [x] instance members
  - [x] constructors
  - [x] implicit and explicit conversion operators
  - [x] overridden implementations: ToString(), GetHashCode(), Equals()
- [ ] Equivalence between nint/IntPtr and nuint/UIntPtr for:
  - [ ] interface implementations
  - [x] overloads
  - [x] partial methods
  - [x] generic type constraints
  - [x] type inference
  - [ ] type unification
- [x] Retargeting when a compilation reference that uses wrapped nint is referenced in a compilation that uses .NET 7 (see `RetargetingFromNonNumericToNumericIntPtrCorlib` and `RetargetingFromNumericIntPtrToNonNumericCorlib`)
- [x] Built-in operators for nint/nuint apply to IntPtr/UIntPtr (and IntPtr?/UIntPtr?)
  - [x] built-in conversions
  - [x] built-in unary and binary operators
- [x] Constants (in int/uint range) supported for IntPtr/UIntPtr:
  - [x] `const` allowed
  - [x] constant folding
  - [x] parameter default values
  - [x] `switch` value
- [x] fix better conversion rules ([issue](https://github.com/dotnet/roslyn/issues/61199)) and update specs accordingly
- [x] Verify with `>>>` (see `UnsignedRightShift`)
- [x] Breaking changes:
  - [x] for `checked` operator+ and operator- with IntPtr/UIntPtr
  - [x] breaking changes documented
- [x] Other scenarios called out by https://github.com/dotnet/csharplang/issues/4385

## BCL
- [x] Add runtime feature flag (tracked by https://github.com/dotnet/runtime/issues/67966, done in https://github.com/dotnet/runtime/pull/69322)
- [x] Modify `System.IntPtr` and `System.UIntPtr` (needs to include `>>>`) (not applicable)

## Productivity
- [ ] QuickInfo (validated manually in PR https://github.com/dotnet/roslyn/pull/60913, but can't be unittested because IDE tests run on .NET 6 BCL)
- [x] Classification (`SemanticClassifierTests.NativeInteger`)
- [x] MetadataAsSource (`MetadataAsSource.MetadataAsSourceTests+CSharp.TestNativeInteger`)
- [x] Prefer keyword over full type name (`UseExplicitTypeTests.InNativeIntIntrinsicType`, this should follow the preference for built-in types)
- [ ] Simplify type name
  - [ ] `using x = System.IntPtr;` should not simplify to `nint`
- [ ] Update simplification defaults to suggest updating `IntPtr` to `nint` if that option is set
  - [ ] In cref: `<see cref="nint"/>`, `<see cref="System.IntPtr"/>` (completion issue, should offer to simplify to `nint`)
- [ ] Simplify `nint x = default(nint);` to either `nint x = default;` or `nint x = 0;`

Relates to test plan for native ints: https://github.com/dotnet/roslyn/issues/38821
Relates to statics in interfaces and numerics design: https://github.com/dotnet/designs/blob/main/accepted/2021/statics-in-interfaces/README.md

**Comment by jcouv** [comment]
Feature was merged into 17.3p2

**Comment by cston** [comment]
Closing as completed.
