### ISSUE TITLE
Convert To Record Improvements

### ISSUE THREAD

**Issue by Soreloser2** [dotnet/roslyn#63849]
## Summary
While the initial offering for the Convert to Record feature is pending a merge: #63654, and can be viewed on the [features/ConvertToRecord](https://github.com/dotnet/roslyn/tree/features/ConvertToRecord) branch, there are a few more "nice to have"s and extensions for the feature.

## Known Bugs
- [ ] Support VB object creation refactoring (tracked in #63756)
  - Following the C# refactoring we should only change to the primary constructor if the object creation calls the implicit parameterless constructor (i.e. there is not an explicitly declared constructor on the type that already has no parameters, and the creation does not have parentheses). We can use assignments in the with clause to associate expressions to positional parameters, and fill in default/null for the rest of the arguments.
- [ ] multi-line documentation comments do not align properly when moved from property to constructor. Difficult edge case because most supporting code assumes we're always using single line (`///`) doc comments
- [ ] Non-primary constructors which use a base initializer are not analyzed or refactored properly. They should always be calling the `this` initializer if we have a primary constructor. Also difficult edge case because we can't necessarily associate base parameters with any respective fields unless we also dive into that constructor operation tree.
- [ ] `default` values don't use types to avoid signature conflicts (added in #63848)
- [ ]  HashCode analysis just uses `UseSystemHashCode` Analyzer, which doesn't handle all common cases where we might want to delete (such as if the user is actually using the suggested `System.HashCode`)

## Proposed Feature Extensions
- [ ] Support Non-positional conversion via a nested action list: tracked and explained in #63848
- [ ] "Fix All" support for code fix and refactoring (not started, should be able to complete without re-obtaining semantic info but would likely need serious code restructuring/redesign)
- [ ] Can we or should we move to SyntaxEditorBasedCodeFixProvider?

## Alternative Designs
- [ ] Dialog option to always (or never) delete constructors, methods, edit signature of primary constructor (or no primary constructor), potentially change fix all scope options.

**Comment by arkalyanms** [comment]
@jasonmalinowski starting with you to handle the merge with the approvals before throwing back the rest for retriage.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of broad feedback on this topic.
