### ISSUE TITLE
Test plan for "Primary Constructors" feature

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#65697]
Championed issue: https://github.com/dotnet/csharplang/issues/2691
Speclet: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/primary-constructors.md
Feature branch: https://github.com/dotnet/roslyn/tree/features/PrimaryConstructors

## Compiler
- [X] language version
- [X] syntax changes:
  - [X] `type Name;` for `class`, `struct`
  - [X] `type Name(...) ...` for `class`, `struct`
  - [X] `type Name(...) : Base(...) ...` for `class`
  - [X] error for `type Name(...) : Interface(...) ...`
  - [X] error for `type Name : Base(...) ...`
- [X] `public` primary constructor emitted
  - [x] (#70026) explicit parameterless constructor for `class C0();` or `struct S0() { }`
- [X] declared constructors must call primary constructor
- [X] error for declared constructor with matching signature
- [X] error for primary constructor on multiple `partial` declarations
- [X] parameters:
  - [x] (#70026) generic types
  - [x] (#70026) pointer types with/without `unsafe`
  - [X] default parameter values
  - [X] `params` modifier
  - [X] `this` modifier (error)
- [X] attributes on parameters:
  - [X] with no target modifier; with `param:` target; with other target (disallowed)
  - [X] `[CallerMemberName]`
  - [X] synthesized attributes: `NativeIntegerAttribute`, `DynamicAttribute`, `TupleElementNames` (see `ParameterCapturing_*_SynthesizedAttributes`)
- [X] parameter capturing in `class`, `[readonly] struct`, `[readonly] ref struct` (see `ParameterCapturing_*`)
- [X] parameter referenced in:
  - [X] instance methods and property or event accessors (capturing)
  - [X] instance field and property initializers (not capturing)
  - [X] `static` members (error)
  - [X] `const` field (error)
  - [X] other constructor (error)
  - [X] `this(x)` or `base(x)` initializer (error)
  - [X] `: Base(x)` initializer (not capturing)
  - [X] lambdas (capturing based on containing context)
  - [X] local function (capturing based on containing member)
  - [X] `static` lambdas and local functions (error if captured)
  - [X] `partial` method
- [X] parameter referenced in:
  - [X] `is x`
  - [X] `x()`
  - [X] `@x` (see `ParameterCapturing_011_EscapedIdentifier`)
  - [X] `nameof(x)`
  - [X] `lock (x)` (see `ParameterCapturing_098_Lock`)
  - [X] `using (x)` (see `ParameterCapturing_099_Using`)
  - [X] `x switch { ... }` (see `ParameterCapturing_099_MultiplePathsToNode_SwitchDispatch_02`)
  - [X] deconstruction (see `ParameterCapturing_103_Deconstruction`)
  - [X] `&x` (see `*AddressOf*`)
  - [X] `x.F` fixed size field (see `ParameterCapturing_*FixedSizeBuffer`)
  - [X] `Color Color` (see `ParameterCapturing_*_ColorColor_*`)
- [X] error capturing `ref`, `in`, `out`, or `ref struct` parameters (see `IllegalCapturingDueToRefness_*`)
- [X] name shadowing (see `ParameterScope`) from:
  - [X] field, property, event, method names
  - [X] nested type
  - [X] local function name
  - [x] (#70026) type parameter name
  - [x] (#70026) parameter in instance member, constructor, lambda, or local function
  - [x] (#70026) local in instance member, lambda, or local function
  - [X] local in `: Base(...)`: error (see `BaseArguments_17`)
  - [x] (#70026) attribute
  - [X] LINQ expression identifier (see `ParameterCapturing_010_ShadowingInMethodBody`, `ParameterCapturing_016_Query`)
- [X] definite assignment (see `DefiniteAssignment_*`)
  - [X] `out` parameters must be assigned
  - [X] use of `out` parameters before assignment
  - [X] warning for parameters that are not read
- [X] `dynamic` dispatch not allowed for `: Base(@dynamic)` initializer (see `BaseArguments_10`)
- [x] (#70056) order of evaluation: field initializers, `: Base()`
- [X] Semantic model:
  - [X] primary constructor symbol available from containing type
  - [X] `GetDeclaredSymbol()`
  - [X] `GetSymbolInfo()`
  - [X] `GetSpeculativeSymbolInfo()`, `GetSpeculativeTypeInfo()`
- [X] `LookupSymbols` and `LookupNames` for parameters
  - [X] in initializers
  - [X] in `: Base(x, y)`
  - [X] in attributes
  - [X] in members (see `ParameterScope`)
- [X] analyzer events:
  - [X] syntax events for primary constructor parameters
  - [X] syntax events for `: Base(x, y)` arguments 
  - [X] symbol events for primary constructor parameters
  - [X] `IOperation` events for synthesized constructor bodies, parameters, default values
- [X] XML doc comments:
  - [X] `param` on containing type and members
  - [X] `paramref` on containing type and members
  - [X] across `partial` declarations
- [X] capturing managed parameter makes `struct` managed (see `ParameterCapturing_056_CapturingOfAManagedParameterMakesStructManaged`)
- [X] `struct` cycles from capture (see `ParameterCapturing_*_Cycle`)
- [X] synthesized constructor not allowed on `[ComImport]` types
- [X] parameters (captured or not) referenced in lambda (see `*ParameterUsedInLambda_InPrimaryConstructor`)
- [X] warning for captured parameter passed to base constructor (see `ParameterCapturing_*CapturedAndPassedToBase*`)
- [X] nullable analysis (see `ParameterCapturing_*NullableAnalysis*`)
- [X] parameters are `readonly` in `readonly struct` (see `ParameterCapturing_*_ReadonlyContext`)
- [X] parameter assignment in `readonly struct` or `readonly` method (see `ParameterCapturing_*_ReadonlyContext`)
- [X] `ref` safety analysis of parameter references (see `ParameterCapturing_145_ReturnByRef`, etc.)
- [x] (#70050) add feature to Compiler Test Plan.md
- [x] (#70056) order of emitted fields with/without explicit fields
- [x] (#70056) error for primary constructor on `static class`
- [x] report unused parameters
- [x] `SyntaxNormalizer` (SyntaxNormalizerTests.TestSpacingOnPrimaryConstructor/TestSemicolonBody)
- [x] (#70056) structs fulfilling the `unmanaged` constraint requires binding all members first

## Public API
- [x] API review (#66914)

## IDE test pass

- [x] Language version upgrade 
- [x] Type and paste new constructs
- [x] Completion
  - [x] Type completion for parameters
  - [x] Parameter name completion 
    - [x] In base initializer
    - [x] In field initializer
    - [x] In member body 
  - [x] Dotting off of parameter name
    - [x] In base initializer
    - [x] In field initializer
    - [x] In member body 
  - [x] Identifier highlighting
    - [x] Prefix matching
    - [x] Full identifier matching
- [x] Formatting
  - [x] Format command
- [x] Automatic Brace Completion
  - [x] Parameter list
  - [x] Argument list  
- [x]  Indentation (typing Enter in an unfinished statement indents the next line)  
  - [x] Parameter list
  - [x] Argument list  
- [x] Go To definition
  - [x] For parameter
  - [x] For constructor 
- [x] Find All References
  - [x] For parameters 
  - [x] For constructor 
- [x] Colorization
  - [x] Types in parameter list
  - [x] Parameter names
- [x] Error Squiggles    
- [x] Rename of parameter
- [x] Change signature (for constructor) 
- [x] Extract method/local function for code referencing parameter 
_________
- [x] Debugging
  - [x] Stepping
  - [x] Non-captured parameters
     - [x] Show up in Locals window 
     - [x] Can be modified 
  - [x] Captured parameters
    - [x] In initializers
      - [x] Capture fields are hidden 
      - [x] Show up in Locals window, the values reflect the actual captured state. Modifications go to the the capture field. (#67266) 
      - [x] Same in Watch window. (#67266)
    - [x] Inside instance methods
      - [x] Capture fields are hidden 
      - [x] Show up in Locals window, the values reflect the actual captured state. Modifications go to the the capture field. (#67266) 
      - [x] Same in Watch window. (#67266)
_________
- [x] Edit and Continue (EnC)
  - [x] #67108, #68477.

Filed issues:
 - #67011
 - #67013
 - #67015
 - #67016
 - #67017
 - #67021
