### ISSUE TITLE
Test plan for "roles" features

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn#66722]
Spec: https://github.com/dotnet/csharplang/blob/main/proposals/extensions.md
Championed issue: https://github.com/dotnet/csharplang/issues/8697

Confirm metadata format for forward compatibility requirements before shipping. Consider marking assemblies with an attribute.

## TODO list
- remove logic for roles (`explicit` modifier, `IsExplicitExtension`, type erasure, treat extensions as static classes)
- add API guidelines to spec
- interop story with F# and VB (instance methods blocked for now)
- switch codegen to `static class`
- signature conflicts
- static scenarios
  - spec: block or allow extension resolution in `usings`
  - emit type references, satisfying constraints
  - static usings
  - problem with extension members in usings
  - spec: checking for implicit conversion when looking for compatible implicit extensions?
  - semantic model (`GetMemberGroup`, which plays in SigHelp), speculative semantic model, remaining Lookup API
  - fix downlevel support (update tests, maybe synthesize missing attribute)
  - hiding (warnings)
  - use-site diagnostics
  - dealing with substitution/unification ambiguities (`MergeEquivalentTypes`)
  - nullability
  - Public APIs (`IsExtension`)
  - XML docs
  - spec: Attributes on extension types (just use AttributeTarget.Struct?)
  - reserve `extension` keyword
  - events
  - spec: warn on slight type mismatches in extension resolution
  - Expression trees (see what we do for extension methods)
  - test ref analysis (expecting no impact)
  - pointer access, pointer element access, 
  - compilation events
  - interceptors
  - EnC
  - if we don't ship instance scenarios, we need to block them
- instance scenarios
  - use `modreq` instead of `modopt` to prevent accidental consumption of generated static members
  - erasure, access on instances of receiver type (`e.UnderlyingMember`)
  - type parameter receiver
  - merging extension methods and extension members within scopes instead of priority order
  - remaining lookup APIs
  - resolve extensions on type parameter values, adjust receiver accordingly
  - pattern-based lookups (`using`, implicit indexer access, ...)
  - patterns
  - spec: operators
  - spec: maybe add a tie breaker or preference in overload resolution 
  - indexer access on extension type
  - IOperation, CFG (should be minimal, if no new bound nodes from initial binding)
  - `[CollectionBuilder]` attribute should not have an iteration type that is context-specific (disallow GetEnumerator or Current from extensions, see `TryGetCollectionIterationType` and `ViaExtensionMethod` logic)
  - `[InterceptsLocation]` on an extension type method
  - spec: Constructors & object creation
- inheritance
  - hiding
- EE
- IDE: completion, formatting, NormalizeWhitespace
- [ ] CastUp static method for first class span type

## LDM
- [x] making `extension` contextual keywords as types (compat break)

## Compiler
- [ ] Parsing
- [ ] Extension declarations
  - [ ] LangVer
  - [ ] Base list validation:
    - [ ] Circular definition
  - [ ] SymbolDisplay
  - [ ] hiding and `new`
  - [ ] Disallow primary constructor
  - [ ] Allow `;` terminator
  - [ ] Attributes on declaration or members
    - [ ] What attribute target?
    - [ ] Obsolete
    - [ ] ComImport
  - [ ] Writing code inside extensions
    - [ ] Type of `this`
    - [ ] Lookup rules
    - [ ] Accessibility
- [ ] Emitting and decoding PE symbols
  - [ ] synthesized attributes like DynamicAttribute, TupleElementNames
  - [ ] illegal underlying types and base extensions
- [ ] Usage of extensions
  - [ ] Conversions, satisfying constraints (`unmanaged`?), satifying foreach pattern
  - [ ] Construction, with initializers
  - [ ] Entry point
- [ ] Usage of explicit extensions
- [ ] Disallow types named `extension`
- [ ] Semantic model
  - [ ] LookupSymbol in various parts of extension declaration
- [ ] public API (`IsExtension`, `IsExplicit`)
  - [ ] question on `ForTypeSyntax` in `ExtensionDeclarationSyntax` (whether to inline or extract the pair as a node)
- [ ] Document break (reserved keyword)
- [ ] Add to compiler test plan
- [ ] SyntaxNormalizer
- [ ] Debugging experience (locals of extension types should appear with correct type)
- [ ] Analyzer events
- [ ] xml docs
- [ ] Address PROTOTYPE comments
- [ ] VB
- [ ] F#
- [ ] ildasm/ilasm, decompiler
- [ ] EnC
- [ ] IOperation on usages
- [ ] async methods in extension type, capturing `this`
- [ ] interactions with collection literals
- [ ] Spec: Append calls in interpolation handler scenarios exclude extension methods and methods from extension types.
- [ ] Spec: The explicit extension extends a handler type and overrides an `Append` method, and then is explicitly used as the argument type of a method or the target type of a literal
- [ ] Spec: The explicit extension has `InterpolatedStringHandlerAttribute` on it and the original type did not
- [ ] All pattern-based usages on extension type (should include members from extended type)
  - [ ] foreach
  - [ ] using
  - [ ] deconstruction
  - [ ] lock
  - [ ] implicit indexer
- [ ] All pattern-based usages on extended type (should include members from applicable implicit extension types)

## Productivity
- [ ] Completion
  - [ ] keywords `implicit`, `explicit`, `extensions`
  - [ ] underlying and base types
- [ ] Classification (new keywords)
- [ ] Code generation (see references to `RecordDeclaration`)
- [ ] Find symbols (FAR, see references to `RecordDeclaration`)
- [ ] MetadataAsSource
