### ISSUE TITLE
Tracking issue for fixers that do not support "fix all"

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#66812]
- [ ] https://github.com/dotnet/roslyn/issues/34465
- [ ] https://github.com/dotnet/roslyn/issues/34469
- [ ] https://github.com/dotnet/roslyn/issues/34470
- [ ] https://github.com/dotnet/roslyn/issues/34471
- [ ] https://github.com/dotnet/roslyn/issues/34473
- [ ] https://github.com/dotnet/roslyn/issues/34474

**Comment by CyrusNajmabadi** [comment]
Closing out as speculative.  If we want to do this, we can assign to devs/milestones to be done in.
