### ISSUE TITLE
Test and polish IOperations

### ISSUE THREAD

**Issue by ManishJayaswal** [dotnet/roslyn#6894]
1. IExpression: http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IExpression.cs
   1. [x] https://github.com/dotnet/roslyn/issues/17587: [IExpression] IOperation unit tests for invocation arguments
   2. [x] https://github.com/dotnet/roslyn/issues/17588: [IExpression] IOperation unit tests for expressions with arguments
   3. [x] https://github.com/dotnet/roslyn/issues/17589: [IExpression] IOperation unit tests for element reference expressions
   4. [x] https://github.com/dotnet/roslyn/issues/17590: [IExpression] IOperation unit tests for conversions
   5. [x] https://github.com/dotnet/roslyn/issues/17591:  [IExpression] IOperation unit tests for unary operators
   6. [x] https://github.com/dotnet/roslyn/issues/17592: [IExpression] IOperation unit tests for binary operators
   7. [x] https://github.com/dotnet/roslyn/issues/17593: [IExpression] IOperation unit tests for lambda expressions 
   8. [x] https://github.com/dotnet/roslyn/issues/17595: [IExpression] IOperation unit tests for symbol initializer expressions
   9. [x] https://github.com/dotnet/roslyn/issues/17596: [IExpression] IOperation unit tests for array related expressions
   10. [ ] https://github.com/dotnet/roslyn/issues/17597: [IExpression] IOperation unit tests for miscellaneous expressions
   11. [x] https://github.com/dotnet/roslyn/issues/17598: [IExpression] IOperation unit tests for invalid expressions

2. IStatement: http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/IStatement.cs
   1. [x] https://github.com/dotnet/roslyn/issues/17599: [IStatement] IOperation unit tests for variable declarations 
   2. [ ] https://github.com/dotnet/roslyn/issues/17600: [IStatement] IOperation unit tests for switch statement 
   3. [x] https://github.com/dotnet/roslyn/issues/17601: [IStatement] IOperation unit tests for if statement 
   4. [x] https://github.com/dotnet/roslyn/issues/17602: [IStatement] IOperation unit tests for loop statements 
   5. [ ] https://github.com/dotnet/roslyn/issues/17603: [IStatement] IOperation unit tests for branching statements 
   6. [ ] https://github.com/dotnet/roslyn/issues/17604: [IStatement] IOperation unit tests for try/catch/finally statements
   7. [ ] https://github.com/dotnet/roslyn/issues/17605: [IStatement] IOperation unit tests for language specific statement kinds
   8. [ ] https://github.com/dotnet/roslyn/issues/17606: [IStatement] IOperation unit tests for miscellaneous statements
   9. [x] https://github.com/dotnet/roslyn/issues/17607: [IStatement] IOperation unit tests for invalid statements

**Comment by ManishJayaswal** [comment]
@genlu

**Comment by JohnHamby** [comment]
At this point this issue is too vague to be useful.

**Comment by mavasani** [comment]
@jinujoseph I am going to create separate issues for each language feature/IOperation API group for which we need to add unit tests. I am going to change this issue to a story and add check boxes for each of these issues.

**Comment by CyrusNajmabadi** [comment]
For all of these, please discuss with appropriate compiler members the subtleties involved with each.  For example: ```IOperation unit tests for loop statements```.  I know that VB has some very interesting loop statements (which may end up with all sorts of conversions/lifted-operations).  We'll want to appropriately test these sorts of things.  In other words, we should not just write a test to the mainline case and consider things done :)   

It will probably be appropriate to also spelunk into the corresponding BoundNode generation code for these operations to see all the sorts of cases they have to already deal with.

**Comment by jinujoseph** [comment]
closing this as individual tasks are maintained
