### ISSUE TITLE
Infrastructure: IDE Test cleanup

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7038]
- [ ] Extract tests that don't require editor to Workspaces and Features layer tests (#7039)
- [ ] Make workspaces and features layers tests portable to CoreCLR (#7040)
- [ ] Enable parallelism for workspaces and features layer tests (#7041)

**Comment by CyrusNajmabadi** [comment]
Closing out as unlikely to happen based on this issue.  Eitehr we need to do this or not.  If so, we should just schedule and do it.
