### ISSUE TITLE
IDE Support for new language features

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7046]
- [x] Replace event invocations with `?.Invoke()` (PR in #6629) 
- [x] Convert traditional property to auto property (PR in #5743)
- [ ] Replace with `nameof`(#7043)
- [ ] Generate quick action does not offer to generate local function (#9352)
- [x] Convert String.Format call to String interpolation (#7044)
- [x] Replace simple member body with expression bodied member (#7045)

**Comment by Pilchie** [comment]
Moving the rest of these to 2.0

**Comment by Pilchie** [comment]
Done or already tracked in projects
