### ISSUE TITLE
Improve productivity of Core Editing scenarios

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#7056]
- [x] Support "Add reference"/"Add NuGet package" in addition to Add Using (#7051)
- [ ] [Add Using] Does not offer to add reference to shared project (#8572)
- [x] Add Using refactoring should not simplify when using is within namespace block (#3716)
- [ ] Refactoring: Auto-add usings for pasted code snippets (#10272)
- [x] Completion should prefer matches that are convertible to the target type (started in PR #6878)
- [ ] Allow to Switch Back to VS2013 Style XML Comment Outlining (#10937)
- [x] Provide option for VB completion to not insert newline on enter (#7052)
- [ ] Completion should have a way to see items there is no using/reference for (#7053)
- [x] Completion should have a way to filter items by "kind" (#7054)
- [x] Completion item filtering missing filters for snippets and keywords (#14528)
- [ ] Use argument types to guide Signature Help (#6713)
- [ ] Add quick fix to generate a field and initialize from a constructor parameter (#15648)
- [ ] Completion should suggest variable names based on the type (#7055)
- [ ] C# Completion should preselect true and false for target typing (#7122)
- [ ] C# Completion should preselect based on parameter names (#9260)
- [ ] Visual Studio 15 RC - Provide intellisense for when the type at the left-hand side is an interface type (#16499)
- [ ] Support textual word based completion (#9300)
- [ ] Code Quality: Add code fix to remove a variable that is 'declared but never used' (#10284)
- [ ] Intellisense Tooltip get too long in case of many generic parameters (#5)
- [ ] IDE Feature Request: Show Caller Info Attribute values in parameter help & Quick Info (#534)
- [ ] Ability to classify fields, locals and parameters differently (#3976)
- [ ] Suggestion - Make Intellisense show "almost valid" members (#1526)
- [ ] Snippets should be smarter about inserting accessibility modifiers (#7988)
- [ ] Code Quality: Give warning if have multiple enumerations of an IEnumerable (#10276)
- [ ] Core Editing: Support fuzzy matching in auto-completion (#10277)
- [ ] Core Editing: IntelliSense is fighting me when I type things that don't exist yet (#10279)
- [ ] Core Editing: Support the ability to share snippets (#10282)
- [ ] Unreachable code should be faded out, code fix should remove all unreachable code (#6970)
- [ ] Customizing Code Fix previews (#3590)
- [ ] Need to have a way to specify group/order for CodeFixAction provided by CodeFixProvider (#3994)
- [ ] Code Quality: Support for nullref analysis (#10301)
- [ ] Feature Request: Add quick fixes for reference to inaccessible type (#10337)
- [ ] Preselect default(T) after = in a non-primitive parameter declaration (#7113)
- [ ] Completion word breaking heuristics failing with leading _ (#7912)
- [ ] Introduce alias for using statements (#13423)
- [ ] Lightbulb for BC30002 doesn't offer to "fix all" (#2270)
- [x] Completion: list partial classes after "partial class" (#7213)
- [ ] Quick fix for CS0650 (bad array declarator) (#14687)
- [ ] IntelliSense should provide completions from the base class for the new keyword (#15207)
- [ ] Proposal: Automatic documentation for potential exceptions (#15573)
- [ ] Provide option to not automatically format on "Uncomment selection" (#15331)
- [ ] Add quick fix to generate a field and initialize from a constructor parameter (#15648)
- [ ] Diagnostic for invalid String.Format expressions (#15856)
- [ ] Is it possible to add intellisense to dynamic object with something like JSDoc? (#15974)

**Comment by rchande** [comment]
Also https://github.com/dotnet/roslyn/issues/7122 ?

**Comment by Pilchie** [comment]
@rchande: Added, but wouldn't that happen automatically as part of #6878?

**Comment by Pilchie** [comment]
Should be migrated to https://github.com/dotnet/roslyn/projects/7 and https://github.com/dotnet/roslyn/projects/6

**Comment by jmarolf** [comment]
moved to projects
