### ISSUE TITLE
Improve rule management and suppression experience in the editor.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn#7099]
There are a couple of things we could do to make rule management and suppression management experiences better from the error list:

- [ ] Provide a way to disable a rule from the lightbulb and errorlist (#6728)
- [ ] Grey out unused suppressions in source (#4262)

While we are doing this work, we should address the backlog item about adding VS integration tests for this area:
- [ ] Pending test work items for Disconnected baselining feature work (#5354)

**Comment by CyrusNajmabadi** [comment]
Not planning on any more work here.
