### ISSUE TITLE
Move unix infrastructure to CoreCLR

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#7139]
Work remaining to get our Linux / Mac infrastructure ported to fully use CoreCLR

- [x] Public Sign support #6915 
- [ ] Include MSBuild Task + Targets in netcore NuGet #6017 
- [x] Make build tools run on CoreCLR #7136
- [x] Port compiler tests to portable profile #7137
- [x] Move unix unit tests to run under CoreCLR xunit #7138
- [x] Move to netcore MSBuild #7755

**Comment by agocke** [comment]
The MSBuild Task/Targets are no longer a blocker for this, so resolving it.
