### ISSUE TITLE
Test Plan for "Ref Struct Interfaces" feature

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/roslyn#72124]
Championed proposal: https://github.com/dotnet/csharplang/issues/7608
Speclet: https://github.com/dotnet/csharplang/blob/main/proposals/csharp-13.0/ref-struct-interfaces.md
Feature branch: https://github.com/dotnet/roslyn/tree/features/RefStructInterfaces

# Compiler
- [x] language version
  - [x] interface implementation
  - [x] `allows ref struct`
  - [x] generic type substitution
  - [x] `using`, `foreach`, etc. with *ref like type* interface implementation
- [x] target runtime support: `RuntimeFeature.ByRefLikeGenerics`
  - [x] `allows ref struct`
- [x] `ref struct` interface implementation
  - [x] implicit / explicit implementation
  - [x] default interface methods, properties, indexers, events, with `virtual` / `sealed` modifiers (see `*_DefaultImplementation`)
- [x] `allows ref struct` constraint (see `AllowsConstraint_*`)
  - [x] must be last
  - [x] duplicated constraint
  - [x] with `struct`, `class`, `new()`, `unmanaged`, `notnull`, `default`, interface, class
  - [x] on `partial` type / method
  - [x] on override
  - [x] on implicit / explicit implementation
  - [x] constraint emitted to metadata
  - [x] constraint emitted to ref assembly (#74389, AllowsConstraint_01_SimpleTypeTypeParameter)
- [x] calling instance members on value of type parameter with `allows ref struct`
  - [x] error calling `System.Object` methods
  - [x] error calling *non-virtual* default interface member (ERR_BadNonVirtualInterfaceMemberAccessOnAllowsRefLike error CS9246: A non-virtual instance interface member cannot be accessed on a type parameter that allows ref struct.)
  - [x] (open design question) warning calling *virtual, non-abstract* default interface member
- [x] conversions
  - [x] *from:* `ref struct`
  - [x] *from:* type parameter with `allows ref struct`, with/without `struct` constraint
  - [x] *from:* implemented/unimplemented interface
  - [x] *to:* `System.Object`
  - [x] *to:* `ref struct`
  - [x] *to:* implemented/unimplemented interface
  - [x] *to:* same type parameter (IdentityConversion_01 .. IdentityConversion_04)
  - [x] *to:* type parameter with/without `allows ref struct`, with/without `struct` constraint
  - [x] *to:* type parameter with `allows ref struct`, with/without `struct` constraint, with *implemented* interface constraint
  - [x] *to:* type parameter with `allows ref struct`, with/without `struct` constraint, with *unimplemented* interface constraint
  - [x] *to:* type parameter with/without `allows ref struct`, with/without `struct` constraint, `where T : U`/`where `U : T`
- [x] `is` operator: `value is Type` (see `IsOperator_*`)
  - [x] *value:* `ref struct` with/without interface implementation
  - [x] *value:* interface
  - [x] *value:* type parameter with/without `allows ref struct`, with/without `struct` constraint, with/without interface constraint
  - [x] *type:* `ref struct`
  - [x] *type:* interface
  - [x] *type:* same type parameter
  - [x] *type:* type parameter with/without `allows ref struct`, with/without `struct` constraint, with/without interface constraint
  - [x] *type:* type parameter with `class` constraint, with/without interface constraint (#74389, IsOperator_05, IsOperator_07)
  - [x] *type:* type parameter with/without `allows ref struct`, with/without `struct` constraint, `where T : U`/`where `U : T` 
- [x] `is` pattern: `value is Type t` (see `IsPattern_*`)
  - [x] *see cases from `is` operator above*
- [x] `as` operator: `value as Type` (see `AsOperator_*`)
  - [x] *see cases from `is` operator above*
- [x] generic type substitution
  - [x] `ref struct` substituted for type parameter
    - [x] without `allows ref struct`
    - [x] with `allows ref struct`
    - [x] with satisfied interface constraints
    - [x] with unsatisfied interface constraints
    - [x] with valid variance  (#74389, ImplementAnInterface_05_Variance)
    - [x] with invalid variance (#74389, ImplementAnInterface_12_Variance_ErrorScenarios)
  - [x] type parameter with `allows ref struct` substituted for type parameter  (#74389, ImplementAnInterface_03)
    - [x] *see cases above*
  - [x] type parameter without `allows ref struct` substituted for type parameter (ConstraintsCheck_04)
    - [x] *see cases above*
  - [x] ~~`delegate` type variance (...?)~~
- [x] field / auto-property using type parameter with `allows ref struct`
  - [x] instance field / auto-propertyin `ref struct` (allowed)
  - [x] instance field / auto-propertyin `struct`, `class` (disallowed)
  - [x] `static` field / auto-property (disallowed)
  - [x] `record` primary constructor parameter (disallowed)
  - [x] `ref struct` primary constructor parameter (disallowed)
- [x] using type parameter with `allows ref struct` *(extend `IsRefLikeType` checks)*
  - [x] value in anonymous type initializer (disallowed)
  - [x] in LINQ query with implicit anonymous type
  - [x] value in `makeref` (disallowed)
  - [x] type of `ref` field (disallowed)
  - [x] array element type (disallowed)
  - [x] inline array element type (disallowed)
  - [x] `async` parameter type (disallowed)
  - [x] value in expression tree (disallowed)
  - [x] delegate receiver (disallowed)
  - [x] conditional access `?.` result type, with `struct` constraint (disallowed)
  - [x] conditional access `?.` receiver type, without `struct` constraint
  - [x] type argument to `dynamic` call (disallowed)
  - [x] receiver to `dynamic` call (disallowed)
  - [x] captured in lambda or local function (disallowed)
  - [x] error for method signature with `T?` when `where T : struct, allows ref struct` (ConstraintsCheck_06)
- [ ] ref safety analysis for instance of `allows ref struct` *(extend `IsRefLikeType` checks)*
  - [ ] `new T()` instance
  - [ ] `scoped T` instance
  - [ ] cannot assign instance to `static` field (Field, AutoProperty ?)
  - [x] cannot create `T[]` (InArrayType_01)
  - [x] *return only* scope (see `Return*`)
  - [x] *method arguments must match* (see `MethodArgumentsMustMatch_*`)
- [x] `null` checking with value of type parameter with `allows ref struct` (see `NullCheck_*`)
  - [x] `value == null`, `value != null`, `!(value == null)`, `!(value != null)`
  - [x] `value is null`, `value is not null`, `!(value is null)`, `!(value is not null)`
  - [x] `value == null` when type parameter has `struct` constraint
- [x] object creation: `new T()` (see `ObjectCreation_*`)
  - [x] with object initializer
  - [x] *within* object initializer
  - [x] with `struct` constraint
  - [x] with `Activator.CreateInstance<T>()` with/without `allows ref struct` (see `SystemActivatorCreateInstance_*`)
  - [x] collection expression target type
- [x] `scoped` with type parameter with `allows ref struct`
  - [x] local
  - [x] method parameter
  - [x] lambda and local function parameters  (#74389, ScopedTypeParameter_01)
  - [x] `params T` implicitly `scoped`
  - [x] `scoped` mismatch in `override`
  - [x] `scoped` mismatch in `partial` method  (#74389, ScopedTypeParameter_03)
  - [x] `scoped` mismatch in delegate   (#74389, ScopedTypeParameter_04)
- [x] `[UnscopedRef]` on interface members (see `UnscopedRefIn*`)
  - [x] language version: `[UnscopedRef]` on interface members, interface implementations
  - [x] on interface methods, properties, indexers, accessors
  - [x] on member with *no modifier*, `abstract`, `virtual`, `sealed`
  - [x] implemented on `class`, `struct`, `ref struct`, `interface`
  - [x] implemented explicitly (UnscopedRefInImplementation_*)
  - [x] implemented implicitly with/without `[UnscopedRef]` (UnscopedRefInImplementation_*)
  - [x] diagnostic for unsafe `[UnscopedRef]` mismatch with implicit implementation
  - [x] ref safety analysis at callsite with instance of interface constrained/not constrained to `struct` (see `MethodArgumentsMustMatch_*`, etc. cloned from RefFieldTests.cs)
  - [x] defensive copy with instance of interface constrained/not constrained to `struct` (see `DefensiveCopy_*`)
- [x] `using`: implementing `IDisposable` and/or pattern `Dispose()` (see `Using_*`)
  - [x] with `ref struct` implementing interface with/without pattern
  - [x] with type parameter with `allows ref struct` implementing interface and/or pattern, with/without `struct` constraint
- [x] `foreach` (see `Foreach_*`)
  - [x] `IEnumerable`: *see cases in `using` above*
  - [x] `IEnumerable<T>`: *see cases in `using` above*
  - [x] `IEnumerator`: *see cases in `using` above*
  - [x] `IEnumerator<T>`: *see cases in `using` above*
  - [x] `IDisposable`: *see cases in `using` above*
- [x] `await using` (see `AwaitUsing_*`)
  - [x] `IAsyncDisposable`: *see cases in `using` above*
- [x] `await foreach` (see `AwaitForeach_*`)
  - [x] `IAsyncEnumerable<T>`: *see cases in `using` above*
  - [x] `IAsyncEnumerator<T>`: *see cases in `using` above* *(is explicit implementation only tested?)* (AwaitForeach_IAsyncEnumerableT_03?)
  - [x] `IAsyncDisposable`: *see cases in `using` above*
- [x] anonymous delegates (see `AnonymousDelegateType_*`)
  - [x] with `ref struct` parameter types
  - [x] with `allows ref struct` parameter types
  - [x] `System.Func<>` and `System.Action<>` with/without `allows ref struct` constraints
  - [x] synthesized delegate type parameter has `allows ref struct` constraint if needed
- [x] `-langversion:12` and earlier: consuming generic types and methods with type parameters with `allows ref struct`
  - [x] construct generic type with *non `ref struct`* (ConstraintsCheck_07)
  - [x] call generic method with *non `ref struct`* (ConstraintsCheck_02)
- [x] public API
  - [x] `ITypeParameterSymbol.AllowsRefLikeType`
  - [x] `RuntimeCapability.ByRefLikeGenerics`
- [x] VB
  - [x] public API supported
  - [x] consuming generic types and methods with type parameters with `allows ref struct`
    - [x] construct generic type with *non `ref struct`* (AllowsConstraint_01)
    - [x] call generic method with *non `ref struct`* (AllowsConstraint_01)
  - [x] error overriding or implementing generic methods with type parameters with `allows ref struct`
- [x] open questions for Language Design
  - [x] `allows` or `allow`?
  - [x] other open questions?

# Productivity
- [x] Colorization for `allows ref struct`
- [x] completion for `allows ref struct`
  - [x] for `allows`  (with #73608 in place)
  - [x] for `ref`
  - [x] for `struct`
- [x] Language version upgrade is offered
- [ ] F1 for `allows ref struct` (tracked by https://github.com/dotnet/roslyn/issues/74604)
  - [ ] on `allows` **(doesn't work at the moment)**
  - [ ] on `ref` **(goes to a wrong page at the moment)**
  - [ ] on `struct` **(goes to a wrong page at the moment)**
- [x] Hovering over a declaration displays the constraint in the tooltip. 
- [x] Implement interface on `ref struct`
  - [x] implicitly
  - [x] explicitly
- [x] GoToImplementation on an interface finds implementation on a `ref struct`
- [x] GoToImplementation on an interface method finds implicit/explicit implementation within a `ref struct`
- [x] FindAllReferences on an interface finds implementation on a `ref struct`
- [x] FindAllReferences on an interface method finds implicit/explicit implementation within a `ref struct`
- [x] GoToDefinition on an interface implemented by a `ref struct` goes to the interface
- [x] GoToDefinition on an implicit/explicit implementation of an interface method within a `ref struct` goes to the method in the interface
- [x] completion for `override` of generic method with `allows ref struct` constraint is offered and generates correct code
- [x] GoToImplementation on a virtual generic method with `allows ref struct` constraint finds an override
- [x] FindAllReferences on a virtual generic method with `allows ref struct` constraint finds a call site
- [x] GoToDefinition on an override goes to the overridden generic method with `allows ref struct` constraint
- [x] Implement generic interface method with `allows ref struct` constraint
  - [ ] implicitly **(doesn't copy the `allows ref struct` constraint at the moment)** (tracked by https://github.com/dotnet/roslyn/issues/74605)
  - [x] explicitly
- [x] GoToImplementation on a generic method with `allows ref struct` constraint finds an explicit/implicit implementation
- [x] FindAllReferences on a generic method with `allows ref struct` constraint finds an explicit/implicit implementation
- [x] GoToDefinition on an explicit/implicit implementation goes to the implemented generic method with `allows ref struct` constraint

**Comment by AlekseyTs** [comment]
CC @cston, @jjonescz
