### ISSUE TITLE
Follow up workitems for use var codestyle

### ISSUE THREAD

**Issue by balajikris** [dotnet/roslyn#9155]
This issue tracks to dos remaining work for #7062
Completed so far: #8045 
- [ ]  Make simplifier work with new use var options
  - \- [x] ~~upgrade existing code gen features to work with new use var options~~. (Implemented in #9326)
- [x]  ~~Finalize and freeze UI and strings for preview~~ (Implemented in #9286)
  - \- [ ] better keyboard navigation, high contrast support, screen reader friendliness, testing in high DPI et al.
- [x]  ~~Implement Fix All~~ (Implemented in #9200)
  - \- [ ] consider changing to a single diagnostic/fixer because it is better for fix-all scenarios.
- [x] ~~Name feedback from #8045~~ (Implemented in #10352)
  - typing -> type
  - var <-> implicit consistency
  - key, value consistency in resources
  - Notification -> Severity (until we find a better term).

Future Improvements:
- [ ]  ~~Better options preview - update preview to reflect current set of feature related option settings instead of the currently selected option.~~
- [ ]  ~~Go to option settings from light bulb preview~~ (WIP [`balajik:NavigateToOptionsPage`](https://github.com/balajikris/roslyn/tree/NavigateToOptionsPage)). 
- [ ]  misc improvements (WIP [`balajik:UseVarWhenApparentFixes`](https://github.com/balajikris/roslyn/tree/UseVarWhenApparentFixes))

**Comment by Pilchie** [comment]
@dpoeschl how much of this is done - do we need to do more?

**Comment by Pilchie** [comment]
I'm going to call this done at this point.
