### ISSUE TITLE
Support Cross Language navigation and refactoring

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn#9199]
- [ ] Find References and rename should find references in closed .aspx and .cshtml pages (#9194)
- [ ] Goto Definition F# to C# and Vice Versa (#8105)
- [ ] HTML in a .cshtml file in a section that is marked as unnecessary, does not get faded out (#12284)
- [ ] Grey out ToString() calls in a razor render action (#12893)
- [ ] Codelens does not work well in Websites (#1758)

**Comment by Pilchie** [comment]
Moved to https://github.com/dotnet/roslyn/projects/20.
